* Xfce Desktop Environment
  :PROPERTIES:
  :CUSTOM_ID: sec-xfce
  :END:

To enable the Xfce Desktop Environment, set

#+BEGIN_EXAMPLE
  services.xserver.desktopManager = {
    xfce.enable = true;
    default = "xfce";
  };
#+END_EXAMPLE

Optionally, /compton/ can be enabled for nice graphical effects, some
example settings:

#+BEGIN_EXAMPLE
  services.compton = {
    enable          = true;
    fade            = true;
    inactiveOpacity = "0.9";
    shadow          = true;
    fadeDelta       = 4;
  };
#+END_EXAMPLE

Some Xfce programs are not installed automatically. To install them
manually (system wide), put them into your
[[#opt-environment.systemPackages][???]].

To enable /Thunar/ volume support, put

#+BEGIN_EXAMPLE
   = true;
#+END_EXAMPLE

into your /configuration.nix/.

There is no authentication agent automatically installed alongside Xfce.
To allow mounting of local (non-removable) filesystems, you will need to
install one. Installing /polkit_gnome/, a rebuild, logout and login did
the trick.

Even after enabling udisks2, volume management might not work. Thunar
and/or the desktop takes time to show up. Thunar will spit out this kind
of message on start (look at =journalctl --user -b=).

#+BEGIN_EXAMPLE
  Thunar:2410): GVFS-RemoteVolumeMonitor-WARNING **: remote volume monitor with dbus name org.gtk.Private.UDisks2VolumeMonitor is not supported
#+END_EXAMPLE

This is caused by some needed GNOME services not running. This is all
fixed by enabling "Launch GNOME services on startup" in the Advanced tab
of the Session and Startup settings panel. Alternatively, you can run
this command to do the same thing.

#+BEGIN_EXAMPLE
  $ xfconf-query -c xfce4-session -p /compat/LaunchGNOME -s true
#+END_EXAMPLE

A log-out and re-log will be needed for this to take effect.
