diff -dur src.old/linux/makefile src.new/linux/makefile
--- src.old/linux/makefile	2018-01-04 20:49:00.000000000 +0300
+++ src.new/linux/makefile	2018-02-15 12:32:02.913011604 +0300
@@ -28,8 +28,8 @@
 CPP = g++
 CPPFLAGS = -I.. -I../gwnum -O2 -march=i486 -malign-double
 
-LFLAGS = -Wl,-M -Wl,-L/usr/local/lib
-LIBS = ../gwnum/gwnum.a ../gwnum/gwnum.ld -lm -lpthread -Wl,-Bstatic -lhwloc -Wl,-Bstatic -lcurl -Wl,-Bdynamic -lrt -lstdc++ -ldl -lgmp
+LFLAGS =
+LIBS = ../gwnum/gwnum.a ../gwnum/gwnum.ld -lm -lpthread -lhwloc -lcurl -lrt -lstdc++ -ldl -lgmp
 
 FACTOROBJ = factor32.o
 LINUXOBJS = prime.o menu.o
diff -dur src.old/linux64/makefile src.new/linux64/makefile
--- src.old/linux64/makefile	2018-01-04 20:49:00.000000000 +0300
+++ src.new/linux64/makefile	2018-02-15 12:32:28.836286995 +0300
@@ -26,9 +26,9 @@
 CPP = g++
 CPPFLAGS = -I.. -I../gwnum -DX86_64 -O2
 
-LFLAGS = -Wl,-M -Wl,-L/usr/local/lib
+LFLAGS =
 #LIBS = ../gwnum/gwnum.a ../gwnum/gwnum.ld -lm -lpthread -Wl,-Bstatic -lhwloc -Wl,-Bstatic -lcurl -Wl,-Bdynamic -lrt -lstdc++ -lz -lxml2 -ldl -lgmp
-LIBS = ../gwnum/gwnum.a ../gwnum/gwnum.ld -lm -lpthread -Wl,-Bstatic -lhwloc -Wl,-Bstatic -lcurl -Wl,-Bdynamic -lrt -lstdc++ -ldl -lgmp
+LIBS = ../gwnum/gwnum.a ../gwnum/gwnum.ld -lm -lpthread -lhwloc -lcurl -lrt -lstdc++ -ldl -lgmp
 
 FACTOROBJ = factor64.o
 LINUXOBJS = prime.o menu.o
diff -dur src.old/macosx64/makefile src.new/macosx64/makefile
--- src.old/macosx64/makefile	2018-01-04 20:49:02.000000000 +0300
+++ src.new/macosx64/makefile	2018-02-15 12:33:32.401902535 +0300
@@ -12,7 +12,7 @@
 CPP = g++
 CPPFLAGS = -I.. -I../gwnum -I../linux -O2 -DX86_64 -DCOMMAND_LINE_MPRIME -m64
 
-LFLAGS = -m64 -Wl,-no_pie -L/usr/local/lib
+LFLAGS = -m64 -Wl,-no_pie
 LIBS   = ../gwnum/amd64/release/gwnum.a -lm -lpthread -lhwloc -lcurl -framework IOKit -framework CoreFoundation -lstdc++ -lgmp
 
 FACTOROBJ = ../prime95/macosx64/factor64.o
