diff -ur admin.orig/runit-2.1.2/src/Makefile admin/runit-2.1.2/src/Makefile
--- admin.orig/runit-2.1.2/src/Makefile	2014-08-10 20:22:35.000000000 +0200
+++ admin/runit-2.1.2/src/Makefile	2014-10-15 13:04:02.892937939 +0200
@@ -234,7 +234,6 @@
 
 hasshsgr.h: chkshsgr choose compile hasshsgr.h1 hasshsgr.h2 load \
 tryshsgr.c warn-shsgr
-	./chkshsgr || ( cat warn-shsgr; exit 1 )
 	./choose clr tryshsgr hasshsgr.h1 hasshsgr.h2 > hasshsgr.h
 
 haswaitp.h: choose compile haswaitp.h1 haswaitp.h2 load trywaitp.c
