include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_sd_cspdl

security_sd_cspdl_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_sd_cspdl_HEADER_FILES_DIR = lib

security_sd_cspdl_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
