#!@bash@/bin/bash
#
# Dummy init file for syslog, hacketyhack!
#
# chkconfig: 2345 55 25
# description: OpenSSH server daemon
#
# processname: sshd

# source function library
source @initscripts@/functions

# pull in sysconfig settings
#[ -f /etc/sysconfig/sshd ] && . /etc/sysconfig/sshd

RETVAL=0
prog=@nicename@

startService()
{
	# just do networking
	echo -n "Starting $prog:"
	@syslog@/usr/sbin/syslogd
	@syslog@/usr/sbin/klogd
}

stopService()
{
	echo -n "Stopping $prog:"
	kill `cat /var/run/syslogd.pid`
	kill `cat /var/run/klogd.pid`
}

reloadService()
{
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		reload
		;;
	status)
		status
		;;
	name)
		name
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		RETVAL=1
esac
exit $RETVAL
