--- ./lib/Makefile	2014-11-18 08:16:19.000000000 -0800
+++ ./lib/Makefile	2015-05-23 14:48:31.000000000 -0700
@@ -6,12 +6,12 @@
 all: libre2_stubs.a dllre2_stubs.so
 
 dllre2_stubs.so libre2_stubs.a: stubs.o $(LIBRE2)
-	ocamlmklib -oc re2_stubs stubs.o $(LIBRE2) -lstdc++
+	ocamlmklib -oc re2_stubs stubs.o $(LIBRE2) -lc++
 	rm libre2_stubs.a # ocamlmklib just includes $(LIBRE2) inside the stubs archive
 	cp $(LIBRE2) libre2_stubs.a && ar r libre2_stubs.a stubs.o
 
 stubs.o: stubs.cpp stubs.h util.h enum_x_macro.h
-	g++ -O2 -DPIC -fPIC -g -pipe -DCAML_NAME_SPACE -Wall -I. -I../../../include \
+	$(CXX) -O2 -DPIC -fPIC -g -pipe -DCAML_NAME_SPACE -Wall -I. -I../../../include \
 	-I$(RE2_HOME) -I$(ocaml-version-selected-include-path) -c stubs.cpp
 
 #stubs.o: %.o: %.cpp %.h
