#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[@]}")"; cd -P "$(dirname "$(readlink "${BASH_SOURCE[@]}" || echo .)")"; pwd)

cd -- "${SCRIPT_DIRECTORY}"

./update-from-overlay

./update-manual
git commit -m "emacs.pkgs.manualPackages: $(date --iso)" -- .
