#!/usr/bin/env bash
set -euo pipefail

# Classic "where I am" block
# https://www.binaryphile.com/bash/2020/01/12/determining-the-location-of-your-script-in-bash.html
SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); cd -P $(dirname $(readlink ${BASH_SOURCE[0]} || echo .)); pwd)
cd "${SCRIPT_DIR}"

./update-from-overlay

./update-manual
git commit -m "emacs.pkgs.manualPackages: $(date --iso)" -- .
