#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[@]}")"; cd -P "$(dirname "$(readlink "${BASH_SOURCE[@]}" || echo .)")"; pwd)

cd -- "${SCRIPT_DIRECTORY}"

nix-build --no-out-link update-manual.nix | xargs -n 1 -P $(nproc) bash -c
