# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, filepath, hspecMeta }:

cabal.mkDerivation (self: {
  pname = "hspec-discover";
  version = "2.0.2";
  sha256 = "1439134sdgwimjihjy06g4vq3bkym97da4z1zkgxgj91ljfwlb2i";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ filepath ];
  testDepends = [ filepath hspecMeta ];
  noHaddock = true;
  meta = {
    homepage = "http://hspec.github.io/";
    description = "Automatically discover and run Hspec tests";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
