source 'https://rubygems.org'
gem "fusuma"
gem "fusuma-plugin-appmatcher"
gem "fusuma-plugin-keypress"
gem "fusuma-plugin-sendkey"
gem "fusuma-plugin-tap"
gem "fusuma-plugin-wmctrl"

# I've not activated the following plugins for the reasons given below.

# touchscreen needs specific h/w support I don't have access to, so I can't confirm
# if it's problem free.  A quick check didn't reveal any problems.
#gem "fusuma-plugin-touchscreen"

# thumbsense pulls in remap, and at best remap requires further configuration to allow the use access to event devices.
#gem "fusuma-plugin-thumbsense"
#gem "fusuma-plugin-remap"
