# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "gcr-3.18.0";

  src = fetchurl {
    url = mirror://gnome/sources/gcr/3.18/gcr-3.18.0.tar.xz;
    sha256 = "d4d16da5af55148a694055835ccd07ad34daf0ad03bdad929bf7cad15637ce00";
  };
}
