# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
# TODO: This format file is obsolete, consider migrating to JSON.

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "BCrypt.Net-Next";
    version = "4.0.3";
    hash = "sha256-BxXHAjIV2xBuRPUezzC+5jhaHiQhgnqTk1k1ko3D6Ds=";
  })
  (fetchNuGet {
    pname = "BouncyCastle.Cryptography";
    version = "2.2.1";
    hash = "sha256-KDNexXG10Ub5G0M5BOvaFDByGPiSo0HG8GJWWB473Y0=";
  })
  (fetchNuGet {
    pname = "GetText.NET";
    version = "1.7.14";
    hash = "sha256-IR27r7SZJFomN/bu4hO5SeQNGr67DQREIKdjsV7RICc=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.25.1";
    hash = "sha256-UfP/iIcARptUcTVptj/5JQ9Jz9AG3aj+iKotsetOnH0=";
  })
  (fetchNuGet {
    pname = "K4os.Compression.LZ4";
    version = "1.3.5";
    hash = "sha256-M0FaJTS3XRBp5tV02BhrrOLVyzP39cQnpEVY8KGNads=";
  })
  (fetchNuGet {
    pname = "K4os.Compression.LZ4.Streams";
    version = "1.3.5";
    hash = "sha256-BhR48hN/7z2NVgMw1MRnilpjAUNMZ0LDDhmVYnCXoCY=";
  })
  (fetchNuGet {
    pname = "K4os.Hash.xxHash";
    version = "1.0.8";
    hash = "sha256-ILTWT8NFB7itGpDloJh65B5ZuWHrN2dOUQdm8gNy4W8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Data.Sqlite";
    version = "6.0.11";
    hash = "sha256-K+2ZSdaQ9XrAglqxjlIkwBj4NlHhV7FvHTfNCM11u7k=";
  })
  (fetchNuGet {
    pname = "Microsoft.Data.Sqlite.Core";
    version = "6.0.11";
    hash = "sha256-ndL66WlBdAOU6V8k23d/T11r0s8gnBqbGWRZF9Bc7AU=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.0.0";
    hash = "sha256-IEvBk6wUXSdyCnkj6tHahOJv290tVVT8tyemYcR0Yro=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "3.1.0";
    hash = "sha256-cnygditsEaU86bnYtIthNMymAHqaT/sf9Gjykhzqgb0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    hash = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKAuN4bjfaQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "4.7.0";
    hash = "sha256-GHxnD1Plb32GJWVWSv0Y51Kgtlb+cdKgOYVBYZSgVF4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "6.0.0";
    hash = "sha256-N9EVZbl5w1VnMywGXyaVWzT9lh84iaJ3aD48hIBk1zA=";
  })
  (fetchNuGet {
    pname = "ModFramework";
    version = "1.1.7";
    hash = "sha256-fKP5njd+98RYQ/1tqaT0vyIalZbcSUQdo50ucQ7F1hk=";
  })
  (fetchNuGet {
    pname = "Mono.Cecil";
    version = "0.11.4";
    hash = "sha256-HrnRgFsOzfqAWw0fUxi/vkzZd8dMn5zueUeLQWA9qvs=";
  })
  (fetchNuGet {
    pname = "MonoMod";
    version = "22.5.1.1";
    hash = "sha256-VB1xZV+MLAzB/e6uTKW2/IEy9Qzo6vzsxg5ot1bWiPs=";
  })
  (fetchNuGet {
    pname = "MonoMod.RuntimeDetour";
    version = "22.5.1.1";
    hash = "sha256-ivxQJ6VWxzapaxkDvkRZvDQVgpfmFP1afRlx6yolBXM=";
  })
  (fetchNuGet {
    pname = "MonoMod.RuntimeDetour.HookGen";
    version = "22.5.1.1";
    hash = "sha256-jKPij21zrysQO8MnzECpJKVAqil5ZdODyGZOx7j0dRg=";
  })
  (fetchNuGet {
    pname = "MonoMod.Utils";
    version = "22.5.1.1";
    hash = "sha256-5m6C8anC0Z4Ihaxg6PTmXU7UOGiyzV+byZDO8+w/kl8=";
  })
  (fetchNuGet {
    pname = "MySql.Data";
    version = "8.4.0";
    hash = "sha256-fbNsIdRJVbD7NfAKhDJWDq5m5vXcRGzl9DBzQytM4cA=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    hash = "sha256-K2tSVW4n4beRPzPu3rlVaBEMdGvWSv/3Q1fxaDh4Mjo=";
  })
  (fetchNuGet {
    pname = "NuGet.Common";
    version = "6.3.1";
    hash = "sha256-N6NMNL4d2IQsa/AEjyBesbStXTtR8kaL2e7aW7BdBvs=";
  })
  (fetchNuGet {
    pname = "NuGet.Common";
    version = "6.3.4";
    hash = "sha256-GDzEyx9/wdVOUAri94uoDjChmfDnBhI90nBfzoHarts=";
  })
  (fetchNuGet {
    pname = "NuGet.Configuration";
    version = "6.3.1";
    hash = "sha256-Ha04pwa124ptbBH/PBn45dBGpDIPKcMDd+Fil91g728=";
  })
  (fetchNuGet {
    pname = "NuGet.Configuration";
    version = "6.3.4";
    hash = "sha256-qXIONIKcCIXJUmNJQs7MINQ18qIEUByTtW5xsORoZoc=";
  })
  (fetchNuGet {
    pname = "NuGet.Frameworks";
    version = "6.3.1";
    hash = "sha256-FAzvIULDH4/MnutbHL3NUZwpzcBAu0qgSKitFSTlbJY=";
  })
  (fetchNuGet {
    pname = "NuGet.Frameworks";
    version = "6.3.4";
    hash = "sha256-zqogus3HXQYSiqfnhVH2jd2VZXa+uTsmaw/uwD8dlgY=";
  })
  (fetchNuGet {
    pname = "NuGet.Packaging";
    version = "6.3.1";
    hash = "sha256-YiHpqIbOmfYMtJKACeL2nJ5oRngHTPcLN8e4+6IBggs=";
  })
  (fetchNuGet {
    pname = "NuGet.Packaging";
    version = "6.3.4";
    hash = "sha256-1LKM5vgfNKn8v2LcqialwmcynACISR57q13n7I2lQbU=";
  })
  (fetchNuGet {
    pname = "NuGet.Protocol";
    version = "6.3.1";
    hash = "sha256-9dYUTW/oor665WSDG6mu7HILPVzdO2/2pgiEPb5NMF0=";
  })
  (fetchNuGet {
    pname = "NuGet.Protocol";
    version = "6.3.3";
    hash = "sha256-xRW7RMwHqSvTUhSaSI5s2OTSUtcLvvi4dy3ncXIb9I4=";
  })
  (fetchNuGet {
    pname = "NuGet.Resolver";
    version = "6.3.1";
    hash = "sha256-NAvCKWepFnswh5Q8ecGXhfki7i2lDahDCit9v706mrE=";
  })
  (fetchNuGet {
    pname = "NuGet.Versioning";
    version = "6.3.1";
    hash = "sha256-wNM/C2Y+K+gjceaXD2nHuBkZZgshBMo9NQ9h9gz/RnQ=";
  })
  (fetchNuGet {
    pname = "NuGet.Versioning";
    version = "6.3.4";
    hash = "sha256-6CMYVQeGfXu+xner3T3mgl/iQfXiYixoHizmrNA6bvQ=";
  })
  (fetchNuGet {
    pname = "OTAPI.Upcoming";
    version = "3.1.20";
    hash = "sha256-ONMBrJG5hDmdkRQhyF0tHxd5M/NebsOkhQmnyfKVK0Y=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Collections";
    version = "4.3.0";
    hash = "sha256-4PGZqyWhZ6/HCTF2KddDsbmTTjxs2oW79YfkberDZS8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    hash = "sha256-PaiITTFI2FfPylTEk7DwzfKeiA/g/aooSU1pDcdwWLU=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.IO";
    version = "4.3.0";
    hash = "sha256-vej7ySRhyvM3pYh/ITMdC25ivSd0WLZAaIQbYj/6HVE=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection";
    version = "4.3.0";
    hash = "sha256-ns6f++lSA+bi1xXgmW1JkWFb2NaMD+w+YNTfMvyAiQk=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-Y2AnhOcJwJVYv7Rp6Jz6ma0fpITFqJW+8rsw106K2X8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-LkPXtiDQM3BcdYkAm5uSNOiz3uF4J45qpxn5aBiqNXQ=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-9EvnmZslLgLLhJ00o5MWaPuJQlbUFcUF8itGQNVkcQ4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    hash = "sha256-qwhNXBaJ1DtDkuRacgHwnZmOZ1u9q7N8j0cWOLYOELM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-PQRACwnSUuxgVySO1840KvqCC9F8iI9iTzxNW0RcBS4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-Kaw5PnLYIiqWbsoF3VKJhy7pkpoGsUwn4ZDCKscbbzA=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-Q18B9q26MkWZx68exUfQT30+0PGmpFlDgaF0TnaIGCs=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-agdOM0NXupfHbKAQzQT8XgbI9B8hVEh+a/2vqeHctg4=";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-LXUPLX3DJxsU1Pd3UwjO1PO9NM2elNEDXeu2Mu/vNps=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-qeSqaUI80+lqw5MK4vMpmO0CZaqrmYktwp6L+vQAb0I=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-SrHqT9wrCBsxILWtaJgGKd6Odmxm8/Mh7Kh0CUkZVzA=";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    hash = "sha256-ZBZaodnjvLXATWpXXakFgcy6P+gjhshFXmglrL5xD5Y=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-Jy01KhtcCl2wjMpZWH+X3fhHcVn+SyllWFY8zWlz/6I=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-wyv00gdlqf8ckxEdV7E+Ql9hJIoPcmYEuyeWb5Oz3mM=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-zi+b4sCFrA9QBiSGDD7xPV27r3iHGlV99gpyVUjRmc4=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-gybQU6mPgaWV3rBG2dbH6tT3tBq8mgze3PROdsuWnX0=";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-VsP72GVveWnGUvS/vjOQLv1U80H2K8nZ4fDAmI61Hm4=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-4yKGa/IrNCKuQ3zaDzILdNPD32bNdy6xr5gdJigyF5g=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-HmdJhhRsiVoOOCcUvAwdjpMRiyuSwdcgEv2j9hxi+Zc=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-pVFUKuPPIx0edQKjzRon3zKq8zhzHEzko/lc01V/jdw=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-ReoazscfbGH+R6s6jkg5sIEHWNEvjEoHtIsMbpc7+tI=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-c5tXWhE/fYbJVl9rXs0uHh3pTsg44YD1dJvyOA0WoMs=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-l8S9gt6dk3qYG6HYonHtdlYtBKyPb29uQ6NDjmrt3V4=";
  })
  (fetchNuGet {
    pname = "SharpZipLib";
    version = "1.4.2";
    hash = "sha256-/giVqikworG2XKqfN9uLyjUSXr35zBuZ2FX2r8X/WUY=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.bundle_e_sqlite3";
    version = "2.0.6";
    hash = "sha256-o6uXTtcxjb7H33I8UL4XLgx9y/f/iNeXx6z0NopR4MY=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.core";
    version = "2.0.6";
    hash = "sha256-MXi9UEga37dJyFuMg0AVt8enKdr54KlOFT/ssMHzkfA=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.lib.e_sqlite3";
    version = "2.0.6";
    hash = "sha256-o68At523MDwLEuRxjM+4EiydK4ITSFyc9R0zGmBGZ5g=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.provider.e_sqlite3";
    version = "2.0.6";
    hash = "sha256-308v2h3rvcPSsR9F+yFdJC1QEHgOQtuVxTMs5j3ODzI=";
  })
  (fetchNuGet {
    pname = "Steamworks.NET";
    version = "20.1.0";
    hash = "sha256-vt1UVbH4mHGPm7hTW2wKRrSzaFaHz9ZSuiaYeOhs6Ws=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.1";
    hash = "sha256-wws90sfi9M7kuCPWkv1CEYMJtCqx9QB/kj0ymlsNaxI=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.3.0";
    hash = "sha256-afY7VUtD6w/5mYqrce8kQrvDIfS2GXDINDh73IjxJKc=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "6.0.0";
    hash = "sha256-DKEbpFqXCIEfqp9p3ezqadn5b/S1YTk32/EQK+tEScs=";
  })
  (fetchNuGet {
    pname = "System.Collections.NonGeneric";
    version = "4.3.0";
    hash = "sha256-8/yZmD4jjvq7m68SPkJZLBQ79jOTOyT5lyzX4SCYAx8=";
  })
  (fetchNuGet {
    pname = "System.Collections.Specialized";
    version = "4.3.0";
    hash = "sha256-QNg0JJNx+zXMQ26MJRPzH7THdtqjrNtGLUgaR1SdvOk=";
  })
  (fetchNuGet {
    pname = "System.CommandLine";
    version = "2.0.0-beta4.22272.1";
    hash = "sha256-zSO+CYnMH8deBHDI9DHhCPj79Ce3GOzHCyH1/TiHxcc=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel";
    version = "4.3.0";
    hash = "sha256-i00uujMO4JEDIEPKLmdLY3QJ6vdSpw6Gh9oOzkFYBiU=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Primitives";
    version = "4.3.0";
    hash = "sha256-IOMJleuIBppmP4ECB3uftbdcgL7CCd56+oAD/Sqrbus=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.TypeConverter";
    version = "4.3.0";
    hash = "sha256-PSDiPYt8PgTdTUBz+GH6lHCaM1YgfObneHnZsc8Fz54=";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "4.4.1";
    hash = "sha256-4i8PUO1XTLfdUzeFxfHtR6xOP7mM3DD+ST9FviQl7zc=";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "6.0.0";
    hash = "sha256-fPV668Cfi+8pNWrvGAarF4fewdPVEDwlJWvJk0y+Cms=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-fkA79SjPbSeiEcrbbUsb70u9B7wqbsdM9s1LnoKj0gM=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "7.0.2";
    hash = "sha256-8Uawe7mWOQsDzMSAAP16nuGD1FRSajyS8q+cA++MJ8E=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.PerformanceCounter";
    version = "6.0.1";
    hash = "sha256-53t07yyRBb6sC4e3IjTp5fj44+p6JpX2zpr5/Bbf5Z4=";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "4.7.0";
    hash = "sha256-D3qG+xAe78lZHvlco9gHK2TEAM370k09c6+SQi873Hk=";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "6.0.0";
    hash = "sha256-/9EaAbEeOjELRSMZaImS1O8FmUe8j4WuFUw1VOrPyAo=";
  })
  (fetchNuGet {
    pname = "System.Formats.Asn1";
    version = "5.0.0";
    hash = "sha256-9nL3dN4w/dZ49W1pCkTjRqZm6Dh0mMVExNungcBHrKs=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    hash = "sha256-caL0pRmFSEsaoeZeWN5BTQtGrAtaQPwFi8YOZPZG5rI=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Extensions";
    version = "4.3.0";
    hash = "sha256-mmJWA27T0GRVuFP9/sj+4TrR4GJWrzNIk2PDrbr7RQk=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    hash = "sha256-ruynQHekFP5wPrDiVyhNiRIXeZ/I9NpjK5pU+HPDiRY=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.3.0";
    hash = "sha256-LMnfg8Vwavs9cMnq9nNH8IWtAtSfk0/Fy4s4Rt9r1kg=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "6.0.3";
    hash = "sha256-v+FOmjRRKlDtDW6+TfmyMiiki010YGVTa0EwXu9X7ck=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.3.0";
    hash = "sha256-R5uiSL3l6a3XrXSSL6jz+q/PcyVQzEAByiuXZNSqD/A=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    hash = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk=";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-fVfgcoP4AVN1E5wHZbKBIOPYZ/xBeSIdsNF+bdukIRM=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    hash = "sha256-NQSZRpZLvtPWDlvmMIdGxcVuyUnw92ZURo0hXsEshXY=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.7.0";
    hash = "sha256-GUnQeGo/DtvZVQpFnESGq7lJcjB30/KnDY7Kd2G/ElE=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.7.0";
    hash = "sha256-V0Wz/UUoNIHdTGS9e1TR89u58zJjo/wPUWw6VaVyclU=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-mMOCYzUenjd4rWIfq7zIX9PFYk/daUyF0A8l1hbydAk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "6.0.0";
    hash = "sha256-VJHXPjP05w6RE/Swu8wa2hilEWuji3g9bl/6lBMSC/Q=";
  })
  (fetchNuGet {
    pname = "System.Reflection.MetadataLoadContext";
    version = "6.0.0";
    hash = "sha256-82aeU8c4rnYPLL3ba1ho1fxfpYQt5qrSK5e6ES+OTsY=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-5ogwWB4vlQTl3jjk1xjniG2ozbFIjZTL9ug0usZQuBM=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.7.0";
    hash = "sha256-GEtCGXwtOnkYejSV+Tfl+DqyGq5jTUaVyL9eMupMHBM=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-idiOD93xbbrbwwSnD4mORA9RYi/D/U48eRUsn/WnWGo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    hash = "sha256-51813WXpBIsuA6fUtE5XaRQjcWdQ2/lmEokJt97u0Rg=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-wLDHmozr84v1W2zYCWYxxj0FR0JDYHSVRaRuDm0bd/o=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-KJ5aXoGpB56Y6+iepBkdpx/AfaJDAitx4vrkLqR7gms=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-8sDH+WUJfCR+7e4nfpftj/+lstEiZixWUBueR2zmHgI=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Loader";
    version = "4.3.0";
    hash = "sha256-syG1GTFjYbwX146BD/L7t55j+DZqpHDc6z28kdSNzx0=";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "4.7.0";
    hash = "sha256-/9ZCPIHLdhzq7OW4UKqTsR0O93jjHd6BRG1SRwgHE1g=";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "6.0.0";
    hash = "sha256-qOyWEBbNr3EjyS+etFG8/zMbuPjA+O+di717JP9Cxyg=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "5.0.0";
    hash = "sha256-nOJP3vdmQaYA07TI373OvZX6uWshETipvi5KpL7oExo=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Pkcs";
    version = "5.0.0";
    hash = "sha256-kq/tvYQSa24mKSvikFK2fKUAnexSL4PO4LkPppqtYkE=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "4.4.0";
    hash = "sha256-Ri53QmFX8I8UH0x4PikQ1ZA07ZSnBUXStd5rBfGWFOE=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "6.0.0";
    hash = "sha256-Wi9I9NbZlpQDXgS7Kl06RIFxY/9674S7hKiYw5EabRY=";
  })
  (fetchNuGet {
    pname = "System.Security.Permissions";
    version = "4.7.0";
    hash = "sha256-BGgXMLUi5rxVmmChjIhcXUxisJjvlNToXlyaIbUxw40=";
  })
  (fetchNuGet {
    pname = "System.Security.Permissions";
    version = "6.0.0";
    hash = "sha256-/MMvtFWGN/vOQfjXdOhet1gsnMgh6lh5DCHimVsnVEs=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.7.0";
    hash = "sha256-rWBM2U8Kq3rEdaa1MPZSYOOkbtMGgWyB8iPrpIqmpqg=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-GctHVGLZAa/rqkBNhsBGnsiWdKyv6VDubYpGkuOkBLg=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "4.4.0";
    hash = "sha256-zD24blG8xhAcL9gC4UTGKetd8c3LO0nv22nKTp2Vfx0=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "7.0.0";
    hash = "sha256-tF8qt9GZh/nPy0mEnj6nKLG4Lldpoi/D8xM5lv2CoYQ=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "7.0.1";
    hash = "sha256-wtk7fK3c/zAsaPB5oCmD86OfpPEJlGK3npr0mbM1ENM=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.3.0";
    hash = "sha256-ZDQ3dR4pzVwmaqBg4hacZaVenQ/3yAF/uV7BXZXjiWc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
  (fetchNuGet {
    pname = "System.Windows.Extensions";
    version = "4.7.0";
    hash = "sha256-yW+GvQranReaqPw5ZFv+mSjByQ5y1pRLl05JIEf3tYU=";
  })
  (fetchNuGet {
    pname = "System.Windows.Extensions";
    version = "6.0.0";
    hash = "sha256-N+qg1E6FDJ9A9L50wmVt3xPQV8ZxlG1xeXgFuxO+yfM=";
  })
  (fetchNuGet {
    pname = "ZstdSharp.Port";
    version = "0.7.1";
    hash = "sha256-VzvKkpVjR7yKQyXhf6Ljf9ikMAQkbPWUiGFOeluanS4=";
  })
]
