# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "evolution-3.22.0";

  src = fetchurl {
    url = mirror://gnome/sources/evolution/3.22/evolution-3.22.0.tar.xz;
    sha256 = "3e4742032b450cd8752097ba7e56302134e3653d510d4c53196654fb353ebbeb";
  };
}
