include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_cdsa_client

security_cdsa_client_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_cdsa_client_HEADER_FILES_DIR = lib

security_cdsa_client_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
