[ #./hardware/network/intel-3945abg.nix
  ../etc/default.nix
  ./config/fonts.nix
  ./config/i18n.nix
  ./config/system-path.nix
  ./config/unix-odbc-drivers.nix
  ./config/users-groups.nix
  ./installer/grub/grub.nix
  ./security/setuid-wrappers.nix
  ./security/sudo.nix
  ./services/audio/alsa.nix
  ./services/audio/pulseaudio.nix
  ./services/databases/mysql.nix
  ./services/databases/postgresql.nix
  ./services/hardware/acpid.nix
  ./services/hardware/hal.nix
  ./services/hardware/udev.nix
  ./services/logging/klogd.nix
  ./services/logging/syslogd.nix
  ./services/mail/dovecot.nix
  ./services/mail/postfix.nix
  ./services/misc/autofs.nix
  ./services/misc/disnix.nix
  ./services/misc/nix-daemon.nix
  ./services/misc/nixos-manual.nix
  ./services/misc/rogue.nix
  ./services/misc/synergy.nix
  ./services/monitoring/nagios/default.nix
  ./services/monitoring/zabbix-agent.nix
  ./services/monitoring/zabbix-server.nix
  ./services/network-filesystems/nfs-kernel.nix
  ./services/network-filesystems/samba.nix # TODO: doesn't start here (?)
  ./services/networking/avahi-daemon.nix
  ./services/networking/bind.nix
  ./services/networking/bitlbee.nix
  ./services/networking/dhclient.nix
  ./services/networking/dhcpd.nix
  ./services/networking/ejabberd.nix # untested, dosen't compile on x86_64-linux
  ./services/networking/gnunet.nix
  ./services/networking/gw6c.nix
  ./services/networking/ifplugd.nix
  ./services/networking/ircd-hybrid.nix # TODO: doesn't compile on x86_64-linux, can't test
  ./services/networking/ntpd.nix
  ./services/networking/openfire.nix
  ./services/networking/openvpn.nix
  ./services/networking/portmap.nix
  ./services/networking/ssh/lshd.nix # GNU lshd SSH2 deamon (TODO: does neither start nor generate seed file ?)
  ./services/networking/ssh/sshd.nix
  ./services/networking/vsftpd.nix
  ./services/printing/cupsd.nix
  ./services/scheduling/atd.nix
  ./services/scheduling/cron.nix
  ./services/scheduling/fcron.nix
  ./services/system/consolekit.nix
  ./services/system/dbus.nix
  ./services/system/nscd.nix
  ./services/ttys/gpm.nix
  ./services/ttys/mingetty.nix
  ./services/web-servers/apache-httpd
  ./services/web-servers/jboss.nix
  ./services/web-servers/tomcat.nix # untested, too lazy to get that jdk
  ./services/x11/xfs.nix
  ./services/x11/xserver/default.nix
  ./system/activation/activation-script.nix
  ./system/activation/top-level.nix
  ./system/boot/kernel.nix
  ./system/boot/stage-1.nix
  ./system/boot/stage-2.nix
  ./system/upstart-events/ctrl-alt-delete.nix
  ./system/upstart-events/halt.nix
  ./system/upstart-events/maintenance-shell.nix
  ../system/assertion.nix
  ../system/nixos-environment.nix
  ../system/nixos-installer.nix
  ../system/system-options.nix
  ../upstart-jobs/cron/locate.nix
  ../upstart-jobs/default.nix
  ../upstart-jobs/filesystems.nix
  ../upstart-jobs/guest-users.nix
  ../upstart-jobs/kbd.nix
  ../upstart-jobs/ldap
  ../upstart-jobs/lvm.nix
  ../upstart-jobs/network-interfaces.nix
  ../upstart-jobs/pcmcia.nix
  ../upstart-jobs/swap.nix
  ../upstart-jobs/swraid.nix
  ../upstart-jobs/tty-backgrounds.nix
]
