# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/coreos/go-systemd";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/go-systemd";
      rev = "9002847aa1425fb6ac49077c0a630b3b67e0fbfd";
      sha256 = "0d7xpcinzj18qc91rb6fjjrf9jnlzn775dqhp0n00n0gjg5rfksj";
    };
  }
  {
    goPackagePath = "github.com/satori/go.uuid";
    fetch = {
      type = "git";
      url = "https://github.com/satori/go.uuid";
      rev = "b2ce2384e17bbe0c6d34077efa39dbab3e09123b";
      sha256 = "1yz4cx02377ijlf8mnn84j1dcmlwh8ncx7y3kw1zg2qw0z4x119c";
    };
  }
  {
    goPackagePath = "github.com/urfave/cli";
    fetch = {
      type = "git";
      url = "https://github.com/urfave/cli";
      rev = "b67dcf995b6a7b7f14fad5fcb7cc5441b05e814b";
      sha256 = "0n5vq4nydlhb7w12jiwphvxqdy4jwpxc3zwlxyhf05lq1nxfb56h";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "927f97764cc334a6575f4b7a1584a147864d5723";
      sha256 = "0np7b766gb92vbm514yhdl7cjmqvn0dxdxskd84aas2ri1fkpgw5";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "d668ce993890a79bda886613ee587a69dd5da7a6";
      sha256 = "17m8d02fazil0dwvk33vpwvsb91asgbmmpqy05751csrfqhhdqna";
    };
  }
  # manually mirrored from launchpad because cloning failed due insecure http protocol
  {
    goPackagePath = "launchpad.net/go-xdg/v0";
    fetch = {
      type = "git";
      url = "https://github.com/Mic92/go-xdg";
      rev = "b3fc6b3106d78701853b0caf62ebedae42769af2";
      sha256 = "0fd68kkxzxjanpgannpys962bxzqdf8c1qvzk687hv504a3dp76f";
    };
  }
]
