#! /usr/bin/env bash

export SELF_HOME="$HOME/.local/share/self"
if [ -n "$XDG_DATA_HOME" ]
  then export SELF_HOME="$XDG_DATA_HOME/self"
fi

if [ ! -d $SELF_HOME ]; then
  mkdir -p $SELF_HOME
fi

if [ ! -d $SELF_HOME/objects ]; then
  mkdir -p $SELF_HOME/objects
  cp -r $SELF_ROOT/share/self/objects/* $SELF_HOME/objects
  chmod -R +w $SELF_HOME/objects
fi

exec $SELF_ROOT/bin/Self.wrapped "$@"
