# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "epiphany-3.22.0";

  src = fetchurl {
    url = mirror://gnome/sources/epiphany/3.22/epiphany-3.22.0.tar.xz;
    sha256 = "a645d17c10a1c266d4647306ea3e5496d3ca575d2ed8152947ed77e9eb623a27";
  };
}
