build:
  timeout: 10h
  tags:
  - nix
  script:
    - bash build.sh
    - bash xzar-install.sh
    - bash xzar.sh
  stage: build
  artifacts:
    paths:
      - nixpkgs.tar.xz

build_mac:
  timeout: 10h
  tags:
  - macos
  script:
    - bash xzar-install.sh
    - bash xzar.sh
  stage: build
