build:
  timeout: 10h
  tags:
    - ${RUNNER_TAG}
  script:
    - bash build.sh
    - bash xzar-install.sh
    - bash xzar.sh
  stage: build
  artifacts:
    paths:
      - nixpkgs.tar.xz
  parallel:
    matrix:
      - RUNNER_TAG: [macos, nix]

