build_x86_64-linux:
  timeout: 10h
  tags:
  - nix
  script:
    - bash build.sh
    - bash xzar-install.sh
    - bash xzar.sh
  stage: build
  artifacts:
    paths:
      - nixpkgs.tar.xz

build_aarch64-darwin:
  timeout: 10h
  tags:
  - macos
  script:
    - 'nix profile install nixpkgs#gnutar'
    - bash build.sh
    - bash xzar-install.sh
    - bash xzar.sh
  stage: build
  artifacts:
    paths:
      - nixpkgs.tar.xz
