#! /bin/sh

nix init

root=/home/eelco/Dev/nix/test

cd $root/tmpl

if ! nix-instantiate $root/descr $root/tmpl/*.nix; then
    exit 1;
fi

for i in $root/dist/*; do nix regfile $i; done
for i in $root/descr/*; do 
    md5sum $i
    nix regfile $i
done

