#! /bin/sh

mkdir -p $NIX/db
mkdir -p $NIX/pkg
mkdir -p $NIX/descr
mkdir -p $NIX/netcache

nix init

if ! nix-instantiate $NIX/descr $NIX/netcache tmpl/*.nix; then
    exit 1;
fi

for i in $NIX/netcache/*; do nix regfile $i; done
for i in build/*; do nix regfile $i; done
for i in $NIX/descr/*; do 
    md5sum $i
    nix regfile $i
done
