# This file has been autogenerated with cabal2nix.
# Update via ./update.sh
{
  mkDerivation,
  ansi-terminal,
  ansi-wl-pprint,
  base,
  base64-bytestring,
  binary,
  bytestring,
  containers,
  directory,
  edit-distance,
  fetchgit,
  filelock,
  filepath,
  ghc-prim,
  haskeline,
  hspec,
  hspec-discover,
  indexed-traversable,
  lib,
  mtl,
  prettyprint-avh4,
  process,
  raw-strings-qq,
  scientific,
  text,
  time,
  utf8-string,
  vector,
}:
mkDerivation {
  pname = "gren";
  version = "0.4.5";
  src = fetchgit {
    url = "https://github.com/gren-lang/compiler.git";
    sha256 = "0hbxzn14m9y7sqwk347yj7hblwmj5fyzmy7kjqc8zjd63gmrkdh8";
    rev = "0efe25e3f48663a36eec525d2df0d957f53c9b4e";
    fetchSubmodules = true;
  };
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    ansi-terminal
    ansi-wl-pprint
    base
    base64-bytestring
    binary
    bytestring
    containers
    directory
    edit-distance
    filelock
    filepath
    ghc-prim
    haskeline
    indexed-traversable
    mtl
    prettyprint-avh4
    process
    raw-strings-qq
    scientific
    text
    time
    utf8-string
    vector
  ];
  testHaskellDepends = [
    ansi-terminal
    ansi-wl-pprint
    base
    base64-bytestring
    binary
    bytestring
    containers
    directory
    edit-distance
    filelock
    filepath
    ghc-prim
    haskeline
    hspec
    indexed-traversable
    mtl
    prettyprint-avh4
    process
    raw-strings-qq
    scientific
    text
    time
    utf8-string
    vector
  ];
  testToolDepends = [ hspec-discover ];
  jailbreak = true;
  homepage = "https://gren-lang.org";
  description = "The `gren` command line interface";
  license = lib.licenses.bsd3;
  mainProgram = "gren";
}
