include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_keychain

security_keychain_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_keychain_HEADER_FILES_DIR = lib

security_keychain_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
