include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_pkcs12

security_pkcs12_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_pkcs12_HEADER_FILES_DIR = lib

security_pkcs12_CC_FILES = $(wildcard lib/*.cpp)
security_pkcs12_C_FILES = $(wildcard lib/*.c)

include $(GNUSTEP_MAKEFILES)/library.make
