diff --git a/Makefile b/Makefile
index af7a206..553ac70 100644
--- a/Makefile
+++ b/Makefile
@@ -47,7 +47,7 @@ ifeq ($(PREFIX),/usr)
 	INITRAMFS_DIR=$(PREFIX)/share/initramfs-tools
 else
 	ROOT_SBINDIR=$(PREFIX)/sbin
-	INITRAMFS_DIR=/etc/initramfs-tools
+	INITRAMFS_DIR=$(PREFIX)/etc/initramfs-tools
 endif
 
 .PHONY: all
