#!/bin/sh

buildcpath() {
  local language=$1 path after
  shift
  while (( $# )); do
    case $language:$1 in
        *:-isystem|c++:-cxx-isystem)
            shift
            path=$path${path:+':'}$1
            ;;
        *:-idirafter)
            shift
            after=$after${after:+':'}$1
            ;;
    esac
    shift
  done
  echo $path${after:+':'}$after
}

export CPATH=${CPATH}${CPATH:+':'}$(buildcpath c ${NIX_CFLAGS_COMPILE} \
                                               $(<@libcFlags@)):@clang@/resource-root/include
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}${CPLUS_INCLUDE_PATH:+':'}$(buildcpath c++ ${NIX_CFLAGS_COMPILE} \
                                                                                      $(<@cxxFlags@) \
                                                                                      $(<@libcFlags@)):@clang@/resource-root/include
exec -a "$0" @out@/bin/.$(basename $0)-unwrapped "$@"
