#!/bin/env bash

# Adapt from get_vsixpkg() of the original update_install_exts.sh

set -eu -o pipefail

# Helper to just fail with a message and non-zero exit code.
function fail() {
    echo "$1" >&2
    exit 1
}

PUBLISHER=""
NAME=""
VER=""

if [[ "$#" -eq 0 ]]; then
fail "Expect PUBLISHER and NAME"
fi

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -h|--help)
            cat <<END_HELP
Usage: nix-prefetch-vscode-mktplc [OPTIONS] PUBLISHER NAME VERSION=latest

Fetch the vscode extension from the official marketplace
and print the mktplcRef attributes in JSON format

Options:
  -h, --help    Print this help and exit
END_HELP

            exit 0
            ;;
        *)
            if [[ $# -lt 2 ]]; then
                fail "Expect PUBLISHER and NAME"
            fi
            PUBLISHER="$1"
            NAME="$2"
            if [[ "$#" -lt 3 ]] || [[ -z "$3" ]]; then
                VER="latest"
            else
                VER="$3"
            fi
            if [[ "$#" -eq 2 ]]; then
                shift 2
            else
                shift 3
            fi
            ;;
    esac
done

N="$PUBLISHER.$NAME"

# Create a tempdir for the extension download.
EXTTMP=$(mktemp -d -t vscode_exts_XXXXXXXX)

# Clean up the temp folder whenever exit
function clean_up {
    rm -rf "$EXTTMP"
}

trap clean_up EXIT

URL="https://$PUBLISHER.gallery.vsassets.io/_apis/public/gallery/publisher/$PUBLISHER/extension/$NAME/$VER/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"

# Quietly but delicately curl down the file, blowing up at the first sign of trouble.
curl --silent --show-error --fail -o "$EXTTMP/$N.zip" "$URL"
# Unpack the file we need to stdout then pull out the version
VER_FETCHED="$(unzip -qc "$EXTTMP/$N.zip" "extension/package.json" | jq -r '.version')"
if [[ "$VER" = "latest" ]]; then
    VER="$VER_FETCHED"
else
    if [[ "$VER" != "$VER_FETCHED" ]]; then
    fail "Fetched version ($VER_FETCHED) does not match the specified version ($VER)"
    fi
fi
# Calculate the SHA
SHA="$(nix-hash --flat --base32 --type sha256 "$EXTTMP/$N.zip")"

cat <<-EOF
{
  "name": "$NAME",
  "publisher": "$PUBLISHER",
  "version": "$VER",
  "useMSMktplc": true,
  "sha256": "$SHA"
}
EOF
