# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, parsec }:

cabal.mkDerivation (self: {
  pname = "multipart";
  version = "0.1.2";
  sha256 = "0g04jhyw1ib1s7c9bcldyyn4n90qd9x7dmvic4vgq57bgcqgnhz5";
  buildDepends = [ parsec ];
  meta = {
    homepage = "http://www.github.com/silkapp/multipart";
    description = "HTTP multipart split out of the cgi package";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ aycanirican ];
  };
})
