{ stdenv, pkgs, lib, maven }:

with pkgs.javaPackages;

let
  fetchMaven = pkgs.callPackage ./m2install.nix { };
  poms = import ./poms.nix { inherit fetchMaven; };
  plugins = import ./mavenPlugins.nix { inherit stdenv lib pkgs maven; };
in rec {
# "Minimal"
  mavenMinimal = lib.flatten
    (with plugins; [
    classworlds_1_1
    commonsCli_1_0
    findbugsJsr305_2_0_1
    junit_3_8_1
    mavenArchiver_2_5
    mavenArtifact_2_0_6
    mavenArtifact_2_0_9
    mavenArtifactManager_2_0_6
    mavenArtifactManager_2_0_9
    mavenArtifactManager_2_2_1
    mavenClean_2_5
    mavenCompiler_3_1
    mavenCore_2_0_6
    mavenCore_2_0_9
    mavenCore_2_2_1
    mavenDoxiaSinkApi_1_0_alpha7
    mavenErrorDiagnostics_2_0_6
    mavenErrorDiagnostics_2_0_9
    mavenErrorDiagnostics_2_2_1
    mavenFiltering_1_1
    mavenInstall_2_4
    mavenJar_2_4
    mavenModel_2_0_6
    mavenModel_2_0_9
    mavenModel_2_2_1
    mavenMonitor_2_0_6
    mavenMonitor_2_0_9
    mavenMonitor_2_2_1
    mavenPluginDescriptor_2_0_6
    mavenPluginDescriptor_2_0_9
    mavenPluginDescriptor_2_2_1
    mavenPluginParameterDocumenter_2_0_6
    mavenPluginParameterDocumenter_2_0_9
    mavenPluginParameterDocumenter_2_2_1
    mavenProfile_2_0_6
    mavenProfile_2_0_9
    mavenProfile_2_2_1
    mavenProject_2_0_6
    mavenProject_2_0_9
    mavenPluginAnnotations_3_1
    mavenPluginApi_2_0_6
    mavenPluginApi_2_0_9
    mavenPluginApi_2_2_1
    mavenPluginRegistry_2_0_6
    mavenPluginRegistry_2_0_9
    mavenPluginRegistry_2_2_1
    mavenReportingApi_2_0_6
    mavenReportingApi_2_0_9
    mavenRepositoryMetadata_2_0_6
    mavenRepositoryMetadata_2_0_9
    mavenRepositoryMetadata_2_2_1
    mavenResources_2_6
    mavenSettings_2_0_6
    mavenSettings_2_0_9
    mavenSettings_2_2_1
    mavenSharedIncremental_1_1
    mavenSharedUtils_0_1
    mavenSurefire_2_12_4
    mavenSurefireApi_2_12_4
    mavenSurefireBooter_2_12_4
    mavenSurefireCommon_2_12_4
    mavenToolchain_1_0
    mavenToolchain_2_0_9
    plexusBuildApi_0_0_4
    plexusCompilerApi_2_2
    plexusContainerDefault_1_0_alpha9_stable1
    plexusInteractivityApi_1_0_alpha4
    plexusInterpolation_1_13
    plexusUtils_1_5_1
    plexusUtils_2_0_5
    plexusUtils_3_0
    ])
    ++
    (with
    poms;
    [
    apache_3
    apache_4
    apache_5
    apache_6
    apache_9
    apache_10
    apache_11
    apache_13
    doxia_1_0_alpha7
    maven_2_0_6
    maven_2_0_9
    maven_2_2_1
    mavenParent_5
    mavenParent_8
    mavenParent_11
    mavenParent_13
    mavenParent_21
    mavenParent_22
    mavenParent_23
    mavenPlugins_22
    mavenPlugins_23
    mavenPlugins_24
    mavenPluginTools_3_1
    mavenReporting_2_0_6
    mavenReporting_2_0_9
    mavenSharedComponents_12
    mavenSharedComponents_17
    mavenSharedComponents_18
    mavenSharedComponents_19
    plexus_1_0_4
    plexus_1_0_11
    plexus_2_0_3
    plexus_2_0_6
    plexus_2_0_7
    plexus_3_3_1
    plexusCompiler_2_2
    plexusComponents_1_1_15
    plexusComponents_1_3_1
    plexusComponentAnnotations_1_5_5
    plexusContainers_1_0_3
    plexusContainers_1_5_5
    sonatypeForgeParent_3
    sonatypeForgeParent_5
    sonatypeForgeParent_10
    sonatypeSpiceParent_10
    sonatypeSpiceParent_16
    sonatypeSpiceParent_17
    surefire_2_12_4
    ]);
}
