# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "tributary-0.4.1-tqCfW5jFAAASNG4kHOmwHkahf3XM4m2FEU1qeRB8CvCZ";
    path = fetchzip {
      url = "https://codeberg.org/Sivecano/libtributary/archive/0.4.1.tar.gz";
      hash = "sha256-SAPzjnCB/BBEc/ZyujrVZG2BAgVrYcFx2ELiPZ4lgsU=";
    };
  }
  {
    name = "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.6.0.tar.gz";
      hash = "sha256-3m/ITNhZUJ/5uD/Tqm+0uZSktGoYgWF5oldOqOCUkIE=";
    };
  }
]
