diff --git a/Makefile b/Makefile
index 005d60d..f69c7fe 100644
--- a/Makefile
+++ b/Makefile
@@ -41,6 +41,7 @@ install:
 	install -d -v                      $(DESTDIR)/bin/
 	install -d -v                      $(DESTDIR)/share/doc/ebook2cw/
 	install -d -v                      $(DESTDIR)/share/doc/ebook2cw/examples/
+	install -d -v                      $(DESTDIR)/share/locale/de/LC_MESSAGES/
 	install -s -m 0755 ebook2cw        $(DESTDIR)/bin/
 	install    -m 0644 ebook2cw.1      $(DESTDIR)/share/man/man1/
 	install    -m 0644 README          $(DESTDIR)/share/doc/ebook2cw/
