# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "machine-${version}";
  version = "0.12.2";

  goPackagePath = "github.com/docker/machine";

  src = fetchFromGitHub {
    rev = "v${version}";
    owner = "docker";
    repo = "machine";
    sha256 = "0ikgjb6x6h7f43vjabxnqgrrlq516zsz7vj945hca1w919jpdwhf";
  };

  postInstall = ''
    mkdir -p $bin/share/bash-completion/completions/
    cp go/src/github.com/docker/machine/contrib/completion/bash/* $bin/share/bash-completion/completions/
  '';

  postFixup =  ''
    mv $bin/bin/cmd $bin/bin/docker-machine
  '';

  meta = with stdenv.lib; {
    homepage = https://docs.docker.com/machine/;
    description = "Docker Machine is a tool that lets you install Docker Engine on virtual hosts, and manage Docker Engine on the hosts.";
    license = licenses.asl20;
    maintainers = with maintainers; [ offline tailhook ];
    platforms = platforms.unix;
  };
}
