diff -rc openal-0.0.8-orig/configure.ac openal-0.0.8-new/configure.ac
*** openal-0.0.8-orig/configure.ac	2005-12-15 16:58:45.000000000 +0100
--- openal-0.0.8-new/configure.ac	2006-01-26 14:28:47.000000000 +0100
***************
*** 530,535 ****
--- 530,537 ----
    fi
  fi
  
+ AM_CONDITIONAL([ARTSENABLED], [test -n "$HAVEARTS"])
+ 
  # enable esd sound?
  AC_ARG_ENABLE([esd],
  [AS_HELP_STRING([--enable-esd],
***************
*** 558,563 ****
--- 560,567 ----
    fi
  fi
  
+ AM_CONDITIONAL([ESDENABLED], [test -n "$HAVEESD"])
+ 
  # enable wave output?
  AC_ARG_ENABLE([waveout],
  [AS_HELP_STRING([--enable-waveout],
***************
*** 614,619 ****
--- 618,625 ----
    esac
  fi
  
+ AM_CONDITIONAL([SDLENABLED], [test -n "$HAVESDL"])
+ 
  # enable directsound backend?
  AC_ARG_ENABLE([dsound],
  [AS_HELP_STRING([--enable-dsound],
diff -rc openal-0.0.8-orig/src/Makefile.am openal-0.0.8-new/src/Makefile.am
*** openal-0.0.8-orig/src/Makefile.am	2005-12-04 19:16:21.000000000 +0100
--- openal-0.0.8-new/src/Makefile.am	2006-01-26 14:28:56.000000000 +0100
***************
*** 61,79 ****
  	arch/alsa/alsa.h
  endif
  
  libopenal_la_SOURCES +=			\
  	arch/interface/interface_sound.c \
  	arch/interface/interface_sound.h \
  	arch/interface/platform.h	\
  	arch/portable/cpu_caps.c	\
- 	arch/arts/arts.c		\
- 	arch/arts/arts.h		\
- 	arch/esd/esd.c			\
- 	arch/esd/esd.h			\
  	arch/null/null.c		\
  	arch/null/null.h		\
- 	arch/sdl/sdl.c			\
- 	arch/sdl/sdl.h			\
  	arch/waveout/waveout.c		\
  	arch/waveout/waveout.h
  
--- 61,91 ----
  	arch/alsa/alsa.h
  endif
  
+ if SDLENABLED
+ libopenal_la_SOURCES +=			\
+ 	arch/sdl/sdl.c			\
+ 	arch/sdl/sdl.h
+ endif
+ 
+ if ESDENABLED
+ libopenal_la_SOURCES +=			\
+ 	arch/esd/esd.c			\
+ 	arch/esd/esd.h
+ endif
+ 
+ if ARTSENABLED
+ libopenal_la_SOURCES +=			\
+ 	arch/arts/arts.c		\
+ 	arch/arts/arts.h
+ endif
+ 
  libopenal_la_SOURCES +=			\
  	arch/interface/interface_sound.c \
  	arch/interface/interface_sound.h \
  	arch/interface/platform.h	\
  	arch/portable/cpu_caps.c	\
  	arch/null/null.c		\
  	arch/null/null.h		\
  	arch/waveout/waveout.c		\
  	arch/waveout/waveout.h
  
