#!/usr/bin/env bash
set -e

OUT_DIR="${1-result}"
mkdir -p "$OUT_DIR"

URL_BASE="${2-https://f005.backblazeb2.com/file/nixbsd}"
SELF_DIRNAME="$(dirname $(realpath $0))"
export NIX_PATH="$SELF_DIRNAME/../../../.."
TMPCFG="$(mktemp)"
NIX_BUILD=${NIX_BUILD-nix-build}
if git -C $NIX_PATH/nixpkgs diff-index --quiet HEAD; then
    TAG=$(git -C $NIX_PATH/nixpkgs rev-parse HEAD)
else
    TAG="(dirty)"
fi
PLATFORM=$(nix-instantiate --eval --expr builtins.currentSystem | cut -d '"' -f 2)

echo "    # These bootstrap hashes generated by compiling from nixpkgs $TAG on $PLATFORM" >$TMPCFG

for PLATFORM in x86_64-freebsd14; do
    echo "    ${PLATFORM} = {"
    for PROGRAM in bash mkdir tar unxz chmod bootstrapFiles; do
        STORE_PATH="$($NIX_BUILD -K --no-out-link --argstr system ${PLATFORM} ${SELF_DIRNAME}/bootstrap-files/${PROGRAM}.nix --show-trace)"
        BASENAME="$(basename $STORE_PATH)"
        if [[ "$PROGRAM" = "bootstrapFiles" ]]; then
            HASH="$(nix-hash --type sha256 --to-sri $(sha256sum $STORE_PATH | awk '{ print $1 }'))"
        else
            HASH="$(nix-hash --type sha256 --sri $STORE_PATH)"
        fi
        cp "${STORE_PATH}" "${OUT_DIR}/${BASENAME}"
        chmod u+w "${OUT_DIR}/${BASENAME}"
        echo "      ${PROGRAM} = {"
        echo "        url = \"${URL_BASE}/${BASENAME}\";"
        echo "        hash = \"$HASH\";"
        if [[ "$PROGRAM" = "bootstrapFiles" ]]; then
            echo '        name = "bootstrap-files.tar.xz";'
            echo '        executable = false;'
        fi
        echo "      };"
    done
    echo "    };"
done >>$TMPCFG

echo 'Done! Please copy the following into nixpkgs/pkgs/stdenv/freebsd/default.nix:'
cat $TMPCFG
rm -f $TMPCFG
