diff --git a/software/Makefile.linux b/software/Makefile.linux
index db48aa5..df8b3d2 100644
--- a/software/Makefile.linux
+++ b/software/Makefile.linux
@@ -1,6 +1,6 @@
-GIT_VERSION := $(shell git --no-pager describe --tags --always)
-GIT_COMMIT  := $(shell git rev-parse --verify HEAD)
-GIT_DATE    := $(firstword $(shell git --no-pager show --date=iso-strict --format="%ad" --name-only))
+GIT_VERSION ?= $(shell git --no-pager describe --tags --always)
+GIT_COMMIT  ?= $(shell git rev-parse --verify HEAD)
+GIT_DATE    ?= $(firstword $(shell git --no-pager show --date=iso-strict --format="%ad" --name-only))
 
 PREFIX = $(DESTDIR)/usr/local
 
