# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, blazeBuilder, caseInsensitive, dataDefault, hspec2
, hspecWai, httpTypes, liftedBase, monadControl, mtl, regexCompat
, text, transformers, transformersBase, wai, waiExtra, warp
}:

cabal.mkDerivation (self: {
  pname = "scotty";
  version = "0.9.0";
  sha256 = "0gx00k5w4cs68bh3ciplkwhzh2412y6wqg0qdsslnnsb41l5kb1d";
  buildDepends = [
    aeson blazeBuilder caseInsensitive dataDefault httpTypes
    monadControl mtl regexCompat text transformers transformersBase wai
    waiExtra warp
  ];
  testDepends = [ hspec2 hspecWai httpTypes liftedBase text wai ];
  jailbreak = true;
  doCheck = false;
  meta = {
    homepage = "https://github.com/scotty-web/scotty";
    description = "Haskell web framework inspired by Ruby's Sinatra, using WAI and Warp";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
