#! /bin/sh -e

src=$(realpath $1)
out=$(realpath $2)

echo "Fetching $src to $out"

mkdir $out
export HOME=$out
cd $src
cargo fetch --verbose

# TODO: check that Cargo.lock exists, and hasn't changed
# TODO: this should be done by cargo itself

# Make it deterministic
find $out -name .git | xargs -I {} rm -rf {}/logs {}/index {}/hooks
# The checkout contain the path of the output himself, which is not allowed
#rm -rf $out/.cargo/git/checkouts
find $out -name .git | xargs -I {} sed "s|file://$out/.cargo/git|..|g" -i {}/config
