diff --git a/app/Makefile b/app/Makefile
index 5078b9a..99b208a 100644
--- a/app/Makefile
+++ b/app/Makefile
@@ -46,29 +46,10 @@ APP = pktgen
 CFLAGS += -O3 -g $(WERROR_FLAGS) -fno-stack-protector
 CFLAGS += -I$(RTE_SRCDIR) -I$(RTE_SRCDIR)/../lib/common
 
-dpdk_ver := $(RTE_SDK)/xusertools/dpdk-version.sh
-pktgen_ver := $(RTE_SRCDIR)/../tools/dpdk-version.sh
-ver_cmd := $(if $(wildcard $(dpdk_ver)),$(dpdk_ver),$(pktgen_ver))
-# $(info ver_cmd=$(ver_cmd))
-
-yy := $(shell $(ver_cmd) -yy)
-# mm := $(shell $(ver_cmd) -mm)
-
-# $(info yy=$(yy))
-
-ifeq ($(yy),17)
 COMMON_PRE := $(RTE_SRCDIR)/../lib/common
 LUA_PRE := $(RTE_SRCDIR)/../lib/lua/src
 CLI_PRE := $(RTE_SRCDIR)/../lib/cli
 GUI_PRE := $(RTE_SRCDIR)/../gui/gui
-else
-ifeq ($(yy),16)
-COMMON_PRE := $(RTE_SRCDIR)/../lib/common/lib/common
-LUA_PRE := $(RTE_SRCDIR)/../lib/lua/src/lib/lua/src
-CLI_PRE := $(RTE_SRCDIR)/../lib/cli/lib/cli
-GUI_PRE := $(RTE_SRCDIR)/../gui
-endif
-endif
 
 COMMON_LIB := $(COMMON_PRE)/$(RTE_TARGET)
 LUA_LIB    := $(LUA_PRE)/$(RTE_TARGET)
