diff -Naur ncompress-4.2.4.2.orig/Makefile.def ncompress-4.2.4.2/Makefile.def
--- ncompress-4.2.4.2.orig/Makefile.def	2007-09-06 22:28:42.000000000 -0500
+++ ncompress-4.2.4.2/Makefile.def	2009-08-18 12:30:53.000000000 -0500
@@ -3,14 +3,16 @@
 # C complier
 #CC=cc
 
+PREFIX=/usr/local
+
 # Install prefix
 DESTDIR=
 
 # Install directory for binarys
-BINDIR=/usr/local/bin
+BINDIR=$(PREFIX)/bin
 
 # Install directory for manual
-MANDIR=/usr/local/man/man1
+MANDIR=$(PREFIX)/man/man1
 
 # compiler options:
 # options is a collection of:
@@ -31,7 +33,7 @@
 #	-DDEF_ERRNO=1				Define error (not defined in errno.h).
 #	-DMAXSEG_64K=1 -BITS=16		Support segment processsor like 80286.
 #
-options= $(CFLAGS) $(CPPFLAGS) -DDIRENT=1 -DUSERMEM=800000 -DREGISTERS=3
+options= $(CFLAGS) $(CPPFLAGS) -DDIRENT=1 -DUSERMEM=800000 -DREGISTERS=3 -DNOFUNCDEF=1
 
 # libary options
 LBOPT= $(LDFLAGS)
