# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  # Makko
  {
    name = "N-V-__8AADOnqgUlgd1Wb1ddIDiG1EHw03m7SlLXNpLWgejt";
    path = fetchzip {
      url = "https://code.hexops.org/hexops/xcode-frameworks/archive/d9de76b40c979eb425aad0e365fe57b676b5d6f6.zip";
      hash = "sha256-4nX0J+2oWqDFua8LOzfQ9S3lHlRJ8TBkHmQexVALu6s=";
    };
  }
  {
    name = "args-0.0.0-CiLiqvvfAAAM3smSSA0GGjCI483ftWnhZ_FFo4WjNELF";
    path = fetchgit {
      url = "https://github.com/ikskuh/zig-args";
      rev = "cef615b6762990466d88db126f762f1cabe327e8";
      hash = "sha256-zrZIKVbyYFKrtrCMYTJ0MXxL7r5LAO1oWbdutjTRqXE=";
    };
  }
  {
    name = "qrcode-1.0.0-864BaRGZAADk4dFMZAmFszqcdpRe5vEy4_rRFtte3d3t";
    path = fetchgit {
      url = "https://github.com/darltrash/QRCode.zig";
      rev = "559756c3c4119bd18406f7d9f19b6cb0f54620b2";
      hash = "sha256-IROU9nCVf2is+xXQFGV2jDX1vAuvXkM6OnEcelSLCX0=";
    };
  }
  {
    name = "zdt-0.8.1-xr0_vAxUDwCJRDh9pcAS_mdZBIsvcGTtN-K8JJSWY4I6";
    path = fetchgit {
      url = "https://codeberg.org/FObersteiner/zdt";
      rev = "d93e67e3032029eeee772a28ef7d4557a06cdb70";
      hash = "sha256-YH/zfe5T/e2ZQ/oEhYJpRlyrkYVY/qPF/kf9Zt6w/ow=";
    };
  }
  {
    name = "zigmon-0.0.1-Qy5Zt14UAQDTYIxc8dtS7B3AilX9B1ja11nweP_eeN5l";
    path = fetchgit {
      url = "https://github.com/OsakiTsukiko/zigmon";
      rev = "f1841bfeeb1bf657ff89b9a750184a68742fd6aa";
      hash = "sha256-p3eXGe5ZxRJdi+sLPflUhT9sG9jILyBqXC0alxZJAOE=";
    };
  }

  # md4zig
  {
    name = "N-V-__8AABg2EADw60l3NWKs8RaAXr8TwCv5PRejslRuv3XD";
    path = fetchgit {
      url = "https://github.com/fjebaker/md4c-zig";
      rev = "07ee4687ae0081c565ded4c8ba3d5e13981f9c57";
      hash = "sha256-WMhsfOnCWan5+70lawuxDfwjP97hjFH4nhsYO/+04qc=";
    };
  }
]
