# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version = "10.0.1";
      src = {
        rev = "65c045085a7c2da92e839d00ed14d3f2a447654c";
        sha256 = "1mnlv8fyz03pfg8pkqwdl5gjz6vsk98c6414lf3wkvrkb85ljaav";
      };
    };
    libVersion = {
      version = "10.0.1";
      libSources = {
        symbols.rev = "49f3091e7fea8d9b935635f3328cbf07b7548625";
        symbols.sha256 = "0iz4lb33wdsw4f82a0ln8ycgaf39gjws03mvl2j1q9npwj6xl1cm";
        templates.rev = "66727540677590f988f8448fd3b632d3f26cc1b4";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "ab2f97eaa2ab7769ec3ad0487ff9bcafabe8641a";
        footprints.sha256 = "0jqgyi1yb2zc6w56ba7xama0wnhrqwbbnf2fqvr47xihvdcvs87v";
        packages3d.rev = "efef8c6631221341db2549c52b921e33dd05bbb4";
        packages3d.sha256 = "0jr70ry6inzc2fy3s300z0zlmihbq95ba1zckyd1wwbpplaj1gbl";
      };
    };
  };
  "kicad-testing" = {
    kicadVersion = {
      version = "10.0-2026-04-06";
      src = {
        rev = "d9de30af310c4fd84257b48ae6808ef5e3cfe70f";
        sha256 = "0bxiyhvpncmrakfmx6kdx7jdlssbm90v5li3km558yas5pkzppgx";
      };
    };
    libVersion = {
      version = "10.0-2026-04-06";
      libSources = {
        symbols.rev = "dc72a484664c0470407113a174f2b5435debbcaf";
        symbols.sha256 = "0khfnln0f2zsz5hy31nw2rr0nflb2z3s9n9f7g41g03m9l3s43v2";
        templates.rev = "e703d1e2ab3eb98a209ff402d2b6bf6d02dc1930";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "4899503b69ff037ed102ab0fe5a0564ef3d61726";
        footprints.sha256 = "0ymmd1rzrczpvcqzw1mld9x8xhbka0vvjy3kdqwysg4ri97f5wrm";
        packages3d.rev = "bc82151111e9edddf4295228e6ceb5e0584c9c3e";
        packages3d.sha256 = "0k91iw661fpzb7saryjxdcdvk1kis7dhbcpzp7xzjk84i4jvxrp5";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version = "2025-02-21";
      src = {
        rev = "878cf768d6552131494aa792dc20e6ccf67baf75";
        sha256 = "0ky0a7y6gf409y8bwpngiirqin4ivbcjnk8gjdj1a6w79x559sr8";
      };
    };
    libVersion = {
      version = "2025-02-21";
      libSources = {
        symbols.rev = "da86acd48809fd61876223c8bf0e4e7793c52e9a";
        symbols.sha256 = "1sdpg58wbyyrghjd0jqw5iw2094mjy2v9jmwn5zrj4jm6f51g1kd";
        templates.rev = "3ed4538b0f965d821df63a5fffc4441e723cfe7f";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "e515f1c3213317d436e492c8c06620ef4caca84e";
        footprints.sha256 = "16zslgvjg4swgkkvnd9fmiks3wzg63364d03hixiyzcpjlgk2bbk";
        packages3d.rev = "d5db5cea003fe2b4b1c9b145f5fcbd5fdb48f8ca";
        packages3d.sha256 = "0bg54lg1iw01gw06ajg34y7x4y36wm6ls3jnpjy13i18d4ik77g4";
      };
    };
  };
}
