# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version = "10.0.3";
      src = {
        rev = "1d69e55fc60915f8f1569c9f6522d9b0fb5a0ba8";
        sha256 = "0ldaj072x16452xw2wszbk20g932rz36zappjrxc4m6ygx298aa3";
      };
    };
    libVersion = {
      version = "10.0.3";
      libSources = {
        symbols.rev = "299c330ab364cfc3989d1ab6e82f1eabb9ddd915";
        symbols.sha256 = "05h8dbygch2kp4s5ikspxngwv999j7jwsiwm4pzwwcrir7dqzdfl";
        templates.rev = "a7e1a3ae6255d8d9aaff13e58adf3a0d78cb90c9";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "fe0ca39d34a10036f2b6ccb9749a39bc3fa7af95";
        footprints.sha256 = "0wdzsn7z11wc5yskk576a4a6qfagsvw0y6r034inxrnfc32aiah9";
        packages3d.rev = "c955b94c7bdeffd94b06bac86d94588a9be03afe";
        packages3d.sha256 = "01nbjcs3890hyfmafc623ldmfi9n8sjr5m0wripz5fq5fjdnzqxl";
      };
    };
  };
  "kicad-testing" = {
    kicadVersion = {
      version = "10.0-2026-05-30";
      src = {
        rev = "81d0ec2f35bd2ce905e006d38274a5ab37d6baa9";
        sha256 = "1ajnh1d8gpyyh53s766cr7n6x3h4z0hrlhmyi9dx86p4c6138qly";
      };
    };
    libVersion = {
      version = "10.0-2026-05-30";
      libSources = {
        symbols.rev = "299c330ab364cfc3989d1ab6e82f1eabb9ddd915";
        symbols.sha256 = "05h8dbygch2kp4s5ikspxngwv999j7jwsiwm4pzwwcrir7dqzdfl";
        templates.rev = "a7e1a3ae6255d8d9aaff13e58adf3a0d78cb90c9";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "fe0ca39d34a10036f2b6ccb9749a39bc3fa7af95";
        footprints.sha256 = "0wdzsn7z11wc5yskk576a4a6qfagsvw0y6r034inxrnfc32aiah9";
        packages3d.rev = "c955b94c7bdeffd94b06bac86d94588a9be03afe";
        packages3d.sha256 = "01nbjcs3890hyfmafc623ldmfi9n8sjr5m0wripz5fq5fjdnzqxl";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version = "2026-05-08";
      src = {
        rev = "76f8839fd232594f81180f644e3370c390025144";
        sha256 = "0nbr3cmrz1ca4rcwbfxvlrnwxy091lscgsqd92pqyy9sjcvqdfjg";
      };
    };
    libVersion = {
      version = "2026-05-08";
      libSources = {
        symbols.rev = "5a41d2112853c72129a9128df01021278c1aec11";
        symbols.sha256 = "05h8dbygch2kp4s5ikspxngwv999j7jwsiwm4pzwwcrir7dqzdfl";
        templates.rev = "3ed4538b0f965d821df63a5fffc4441e723cfe7f";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "098da23b916d287a0c7913752df53e6bfdf640a2";
        footprints.sha256 = "1h1v44qc5lvvqvmi1i7b79jhxsfq8snk0mcfl6r73hj6w0b25l84";
        packages3d.rev = "394aeaa41d7be7f717715d9ba004d7d0d8b74b36";
        packages3d.sha256 = "01nbjcs3890hyfmafc623ldmfi9n8sjr5m0wripz5fq5fjdnzqxl";
      };
    };
  };
}
