# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version = "9.0.6";
      src = {
        rev = "878335d000462f1498adc4267854bb594a21bd36";
        sha256 = "0mfnlx0dlpk3jz1b8pard6b7ax1ycyv069k4vg89ph2bia1a9d98";
      };
    };
    libVersion = {
      version = "9.0.6";
      libSources = {
        symbols.rev = "e92aabf81dc1af151fa452a33679dcb42b93fcbd";
        symbols.sha256 = "03k3y86mgc10ir5l1gdzc0r7w1gg7iavb1zl31kgfh9hnfmgv06w";
        templates.rev = "710c895e2f3be0ec366139bf33c9ca711c990630";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "0836ca140b415055e373de97c466961088d8972a";
        footprints.sha256 = "0jzkrmzkxv3kqqmkpq5dpp3shy9ajfg1b1yzhk4ddzvy8l05qym4";
        packages3d.rev = "1e24671163ce0f44bf57b46445c7e7be1a95977d";
        packages3d.sha256 = "04hw6b4hyl2plfgynin3dv7siqml4341264wz2wngddszq8z32ki";
      };
    };
  };
  "kicad-testing" = {
    kicadVersion = {
      version = "9.0-2025-02-21";
      src = {
        rev = "c4c32aa7bbadd3862fb720457b71e7a19420604c";
        sha256 = "01zbvg6n8kajilj3q1sp0zpaqz94bq28wrxjax1968wvwv05g0dp";
      };
    };
    libVersion = {
      version = "9.0-2025-02-21";
      libSources = {
        symbols.rev = "e1c3371228f97b36c6fd61b66d056184930f078e";
        symbols.sha256 = "0l8da2ix917jlsj6v5zclc1cb5pvjaxwmys0gjdv55ic31hhfyyw";
        templates.rev = "3ed4538b0f965d821df63a5fffc4441e723cfe7f";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "ef91963f57028aa095f2d0c4239ba994ea822f73";
        footprints.sha256 = "16zslgvjg4swgkkvnd9fmiks3wzg63364d03hixiyzcpjlgk2bbk";
        packages3d.rev = "b40831fd7ea2ca8f9c7282143dbb7d2f5015cd69";
        packages3d.sha256 = "0bg54lg1iw01gw06ajg34y7x4y36wm6ls3jnpjy13i18d4ik77g4";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version = "2025-02-21";
      src = {
        rev = "878cf768d6552131494aa792dc20e6ccf67baf75";
        sha256 = "0ky0a7y6gf409y8bwpngiirqin4ivbcjnk8gjdj1a6w79x559sr8";
      };
    };
    libVersion = {
      version = "2025-02-21";
      libSources = {
        symbols.rev = "da86acd48809fd61876223c8bf0e4e7793c52e9a";
        symbols.sha256 = "1sdpg58wbyyrghjd0jqw5iw2094mjy2v9jmwn5zrj4jm6f51g1kd";
        templates.rev = "3ed4538b0f965d821df63a5fffc4441e723cfe7f";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "e515f1c3213317d436e492c8c06620ef4caca84e";
        footprints.sha256 = "16zslgvjg4swgkkvnd9fmiks3wzg63364d03hixiyzcpjlgk2bbk";
        packages3d.rev = "d5db5cea003fe2b4b1c9b145f5fcbd5fdb48f8ca";
        packages3d.sha256 = "0bg54lg1iw01gw06ajg34y7x4y36wm6ls3jnpjy13i18d4ik77g4";
      };
    };
  };
}
