source "https://rubygems.org"

gem "flatito"

gem "minitest", "~> 5.25"
gem "rake", "~> 13.2"
gem "rubocop", "~> 1.73"
gem "rubocop-minitest", "~> 0.37"
gem "rubocop-performance", "~> 1.24"
gem "rubocop-rake", "~> 0.7"
