include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_cssm

security_cssm_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_cssm_HEADER_FILES_DIR = lib

security_cssm_CC_FILES = $(wildcard lib/*.cpp)
security_cssm_C_FILES = $(wildcard lib/*.c)

include $(GNUSTEP_MAKEFILES)/library.make
