# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, happstackServer, mtl, text }:

cabal.mkDerivation (self: {
  pname = "happstack-lite";
  version = "7.3.5";
  sha256 = "1gkzkmg1ad5k9hb4gix2afq1k4j996qpp8mm1jzqk03a5njdpb4b";
  buildDepends = [ happstackServer mtl text ];
  meta = {
    homepage = "http://www.happstack.com/";
    description = "Happstack minus the useless stuff";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
