# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn, devicemapper, libvirt, pkgconfig, btrfs-progs, go-md2man, sqlite, systemd }:

buildGoPackage rec {
  name = "hyperd-${version}";
  version = "20170117-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "0195fadc86e12683820478f4c07dc7a65f867a7f";

  goPackagePath = "github.com/hyperhq/hyperd";

  buildInputs = [ devicemapper libvirt pkgconfig btrfs-progs
    go-md2man sqlite btrfs-progs systemd
  ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/hyperhq/hyperd.git";
    sha256 = "1am0711wbiblrf3ki6jjkb19hj02a0gfsl5dzlmhvdz1y8glbm6w";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
