--- matita-0.5.8/Makefile	2009-12-01 18:21:00.000000000 -0500
+++ matita-0.5.8/Makefile	2010-09-16 10:33:59.665461260 -0400
@@ -38,7 +38,7 @@
 uninstall: $(foreach d,$(SUBDIRS),rec@uninstall@$(d))
 
 rec@%:
-	$(MAKE) -C $(word 2, $(subst @, ,$*)) $(word 1, $(subst @, ,$*)) DESTDIR=$(shell pwd)/$(DESTDIR)
+	$(MAKE) -C $(word 2, $(subst @, ,$*)) $(word 1, $(subst @, ,$*))
 
 # {{{ Distribution stuff
 
