// derived from graphql-vscode/esbuild.js
const { build } = require('esbuild');

build({
  entryPoints: ['bin/graphql.js'],
  bundle: true,
  minify: true,
  sourcemap: false,
  platform: 'node',
  outdir: 'out/',
  external: [
    'pnpapi',
    // Avoid bundling @vue/compiler-sfc's dynamic dependencies
    'squirrelly',
    'teacup',
    'coffee-script',
    'marko',
    'slm',
    'vash',
    'plates',
    'babel-core',
    'htmling',
    'ractive',
    'mote',
    'eco',
    'jqtpl',
    'hamljs',
    'jazz',
    'hamlet',
    'whiskers',
    'haml-coffee',
    'hogan.js',
    'templayed',
    'walrus',
    'mustache',
    'just',
    'ect',
    'toffee',
    'twing',
    'dot',
    'bracket-template',
    'vscode',
    'velocityjs',
    'dustjs-linkedin',
    'atpl',
    'liquor',
    'twig',
  ],
});
