# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "gnome-clocks-3.26.1";

  src = fetchurl {
    url = mirror://gnome/sources/gnome-clocks/3.26/gnome-clocks-3.26.1.tar.xz;
    sha256 = "2bd8d8df1d6aa0feddd4afc15d84b1308202fda59a3c3be42e3bce7e9ccd11f7";
  };
}
