--- crypto++/GNUmakefile 2013-02-20 10:30:52.000000000 -0500
+++ crypto++/GNUmakefile 2015-05-07 18:34:25.000000000 -0500
@@ -87,8 +87,8 @@
 endif

 ifeq ($(UNAME),Darwin)
-AR = libtool
-ARFLAGS = -static -o
+AR = ar
+ARFLAGS = cru
 CXX = c++
 IS_GCC2 = $(shell $(CXX) -v 2>&1 | $(EGREP) -c gcc-932)
 ifeq ($(IS_GCC2),1)
