* ibus-engines.typing-booster
  :PROPERTIES:
  :CUSTOM_ID: sec-ibus-typing-booster
  :END:

This package is an ibus-based completion method to speed up typing.

** Activating the engine
   :PROPERTIES:
   :CUSTOM_ID: sec-ibus-typing-booster-activate
   :END:

IBus needs to be configured accordingly to activate =typing-booster=.
The configuration depends on the desktop manager in use. For detailed
instructions, please refer to the
[[https://mike-fabian.github.io/ibus-typing-booster/documentation.html][upstream
docs]].

On NixOS you need to explicitly enable =ibus= with given engines before
customizing your desktop to use =typing-booster=. This can be achieved
using the =ibus= module:

#+BEGIN_EXAMPLE
  { pkgs, ... }: {
    i18n.inputMethod = {
      enabled = "ibus";
      ibus.engines = with pkgs.ibus-engines; [ typing-booster ];
    };
  }
#+END_EXAMPLE

** Using custom hunspell dictionaries
   :PROPERTIES:
   :CUSTOM_ID: sec-ibus-typing-booster-customize-hunspell
   :END:

The IBus engine is based on =hunspell= to support completion in many
languages. By default the dictionaries =de-de=, =en-us=, =fr-moderne=
=es-es=, =it-it=, =sv-se= and =sv-fi= are in use. To add another
dictionary, the package can be overridden like this:

#+BEGIN_EXAMPLE
  ibus-engines.typing-booster.override {
    langs = [ "de-at" "en-gb" ];
  }
#+END_EXAMPLE

/Note: each language passed to =langs= must be an attribute name in
=pkgs.hunspellDicts=./

** Built-in emoji picker
   :PROPERTIES:
   :CUSTOM_ID: sec-ibus-typing-booster-emoji-picker
   :END:

The =ibus-engines.typing-booster= package contains a program named
=emoji-picker=. To display all emojis correctly, a special font such as
=noto-fonts-emoji= is needed:

On NixOS it can be installed using the following expression:

#+BEGIN_EXAMPLE
  { pkgs, ... }: {
    fonts.fonts = with pkgs; [ noto-fonts-emoji ];
  }
#+END_EXAMPLE
