#! /bin/sh -e

url=$1
rev=$2
expHash=$3

hashType=$NIX_HASH_ALGO
if test -z "$hashType"; then
    hashType=sha256
fi
if test -z "$hashFormat"; then
    hashFormat=--base32
fi

if test -z "$url"; then
    echo "syntax: nix-prefetch-hg URL [rev [EXPECTED-HASH]]" >&2
    exit 1
fi

test -n "$rev" || rev="tip"


# If the hash was given, a file with that hash may already be in the
# store.
if test -n "$expHash"; then
    finalPath=$(nix-store --print-fixed-path --recursive "$hashType" "$expHash" hg-archive)
    if ! nix-store --check-validity "$finalPath" 2> /dev/null; then
        finalPath=
    fi
    hash=$expHash
fi


# If we don't know the hash or a path with that hash doesn't exist,
# download the file and add it to the store.
if test -z "$finalPath"; then

    tmpPath=/tmp/hg-checkout-tmp-$$
    tmpArchive=$tmpPath/hg-archive
    mkdir $tmpPath

    trap "rm -rf $tmpPath" EXIT

    # Perform the checkout.
    if [[ $url != /* ]]; then
      tmpClone=$tmpPath/hg-clone
      hg clone -q -y -U "$url" $tmpClone >&2
    else
      tmpClone=$url
    fi
    hg archive -q -y -r "$rev" --cwd $tmpClone $tmpArchive
    rm -f $tmpArchive/.hg_archival.txt

    echo "hg revision is $(cd $tmpClone; hg id -r "$rev" -i)"

    # Compute the hash.
    hash=$(nix-hash --type $hashType $hashFormat $tmpArchive)
    if ! test -n "$QUIET"; then echo "hash is $hash" >&2; fi

    # Add the downloaded file to the Nix store.
    finalPath=$(nix-store --add-fixed --recursive "$hashType" $tmpArchive)

    if test -n "$expHash" -a "$expHash" != "$hash"; then
        echo "hash mismatch for URL \`$url'"
        exit 1
    fi


fi

if ! test -n "$QUIET"; then echo "path is $finalPath" >&2; fi

echo $hash

if test -n "$PRINT_PATH"; then
    echo $finalPath
fi
