#!/bin/bash

python=PYTHON_LIB_PREFIX

case "$1" in
    path)
        echo $(dirname $0)/../lib/$python/site-packages
        ;;
    *)
        echo Usage:
        echo "  $(basename $0) path"
        exit 1
esac
