--- a/Makefile	2015-04-21 00:40:46.949266581 +0200
+++ b/Makefile	2015-04-21 00:41:38.637165883 +0200
@@ -24,9 +24,9 @@
 RAW_FLAGS += -DVERSION=\"$(VERSION)\"
 
 # Where we get installed
-BIN = /usr/local/bin
-MAN = /usr/share/man/man8
-CONF= /usr/local/etc
+BIN = $(PREFIX)/bin
+MAN = $(PREFIX)/share/man/man8
+CONF= $(PREFIX)/etc
 # Setup for compiling and cross-compiling for Windows
 # The CR_ prefix refers to cross compiling from OSX to Windows
 CR_CC = $(CR_BASE)/gcc
@@ -120,7 +120,6 @@
 install: goals
 	install -m 755 $(NAME) $(BIN)
 	install -m 444 $(MAN_PAGES) $(MAN)
-	install -m 444 foremost.conf $(CONF)
 macinstall: BIN = /usr/local/bin/
 macinstall: MAN = /usr/share/man/man1/
 macinstall: CONF = /usr/local/etc/
