# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "discourse_subscription_client", "0.1.11"
gem "iso-639", "0.3.5"
gem "ice_cube", "0.16.4"
gem "icalendar", "2.8.0"
gem "icalendar-recurrence", "1.1.3"
