# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "gtksourceview-3.24.6";

  src = fetchurl {
    url = mirror://gnome/sources/gtksourceview/3.24/gtksourceview-3.24.6.tar.xz;
    sha256 = "7aa6bdfebcdc73a763dddeaa42f190c40835e6f8495bb9eb8f78587e2577c188";
  };
}
