# frozen_string_literal: true
source "https://rubygems.org"

gem 'licensed', '=5.0.0'

gem 'csv' , '~> 3.0'
gem 'byebug', '~> 11.1'
gem 'minitest', '~> 5.17'
gem 'minitest-hooks', '~> 1.5'
gem 'mocha', '~> 2.0'
gem 'rake', '~> 13.0'
gem 'rubocop-github', '~> 0.20'
