# This file is autogenerated from update.py in the same directory.
{
  icedtea7 = rec {
    version = "2.5.2";

    url = "http://icedtea.wildebeest.org/download/source/icedtea-${version}.tar.xz";
    sha256 = "1w2vnk8b1c5wlb25hq69ii4wf2kxfy631yihxigv3aa9lp31l7hp";

    drop_url = "http://icedtea.classpath.org/download/drops/icedtea7/${version}";

    bundles = {
      openjdk = rec {
        url = "${drop_url}/openjdk.tar.bz2";
        sha256 = "a0f1e39980d4774fec4d6d1096a7c6c5858920536977dec294ec14c5c93d4fb9";
      };

      corba = rec {
        url = "${drop_url}/corba.tar.bz2";
        sha256 = "f6afe3f5dbec8723d650ac4ecbaf6aa41cd90759eb6503f0397248098a9e1c77";
      };

      jaxp = rec {
        url = "${drop_url}/jaxp.tar.bz2";
        sha256 = "abd68afe382a92b51a45547bd272c12569cf0d166a1f2f00cc3a9ef0fa988a4b";
      };

      jaxws = rec {
        url = "${drop_url}/jaxws.tar.bz2";
        sha256 = "069def5538e1e52ed831f9657a9b9ea8e9401788390b54290f2fd7c1bd0b6ccc";
      };

      jdk = rec {
        url = "${drop_url}/jdk.tar.bz2";
        sha256 = "992a726be72bce1ad9a275b1fc1782c0beb0f80c50de35a989258a56fdfd2ffd";
      };

      langtools = rec {
        url = "${drop_url}/langtools.tar.bz2";
        sha256 = "5f04fffdcbb4a76cd57c8319c676537c9481625e0c686e172a152deeb7871811";
      };

      hotspot = rec {
        url = "${drop_url}/hotspot.tar.bz2";
        sha256 = "b8c1f0e6560a3300d145784c1a73e02ddecbad38b8ce9511a930b1e7599c8c51";
      };
    };
  };
}
