# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeBuilder, httpTypes, HUnit, mtl, parsec, QuickCheck
, split, testFramework, testFrameworkHunit
, testFrameworkQuickcheck2, testFrameworkTh, text, utf8String
}:

cabal.mkDerivation (self: {
  pname = "web-routes";
  version = "0.27.7";
  sha256 = "0q6rl8vasbkq24jdfdq6jrjivcqqmdy34w8zw5zczmscpyjqf0zb";
  buildDepends = [
    blazeBuilder httpTypes mtl parsec split text utf8String
  ];
  testDepends = [
    HUnit QuickCheck testFramework testFrameworkHunit
    testFrameworkQuickcheck2 testFrameworkTh
  ];
  meta = {
    description = "Library for maintaining correctness and composability of URLs within an application";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ ocharles ];
  };
})
