# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'bcrypt', '3.1.13'
gem 'unix-crypt', '1.3.0'
gem 'ffi', '1.16.3', require: false
gem 'ffi-compiler', '1.0.1', require: false
gem 'argon2', '2.2.0'
