# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeHtml, blazeMarkup, caseInsensitive, clientsession
, conduit, conduitExtra, cpphs, extensibleExceptions, httpTypes
, monadloc, mtl, parsec, pwstoreFast, random, RefSerialize
, resourcet, stm, TCache, text, time, transformers, utf8String
, vector, wai, waiExtra, warp, warpTls, Workflow
}:

cabal.mkDerivation (self: {
  pname = "MFlow";
  version = "0.4.5.8";
  sha256 = "1gfv5ky68dyn8gjjg60c5s9x3dl9xn6j9q43w7vaj9sd1q12wk3c";
  buildDepends = [
    blazeHtml blazeMarkup caseInsensitive clientsession conduit
    conduitExtra extensibleExceptions httpTypes monadloc mtl parsec
    pwstoreFast random RefSerialize resourcet stm TCache text time
    transformers utf8String vector wai waiExtra warp warpTls Workflow
  ];
  buildTools = [ cpphs ];
  meta = {
    description = "stateful, RESTful web framework";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ tomberek ];
  };
})
