include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_cdsa_plugin

security_cdsa_plugin_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_cdsa_plugin_HEADER_FILES_DIR = lib

security_cdsa_plugin_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
