diff -ruN mingetty-1.07.orig/Makefile mingetty-1.07.orig.new/Makefile
--- mingetty-1.07.orig/Makefile	2003-05-24 21:21:17.000000000 +0200
+++ mingetty-1.07.orig.new/Makefile	2005-06-23 15:43:28.000000000 +0200
@@ -1,4 +1,4 @@
-DESTDIR=
+DESTDIR=$(out)
 CC=gcc
 CFLAGS=-O2 -Wall -W -pipe -D_GNU_SOURCE
 MANDIR=/usr/share/man/man8
@@ -7,8 +7,8 @@
 all:		mingetty
 
 install:	all
-		install -m 0755 mingetty $(DESTDIR)$(SBINDIR)
-		install -m 0644 mingetty.8 $(DESTDIR)$(MANDIR)
+		install -D -m 0755 mingetty $(DESTDIR)$(SBINDIR)/mingetty
+		install -D -m 0644 mingetty.8 $(DESTDIR)$(MANDIR)/mingetty.8
 
 mingetty:	mingetty.o
 
