diff --git a/Makefile b/Makefile
index db61eb2..dc0be31 100644
--- a/Makefile
+++ b/Makefile
@@ -4,6 +4,7 @@ include $(_SRC)/Makefile.vars # AKMOD can be annoying so preventing his silent c
 DKMS_ROOT_PATH  := /usr/src/msi_ec-$(VERSION)
 
 KERNELRELEASE := $(shell uname -r)
+KERNELDIR ?= /lib/modules/$(KERNELRELEASE)/build/
 
 KMOD_DIR        := /lib/modules/$(KERNELRELEASE)/updates/drivers/platform/x86
 
@@ -14,10 +15,13 @@ obj-m += $(MODNAME).o
 all: modules
 
 modules:
-	@$(MAKE) -C /lib/modules/$(KERNELRELEASE)/build M=$(CURDIR) modules
+	@$(MAKE) -C $(KERNELDIR) M=$(CURDIR) modules
+
+modules_install:
+	@$(MAKE) -C $(KERNELDIR) M=$(CURDIR) modules_install
 
 clean:
-	@$(MAKE) -C /lib/modules/$(KERNELRELEASE)/build M=$(CURDIR) clean
+	@$(MAKE) -C $(KERNELDIR) M=$(CURDIR) clean
 
 load:
 	insmod msi-ec.ko
