#!@bash@/bin/bash
#
# Dummy init file for network, hacketyhack!
#
# chkconfig: 2345 55 25
# description: OpenSSH server daemon
#
# processname: sshd

# source function library
source @initscripts@/functions

# pull in sysconfig settings
#[ -f /etc/sysconfig/sshd ] && . /etc/sysconfig/sshd

RETVAL=0
prog="network"
INTERFACE=eth0

startService()
{
	# just do networking
	echo -n "Starting $prog:"
	@dhcp@/sbin/dhclient $INTERFACE

	RETVAL=$?
	echo "retval $RETVAL"
	return $RETVAL
}

stopService()
{
	echo "BLAAT"
}

reload()
{
	start
	stop
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		reload
		;;
	status)
		status
		;;
	name)
		name
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status|name}"
		RETVAL=1
esac
exit $RETVAL
