# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/flosch/pongo2";
    fetch = {
      type = "git";
      url = "https://github.com/flosch/pongo2";
      rev = "79872a7b27692599b259dc751bed8b03581dd0de";
      sha256 = "0v1z3wmc2ii5znw0ap3mw9xi2n8dsvv2pidm22lga337h5cmlnhy";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "e91709a02e0e8ff8b86b7aa913fdc9ae9498e825";
      sha256 = "16arbb7nwvs7lkpr7i9vrv8mk9h77zd3blzp3z9b0infqla4ddzc";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "80c2d40e9b91f2ef7a9c1a403aeec64d1b89a9a6";
      sha256 = "059pkf9d9yl4mg0r66pxc4003w41m5qa5fcs7gsadbrj97ayjb9k";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/terraform";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/terraform";
      rev = "c5a2e922ce2cd2a6ae02fe6896ef4eff49404523";
      sha256 = "145cibpxpcy9qwswhfcggnq2n7qdnrjdbv2b7af24amzzr3y6j60";
    };
  }
  {
    goPackagePath = "github.com/juju/errors";
    fetch = {
      type = "git";
      url = "https://github.com/juju/errors";
      rev = "e65537c515d77e35697c471d6c2755375cb3adc4";
      sha256 = "119806fhl4isbxc3g52335jgiv6cddfbapr1absd4v4kkq55i5qh";
    };
  }
  {
    goPackagePath = "github.com/juju/go4";
    fetch = {
      type = "git";
      url = "https://github.com/juju/go4";
      rev = "40d72ab9641a2a8c36a9c46a51e28367115c8e59";
      sha256 = "0sjxa2lnk244si525034fxks593fngnmdjq707g6g7x0c00q1ybg";
    };
  }
  {
    goPackagePath = "github.com/juju/loggo";
    fetch = {
      type = "git";
      url = "https://github.com/juju/loggo";
      rev = "d976af380377adda50b2d34279f1dec3507504ac";
      sha256 = "08qdc31vwnfw5v5jljk9amncffvyzqpdjxnx8fx5ngyq0l541x9r";
    };
  }
  {
    goPackagePath = "github.com/juju/persistent-cookiejar";
    fetch = {
      type = "git";
      url = "https://github.com/juju/persistent-cookiejar";
      rev = "d5e5a8405ef9633c84af42fbcc734ec8dd73c198";
      sha256 = "059k97xilmlwqhr98f3mhw0zqswsfs1y6x9lv72lba62g66hcxpa";
    };
  }
  {
    goPackagePath = "github.com/juju/schema";
    fetch = {
      type = "git";
      url = "https://github.com/juju/schema";
      rev = "29562ba24201043ee1dd1ef422ff1d16fc1cf29d";
      sha256 = "1326d8hjw502yblw6pjysiq75i1ryff7zaikwb4v9kjz8z79mnyp";
    };
  }
  {
    goPackagePath = "github.com/juju/webbrowser";
    fetch = {
      type = "git";
      url = "https://github.com/juju/webbrowser";
      rev = "efb9432b2bcb671b0cf2237468e209d10e2ac373";
      sha256 = "1f6nabdgzgwz5bamzhfz4yhm0i53s3j2s8jzwp512i2a52ml6bh2";
    };
  }
  {
    goPackagePath = "github.com/julienschmidt/httprouter";
    fetch = {
      type = "git";
      url = "https://github.com/julienschmidt/httprouter";
      rev = "26a05976f9bf5c3aa992cc20e8588c359418ee58";
      sha256 = "0bmvrgg373fxwqsr6nri01bmi9qdj6knxkmnbw70h9rmi2d9c585";
    };
  }
  {
    goPackagePath = "github.com/lxc/lxd";
    fetch = {
      type = "git";
      url = "https://github.com/lxc/lxd";
      rev = "a521c64536980fbdeaf184e8a25e1696d58f4c27";
      sha256 = "16wx5g7mf2m237ipvd1kccczdh71s7zg6w0djf7gz27hk21y8kgv";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "af06845cf3004701891bf4fdb884bfe4920b3727";
      sha256 = "0ydzkipf28hwj2bfxqmwlww47khyk6d152xax4bnyh60f4lq3nx1";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "27936f6d90f9c8e1145f11ed52ffffbfdb9e0af7";
      sha256 = "0yzmgi6g4ak4q8y7w6x0n5cbinlcn8yc3gwgzy4yck00qdn25d6y";
    };
  }
  {
    goPackagePath = "github.com/rogpeppe/fastuuid";
    fetch = {
      type = "git";
      url = "https://github.com/rogpeppe/fastuuid";
      rev = "d61b6ae132d93dcb396be506396bf9a5127a41aa";
      sha256 = "0bc9wx3m6lgsbykb3dharzpajl5m7indnyc9ky60flbalq39zs6x";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "a29dc8fdc73485234dbef99ebedb95d2eced08de";
      sha256 = "07f0jj4haqs0ywc1akk1qjwn5msl2j0pry1rxjkkbfcq4r6ihc1p";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "9ce7a6920f093fc0b908c4a5f66ae049110f417e";
      sha256 = "1kbs85jsqbv4v89ii2zam4b8dhmllhsrf46njmi09x0w6s0b9cbk";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "d89cdac9e8725f2aefce25fcbfef41134c9ad412";
      sha256 = "0iazr13ir6i267nb2w81lc3pr740wdjs86nsliwpf90kkgzn853f";
    };
  }
  {
    goPackagePath = "gopkg.in/errgo.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/errgo.v1";
      rev = "08dc5b27f5ced65786776ec936b4298445ec70cf";
      sha256 = "17g3lmbkg0c2axlak482cp0qqssf6vrfnhcfmrw5hzg1y13cbz9k";
    };
  }
  {
    goPackagePath = "gopkg.in/httprequest.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/httprequest.v1";
      rev = "7f3c32e65ad57476ba9675100248f4f87f6ffb9c";
      sha256 = "19m1gjyh4xip63wkz2r4p624x4qldph2lsancgbh0hqa6p1v3bzw";
    };
  }
  {
    goPackagePath = "gopkg.in/juju/environschema.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/juju/environschema.v1";
      rev = "d79e96fb1039e808c217847f4c45cce48e6ff2a5";
      sha256 = "1fsdwbmxbhghdspdgb8mdk21ps9g9nd3rkdzb0xvpf60kvnsr8xr";
    };
  }
  {
    goPackagePath = "gopkg.in/macaroon-bakery.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/macaroon-bakery.v2";
      rev = "a0743b6619d68bbf8dc5cabbb49738b846f06080";
      sha256 = "1pzgwd41mnwwm8flnqpf4f7rhzwycfswnaz5nq80wz766w9g9glr";
    };
  }
  {
    goPackagePath = "gopkg.in/macaroon.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/macaroon.v2";
      rev = "1679699b0b723e05f9f16c45b4c6cbd46adb2c78";
      sha256 = "1hl9c36pp521npndyx9jzv7ic0i6nnydra4i1nbdbgda2gzb9qiy";
    };
  }
  {
    goPackagePath = "gopkg.in/retry.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/retry.v1";
      rev = "87155f248cf6ea9e38ae7613f9ea1e5bb397ac83";
      sha256 = "13wqik2garzl025kd4irpl1wh5sscn2bk10iq7al4rrl2p0z3yb3";
    };
  }
  {
    goPackagePath = "gopkg.in/robfig/cron.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/robfig/cron.v2";
      rev = "be2e0b0deed5a68ffee390b4583a13aff8321535";
      sha256 = "1cmm6dc4cl8269wlknxmicyn1s63irg66lj76b9ncjjfrvijpf0y";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }
]
