#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl nix jq

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

releasesJson="$(curl --fail -s ${GITHUB_TOKEN:+-u ":$GITHUB_TOKEN"} "https://api.github.com/repos/brave/brave-browser/releases?per_page=20")"

releaseJson="$(
  jq -c '
    map(
      select(.prerelease)
      | .tag_name as $tag
      | .assets as $assets
      | select(any($assets[]?.name; . == ("brave-origin-nightly_" + ($tag | ltrimstr("v")) + "_amd64.deb")))
    )
    | first
  ' <<<"$releasesJson"
)"

latestVersion="$(jq -r '.tag_name | ltrimstr("v")' <<<"$releaseJson")"

if [[ -z "$latestVersion" || "$latestVersion" == "null" ]]; then
  echo "Could not determine latest brave-origin version." >&2
  exit 1
fi

hasAsset() {
  jq -e --arg name "$1" 'any(.assets[]?.name; . == $name)' <<<"$releaseJson" >/dev/null
}

requireAsset() {
  if ! hasAsset "$1"; then
    echo "Missing expected asset: $1" >&2
    exit 1
  fi
}

requireAsset "brave-origin-nightly_${latestVersion}_amd64.deb"

if hasAsset "brave-origin-nightly_${latestVersion}_arm64.deb"; then
  hashAarch64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-nightly_${latestVersion}_arm64.deb")")"
fi

hashAmd64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-nightly_${latestVersion}_amd64.deb")")"

if hasAsset "brave-origin-v${latestVersion}-darwin-arm64.zip"; then
  hashAarch64Darwin="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-v${latestVersion}-darwin-arm64.zip")")"
fi

if hasAsset "brave-origin-v${latestVersion}-darwin-x64.zip"; then
  hashAmd64Darwin="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-v${latestVersion}-darwin-x64.zip")")"
fi

cat >"$SCRIPT_DIR/package.nix" <<EOF
# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "${latestVersion}";

  allArchives = {
EOF

if hasAsset "brave-origin-nightly_${latestVersion}_arm64.deb"; then
  cat >>"$SCRIPT_DIR/package.nix" <<EOF
    aarch64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-nightly_\${version}_arm64.deb";
      hash = "${hashAarch64}";
    };
EOF
fi

cat >>"$SCRIPT_DIR/package.nix" <<EOF
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-nightly_\${version}_amd64.deb";
      hash = "${hashAmd64}";
    };
EOF

if hasAsset "brave-origin-v${latestVersion}-darwin-arm64.zip"; then
  cat >>"$SCRIPT_DIR/package.nix" <<EOF
    aarch64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-v\${version}-darwin-arm64.zip";
      hash = "${hashAarch64Darwin}";
    };
EOF
fi

if hasAsset "brave-origin-v${latestVersion}-darwin-x64.zip"; then
  cat >>"$SCRIPT_DIR/package.nix" <<EOF
    x86_64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-v\${version}-darwin-x64.zip";
      hash = "${hashAmd64Darwin}";
    };
EOF
fi

cat >>"$SCRIPT_DIR/package.nix" <<EOF
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
EOF
