# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, alex, deepseq, filepath, happy, hspec, HUnit, mtl
, QuickCheck, temporary
}:

cabal.mkDerivation (self: {
  pname = "BNFC";
  version = "2.7.0.1";
  sha256 = "18009jrpd5kcaz06j4ksay4c7c65m4zrc7jrp3rjx81bs6gkrwk1";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ deepseq filepath mtl ];
  testDepends = [
    deepseq filepath hspec HUnit mtl QuickCheck temporary
  ];
  buildTools = [ alex happy ];
  meta = {
    homepage = "http://bnfc.digitalgrammars.com/";
    description = "A compiler front-end generator";
    license = self.stdenv.lib.licenses.gpl2;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ andres simons ];
  };
})
