if(NOT ATTRIBUTE_NAME)
  set(ATTRIBUTE_NAME "cmakeEntries")
endif()

if (NOT VARIABLE_NAME)
  set(VARIABLE_NAME "${ATTRIBUTE_NAME}")
endif()

message(DEBUG "Setting Bash associative array ${ATTRIBUTE_NAME} from \$NIX_ATTRS_JSON_FILE")

if(NOT ATTRS_JSON_FILE)
  set(ATTRS_JSON_FILE $ENV{NIX_ATTRS_JSON_FILE})
endif()

if (NOT CMAKE_ENTRIES_OBJECT_STRING) # For testing
  file(READ "${ATTRS_JSON_FILE}" ATTRS_JSON_STRING)
  string(JSON CMAKE_ENTRIES_OBJECT_STRING ERROR_VARIABLE ERROR_VAR GET_RAW "${ATTRS_JSON_STRING}" ${ATTRIBUTE_NAME})
  unset(ATTRS_JSON_STRING)
endif()

if (NOT CMAKE_ENTRIES_OBJECT_STRING)
  message(DEBUG "GenCMakeEntriesRC: Attribute ${ATTRIBUTE_NAME} not defined. Doing nothing.")
  cmake_language(EXIT 0)
endif()

set(UNEXPECTED_TYPES NULL ARRAY OBJECT)

string(JSON CMAKE_ENTRIES_LENGTH LENGTH "${CMAKE_ENTRIES_OBJECT_STRING}")

if (CMAKE_ENTRIES_LENGTH EQUAL 0)
  message(DEBUG "GenCMakeEntriesRC: Attribute ${ATTRIBUTE_NAME} is empty. Doing nothing.")
  cmake_language(EXIT 0)
endif()

math(EXPR CMAKE_ENTRIES_LENGTH_M1 "${CMAKE_ENTRIES_LENGTH} - 1")

if (NOT OUTPUT_SCRIPT_NAME) # For testing
  set(OUTPUT_SCRIPT_NAME "/dev/stdout")
  if(NOT OUTPUT_SCRIPT_NAME MATCHES "^/")
    file(REMOVE "${OUTPUT_SCRIPT_NAME}")
  endif()
endif()

set(DECLARE_PREFIX_ENTRY_VALUE "declare -x _cmake_entry_value=")
string(LENGTH "${DECLARE_PREFIX_ENTRY_VALUE}" DECLARE_PREFIX_ENTRY_VALUE_LENGTH)

foreach(IDX RANGE "${CMAKE_ENTRIES_LENGTH_M1}")
  string(JSON CMAKE_ENTRY_NAME MEMBER "${CMAKE_ENTRIES_OBJECT_STRING}" "${IDX}")
  string(JSON CMAKE_ENTRY_TYPE TYPE "${CMAKE_ENTRIES_OBJECT_STRING}" "${CMAKE_ENTRY_NAME}")
  if (IGNORE_NULL AND CMAKE_ENTRY_TYPE STREQUAL "NULL")
    continue()
  endif()
  list(FIND UNEXPECTED_TYPES ${CMAKE_ENTRY_TYPE} UNEXPECTED_TYPE_FOUND)
  if (NOT UNEXPECTED_TYPE_FOUND STREQUAL "-1")
    message(FATAL_ERROR "GenCMakeEntriesRC: Unexpected value type ${CMAKE_ENTRY_TYPE} for ${ATTRIBUTE_NAME}.${CMAKE_ENTRY_NAME}")
  endif()
  string(JSON CMAKE_ENTRY_VALUE GET "${CMAKE_ENTRIES_OBJECT_STRING}" "${CMAKE_ENTRY_NAME}")
  set(ENV{_cmake_entry_value} "${CMAKE_ENTRY_VALUE}")
  execute_process(
    COMMAND bash -c "declare -p _cmake_entry_value"
    OUTPUT_VARIABLE CMAKE_ENTRY_VALUE_DECLARE_STRING
    COMMAND_ERROR_IS_FATAL ANY
  )
  unset($ENV{_cmake_entry_value})
  string(SUBSTRING "${CMAKE_ENTRY_VALUE_DECLARE_STRING}" "${DECLARE_PREFIX_ENTRY_VALUE_LENGTH}" -1 CMAKE_ENTRY_VALUE_ESCAPED)
  file(APPEND "${OUTPUT_SCRIPT_NAME}" "${VARIABLE_NAME}[${CMAKE_ENTRY_NAME}]=${CMAKE_ENTRY_VALUE_ESCAPED}")
endforeach()

unset(CMAKE_ENTRY_VALUE)
unset(CMAKE_ENTRIES_OBJECT_STRING)
