message(INFO "Parsing attribute cmakeEntries from JSON")

if(NOT ATTRS_JSON_FILE)
  set(ATTRS_JSON_FILE $ENV{NIX_ATTRS_JSON_FILE})
endif()

if (NOT CMAKE_ENTRIES_OBJECT_STRING) # For testing
  file(READ ${ATTRS_JSON_FILE} ATTRS_JSON_STRING)
  string(JSON CMAKE_ENTRIES_OBJECT_STRING GET "${ATTRS_JSON_STRING}" cmakeEntries)
  unset(ATTRS_JSON_STRING)
endif()

if (NOT CMAKE_ENTRIES_OBJECT_STRING)
  message(INFO "ParseCMakeEntryAttrs: Attribute cmakeEntries not defined. Doing nothing.")
  cmake_language(EXIT 0)
endif()

set(UNEXPECTED_TYPES NULL ARRAY OBJECT)

string(JSON CMAKE_ENTRIES_LENGTH LENGTH "${CMAKE_ENTRIES_OBJECT_STRING}")
math(EXPR CMAKE_ENTRIES_LENGTH_M1 "${CMAKE_ENTRIES_LENGTH} - 1")

if (NOT OUTPUT_SCRIPT_NAME) # For testing
  set(OUTPUT_SCRIPT_NAME ".attrs.cmakeEntries.sh")
  file(REMOVE ${OUTPUT_SCRIPT_NAME})
endif()

set(DECLARE_PREFIX_ENTRY_VALUE "declare -x CMAKE_ENTRY_VALUE=")
string(LENGTH ${DECLARE_PREFIX_ENTRY_VALUE} DECLARE_PREFIX_ENTRY_VALUE_LENGTH)

foreach(IDX RANGE ${CMAKE_ENTRIES_LENGTH_M1})
  string(JSON CMAKE_ENTRY_NAME MEMBER "${CMAKE_ENTRIES_OBJECT_STRING}" ${IDX})
  list(APPEND CMAKE_ENTY_NAMES ${CMAKE_ENTRY_NAME})
  string(JSON CMAKE_ENTRY_TYPE TYPE "${CMAKE_ENTRIES_OBJECT_STRING}" ${CMAKE_ENTRY_NAME})
  list(FIND UNEXPECTED_TYPES ${CMAKE_ENTRY_TYPE} UNEXPECTED_TYPE_FOUND)
  if (NOT UNEXPECTED_TYPE_FOUND STREQUAL "-1")
    message(FATAL_ERROR "ParseCMakeEntryAttrs: Unexpected value type ${CMAKE_ENTRY_TYPE} for cmakeEntries.${CMAKE_ENTRY_NAME}")
  endif()
  string(JSON CMAKE_ENTRY_VALUE GET "${CMAKE_ENTRIES_OBJECT_STRING}" ${CMAKE_ENTRY_NAME})
  set(ENV{CMAKE_ENTRY_VALUE} "${CMAKE_ENTRY_VALUE}")
  execute_process(
    COMMAND bash -c "declare -p CMAKE_ENTRY_VALUE"
    OUTPUT_VARIABLE CMAKE_ENTRY_VALUE_DECLARE_STRING
    COMMAND_ERROR_IS_FATAL ANY
  )
  unset($ENV{CMAKE_ENTRY_VALUE})
  string(SUBSTRING "${CMAKE_ENTRY_VALUE_DECLARE_STRING}" ${DECLARE_PREFIX_ENTRY_VALUE_LENGTH} -1 CMAKE_ENTRY_VALUE_ESCAPED)
  file(APPEND ${OUTPUT_SCRIPT_NAME} "cmakeEntries[${CMAKE_ENTRY_NAME}]=${CMAKE_ENTRY_VALUE_ESCAPED}")
endforeach()

unset(CMAKE_ENTRY_VALUE)
unset(CMAKE_ENTRIES_OBJECT_STRING)
