include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_apple_file_dl

security_apple_file_dl_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_apple_file_dl_HEADER_FILES_DIR = lib

security_apple_file_dl_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
