#!/bin/bash

set "$(dirname "$0")"/X11.bin "${@}"

export XQUARTZ_DEFAULT_CLIENT="@DEFAULT_CLIENT@"
export XQUARTZ_DEFAULT_SHELL="@DEFAULT_SHELL@"
export XQUARTZ_DEFAULT_STARTX="@DEFAULT_STARTX@"
export FONTCONFIG_FILE="@FONTCONFIG_FILE@"

if [ -x ~/.x11run ]; then
    exec ~/.x11run "${@}"
fi

case $(basename "${SHELL}") in
    bash)          exec -l "${SHELL}" --login -c 'exec "${@}"' - "${@}" ;;
    ksh|sh|zsh)    exec -l "${SHELL}" -c 'exec "${@}"' - "${@}" ;;
    csh|tcsh)      exec -l "${SHELL}" -c 'exec $argv:q' "${@}" ;;
    es|rc)         exec -l "${SHELL}" -l -c 'exec $*' "${@}" ;;
    *)             exec    "${@}" ;;
esac
