{ ...}:
/* List of NixOS maintainers. The format is:

    handle = { name = "Real Name"; email = "address@example.org>";
               GitHub ="GH handle"; IRC = "IRC handle"; };

  where
  - <handle> is preferred to be your GitHub username
     (so it's easy to ping a package @<handle>)
  - <Real Name> is your real name, not a pseudonym
  - <GH handle> will default to <handle>. It can be used to override
     our GitHub account name. E.g. eelco = { GitHub = "edolstra"; }
     If you do not have GitHub, or do not want GitHub to be linked,
     set GitHub = null;
  - <IRC handle> (optional), your IRC name on FreeNode

  Please keep the list alphabetically sorted. */
let maintainers = {
  Adjective-Object = { name = "Maxwell Huang-Hobbs"; email = "mhuan13@gmail.com"; };
  AndersonTorres = { name = "Anderson Torres"; email = "torres.anderson.85@gmail.com"; };
  Baughn = { name = "Svein Ove Aas"; email = "sveina@gmail.com"; };
  ChengCat = { name = "Yucheng Zhang"; email = "yu@cheng.cat"; };
  CrystalGamma = { name = "Jona Stubbe"; email = "nixos@crystalgamma.de"; };
  DamienCassou = { name = "Damien Cassou"; email = "damien@cassou.me"; };
  DerGuteMoritz = { name = "Moritz Heidkamp"; email = "moritz@twoticketsplease.de"; };
  DerTim1 = { name = "Tim Digel"; email = "tim.digel@active-group.de"; };
  DmitryTsygankov = { name = "Dmitry Tsygankov"; email = "dmitry.tsygankov@gmail.com"; };
  FireyFly = { name = "Jonas Höglund"; email = "nix@firefly.nu"; };
  Gonzih = { name = "Max Gonzih"; email = "gonzih@gmail.com"; };
  KibaFox = { name = "Kiba Fox"; email = "kiba.fox@foxypossibilities.com"; };
  MP2E = { name = "Cray Elliott"; email = "MP2E@archlinux.us"; };
  MostAwesomeDude = { name = "Corbin Simpson"; email = "cds@corbinsimpson.com"; };
  Nate-Devv = { name = "Nathan Moore"; email = "natedevv@gmail.com"; };
  NikolaMandic = { name = "Ratko Mladic"; email = "nikola@mandic.email"; };
  Phlogistique = { name = "Noé Rubinstein"; email = "noe.rubinstein@gmail.com"; };
  SShrike = { name = "Severen Redwood"; email = "severen@shrike.me"; };
  SeanZicari = { name = "Sean Zicari"; email = "sean.zicari@gmail.com"; };
  SuprDewd = { name = "Bjarki Ágúst Guðmundsson"; email = "suprdewd@gmail.com"; };
  TealG = { name = "Teal Gaure"; email = "~@Teal.Gr"; };
  ThomasMader = { name = "Thomas Mader"; email = "thomas.mader@gmail.com"; };
  Zimmi48 = { name = "Théo Zimmermann"; email = "theo.zimmermann@univ-paris-diderot.fr"; };
  a1russell = { name = "Adam Russell"; email = "adamlr6+pub@gmail.com"; };
  aaronschif = { name = "Aaron Schif"; email = "aaronschif@gmail.com"; };
  abaldeau = { name = "Andreas Baldeau"; email = "andreas@baldeau.net"; };
  abbradar = { name = "Nikolay Amiantov"; email = "ab@fmap.me"; };
  abigailbuccaneer = { name = "Abigail Bunyan"; email = "abigailbuccaneer@gmail.com"; };
  aboseley = { name = "Adam Boseley"; email = "adam.boseley@gmail.com"; };
  abuibrahim = { name = "Ruslan Babayev"; email = "ruslan@babayev.com"; };
  acowley = { name = "Anthony Cowley"; email = "acowley@gmail.com"; };
  adelbertc = { name = "Adelbert Chang"; email = "adelbertc@gmail.com"; };
  adev = { name = "Adrien Devresse"; email = "adev@adev.name"; };
  adisbladis = { name = "Adam Hose"; email = "adis@blad.is"; };
  adnelson = { name = "Allen Nelson"; email = "ithinkican@gmail.com"; };
  adolfogc = { name = "Adolfo E. García Castro"; email = "adolfo.garcia.cr@gmail.com"; };
  aespinosa = { name = "Allan Espinosa"; email = "allan.espinosa@outlook.com"; };
  aflatter = { name = "Alexander Flatter"; email = "flatter@fastmail.fm"; };
  afldcr = { name = "James Alexander Feldman-Crough"; email = "alex@fldcr.com"; };
  aforemny = { name = "Alexander Foremny"; email = "alexanderforemny@googlemail.com"; };
  afranchuk = { name = "Alex Franchuk"; email = "alex.franchuk@gmail.com"; };
  aherrmann = { name = "Andreas Herrmann"; email = "andreash87@gmx.ch"; };
  ahmedtd = { name = "Taahir Ahmed"; email = "ahmed.taahir@gmail.com"; };
  ak = { name = "Alexander Kjeldaas"; email = "ak@formalprivacy.com"; };
  akaWolf = { name = "Artjom Vejsel"; email = "akawolf0@gmail.com"; };
  akc = { name = "Anders Claesson"; email = "akc@akc.is"; };
  alexvorobiev = { name = "Alex Vorobiev"; email = "alexander.vorobiev@gmail.com"; };
  algorith = { name = "Dries Van Daele"; email = "dries_van_daele@telenet.be"; };
  alibabzo = { name = "Alistair Bill"; email = "alistair.bill@gmail.com"; };
  all = { name = "Nix Committers"; email = "nix-commits@lists.science.uu.nl"; };
  alunduil = { name = "Alex Brandt"; email = "alunduil@alunduil.com"; };
  ambrop72 = { name = "Ambroz Bizjak"; email = "ambrop7@gmail.com"; };
  amiddelk = { name = "Arie Middelkoop"; email = "amiddelk@gmail.com"; };
  amiloradovsky = { name = "Andrew Miloradovsky"; email = "miloradovsky@gmail.com"; };
  amorsillo = { name = "Andrew Morsillo"; email = "andrew.morsillo@gmail.com"; };
  anderspapitto = { name = "Anders Papitto"; email = "anderspapitto@gmail.com"; };
  andir = { name = "Andreas Rammhold"; email = "andreas@rammhold.de"; };
  andres = { name = "Andres Loeh"; email = "ksnixos@andres-loeh.de"; };
  andrestylianos = { name = "Andre S. Ramos"; email = "andre.stylianos@gmail.com"; };
  andrewrk = { name = "Andrew Kelley"; email = "superjoe30@gmail.com"; };
  andsild = { name = "Anders Sildnes"; email = "andsild@gmail.com"; };
  aneeshusa = { name = "Aneesh Agrawal"; email = "aneeshusa@gmail.com"; };
  ankhers = { name = "Justin Wood"; email = "justin.k.wood@gmail.com"; };
  antono = { name = "Antono Vasiljev"; email = "self@antono.info"; };
  antonxy = { name = "Anton Schirg"; email = "anton.schirg@posteo.de"; };
  apeschar = { name = "Albert Peschar"; email = "albert@peschar.net"; };
  apeyroux = { name = "Alexandre Peyroux"; email = "alex@px.io"; };
  ardumont = { name = "Antoine R. Dumont"; email = "eniotna.t@gmail.com"; };
  aristid = { name = "Aristid Breitkreuz"; email = "aristidb@gmail.com"; };
  arobyn = { name = "Alexei Robyn"; email = "shados@shados.net"; };
  artuuge = { name = "Artur E. Ruuge"; email = "artuuge@gmail.com"; };
  ashalkhakov = { name = "Artyom Shalkhakov"; email = "artyom.shalkhakov@gmail.com"; };
  aske = { name = "Kirill Boltaev"; email = "aske@fmap.me"; };
  asppsa = { name = "Alastair Pharo"; email = "asppsa@gmail.com"; };
  astsmtl = { name = "Alexander Tsamutali"; email = "astsmtl@yandex.ru"; };
  asymmetric = { name = "Lorenzo Manacorda"; email = "lorenzo@mailbox.org"; };
  aszlig = { name = "aszlig"; email = "aszlig@nix.build"; };
  auntie = { name = "Jonathan Glines"; email = "auntieNeo@gmail.com"; };
  avnik = { name = "Alexander V. Nikolaev"; email = "avn@avnik.info"; };
  aycanirican = { name = "Aycan iRiCAN"; email = "iricanaycan@gmail.com"; };
  bachp = { name = "Pascal Bach"; email = "pascal.bach@nextrem.ch"; };
  badi = { name = "Badi' Abdul-Wahid"; email = "abdulwahidc@gmail.com"; };
  balajisivaraman = { name = "Balaji Sivaraman"; email = "sivaraman.balaji@gmail.com"; };
  barrucadu = { name = "Michael Walker"; email = "mike@barrucadu.co.uk"; };
  basvandijk = { name = "Bas van Dijk"; email = "v.dijk.bas@gmail.com"; };
  bcarrell = { name = "Brandon Carrell"; email = "brandoncarrell@gmail.com"; };
  bcdarwin = { name = "Ben Darwin"; email = "bcdarwin@gmail.com"; };
  bdimcheff = { name = "Brandon Dimcheff"; email = "brandon@dimcheff.com"; };
  bendlas = { name = "Herwig Hochleitner"; email = "herwig@bendlas.net"; };
  benley = { name = "Benjamin Staffin"; email = "benley@gmail.com"; };
  bennofs = { name = "Benno Fünfstück"; email = "benno.fuenfstueck@gmail.com"; };
  benwbooth = { name = "Ben Booth"; email = "benwbooth@gmail.com"; };
  berdario = { name = "Dario Bertini"; email = "berdario@gmail.com"; };
  bergey = { name = "Daniel Bergey"; email = "bergey@teallabs.org"; };
  bhipple = { name = "Benjamin Hipple"; email = "bhipple@protonmail.com"; };
  binarin = { name = "Alexey Lebedeff"; email = "binarin@binarin.ru"; };
  bjg = { name = "Brian Gough"; email = "bjg@gnu.org"; };
  bjornfor = { name = "Bjørn Forsman"; email = "bjorn.forsman@gmail.com"; };
  bluescreen303 = { name = "Mathijs Kwik"; email = "mathijs@bluescreen303.nl"; };
  bobakker = { name = "Bo Bakker"; email = "bobakk3r@gmail.com"; };
  bobvanderlinden = { name = "Bob van der Linden"; email = "bobvanderlinden@gmail.com"; };
  bodil = { name = "Bodil Stokke"; email = "nix@bodil.org"; };
  boothead = { name = "Ben Ford"; email = "ben@perurbis.com"; };
  bosu = { name = "Boris Sukholitko"; email = "boriss@gmail.com"; };
  bradediger = { name = "Brad Ediger"; email = "brad@bradediger.com"; };
  bramd = { name = "Bram Duvigneau"; email = "bram@bramd.nl"; };
  bstrik = { name = "Berno Strik"; email = "dutchman55@gmx.com"; };
  bzizou = { name = "Bruno Bzeznik"; email = "Bruno@bzizou.net"; };
  c0bw3b = { name = "Renaud"; email = "c0bw3b@gmail.com"; };
  c0dehero = { name = "CodeHero"; email = "codehero@nerdpol.ch"; };
  calbrecht = { name = "Christian Albrecht"; email = "christian.albrecht@mayflower.de"; };
  calrama = { name = "Moritz Maxeiner"; email = "moritz@ucworks.org"; };
  calvertvl = { name = "Victor Calvert"; email = "calvertvl@gmail.com"; };
  campadrenalin = { name = "Philip Horger"; email = "campadrenalin@gmail.com"; };
  canndrew = { name = "Andrew Cann"; email = "shum@canndrew.org"; };
  carlsverre = { name = "Carl Sverre"; email = "accounts@carlsverre.com"; };
  casey = { name = "Casey Rodarmor"; email = "casey@rodarmor.net"; };
  catern = { name = "Spencer Baugh"; email = "sbaugh@catern.com"; };
  caugner = { name = "Claas Augner"; email = "nixos@caugner.de"; };
  cdepillabout = { name = "Dennis Gosnell"; email = "cdep.illabout@gmail.com"; };
  cfouche = { name = "Chaddaï Fouché"; email = "chaddai.fouche@gmail.com"; };
  changlinli = { name = "Changlin Li"; email = "mail@changlinli.com"; };
  chaoflow = { name = "Florian Friesdorf"; email = "flo@chaoflow.net"; };
  chattered = { name = "Phil Scott"; email = "me@philscotted.com"; };
  choochootrain = { name = "Hurshal Patel"; email = "hurshal@imap.cc"; };
  chpatrick = { name = "Patrick Chilton"; email = "chpatrick@gmail.com"; };
  chris-martin = { name = "Chris Martin"; email = "ch.martin@gmail.com"; };
  chrisjefferson = { name = "Christopher Jefferson"; email = "chris@bubblescope.net"; };
  chrisrosset = { name = "Christopher Rosset"; email = "chris@rosset.org.uk"; };
  christopherpoole = { name = "Christopher Mark Poole"; email = "mail@christopherpoole.net"; };
  ciil = { name = "Simon Lackerbauer"; email = "simon@lackerbauer.com"; };
  ckampka = { name = "Christian Kampka"; email = "christian@kampka.net"; };
  ckauhaus = { name = "Christian Kauhaus"; email = "christian@kauhaus.de"; };
  cko = { name = "Christine Koppelt"; email = "christine.koppelt@gmail.com"; };
  cleverca22 = { name = "Michael Bishop"; email = "cleverca22@gmail.com"; };
  cmcdragonkai = { name = "Roger Qiu"; email = "roger.qiu@matrix.ai"; };
  cmfwyp = { name = "cmfwyp"; email = "cmfwyp@riseup.net"; };
  cobbal = { name = "Andrew Cobb"; email = "andrew.cobb@gmail.com"; };
  coconnor = { name = "Corey O'Connor"; email = "coreyoconnor@gmail.com"; };
  codsl = { name = "codsl"; email = "codsl@riseup.net"; };
  codyopel = { name = "Cody Opel"; email = "codyopel@gmail.com"; };
  colemickens = { name = "Cole Mickens"; email = "cole.mickens@gmail.com"; };
  colescott = { name = "Cole Scott"; email = "colescottsf@gmail.com"; };
  copumpkin = { name = "Dan Peebles"; email = "pumpkingod@gmail.com"; };
  corngood = { name = "David McFarland"; email = "corngood@gmail.com"; };
  coroa = { name = "Jonas Hörsch"; email = "jonas@chaoflow.net"; };
  couchemar = { name = "Andrey Pavlov"; email = "couchemar@yandex.ru"; };
  cpages = { name = "Carles Pagès"; email = "page@ruiec.cat"; };
  cransom = { name = "Casey Ransom"; email = "cransom@hubns.net"; };
  cryptix = { name = "Henry Bubert"; email = "cryptix@riseup.net"; };
  csingley = { name = "Christopher Singley"; email = "csingley@gmail.com"; };
  cstrahan = { name = "Charles Strahan"; email = "charles@cstrahan.com"; };
  cwoac = { name = "Oliver Matthews"; email = "oliver@codersoffortune.net"; };
  danbst = { name = "Danylo Hlynskyi"; email = "abcz2.uprola@gmail.com"; };
  dancek = { name = "Hannu Hartikainen"; email = "hannu.hartikainen@gmail.com"; };
  danharaj = { name = "Dan Haraj"; email = "dan@obsidian.systems"; };
  danielfullmer = { name = "Daniel Fullmer"; email = "danielrf12@gmail.com"; };
  dasuxullebt = { name = "Christoph-Simon Senjak"; email = "christoph.senjak@googlemail.com"; };
  david50407 = { name = "David Kuo"; email = "me@davy.tw"; };
  davidak = { name = "David Kleuker"; email = "post@davidak.de"; };
  davidrusu = { name = "David Rusu"; email = "davidrusu.me@gmail.com"; };
  davorb = { name = "Davor Babic"; email = "davor@davor.se"; };
  dbohdan = { name = "Danyil Bohdan"; email = "danyil.bohdan@gmail.com"; };
  dbrock = { name = "Daniel Brockman"; email = "daniel@brockman.se"; };
  deepfire = { name = "Kosyrev Serge"; email = "_deepfire@feelingofgreen.ru"; };
  demin-dmitriy = { name = "Dmitriy Demin"; email = "demindf@gmail.com"; };
  derchris = { name = "Christian Gerbrandt"; email = "derchris@me.com"; };
  dermetfan = { name = "Robin Stumm"; email = "serverkorken@gmail.com"; };
  desiderius = { name = "Didier J. Devroye"; email = "didier@devroye.name"; };
  devhell = { name = "devhell"; email = "\"^\"@regexmail.net"; };
  dezgeg = { name = "Tuomas Tynkkynen"; email = "tuomas.tynkkynen@iki.fi"; };
  dfordivam = { name = "Divam"; email = "dfordivam+nixpkgs@gmail.com"; };
  dfoxfranke = { name = "Daniel Fox Franke"; email = "dfoxfranke@gmail.com"; };
  dgonyeo = { name = "Derek Gonyeo"; email = "derek@gonyeo.com"; };
  dipinhora = { name = "Dipin Hora"; email = "dipinhora+github@gmail.com"; };
  disassembler = { name = "Samuel Leathers"; email = "disasm@gmail.com"; };
  dizfer = { name = "David Izquierdo"; email = "david@izquierdofernandez.com"; };
  dmalikov = { name = "Dmitry Malikov"; email = "malikov.d.y@gmail.com"; };
  dmjio = { name = "David Johnson"; email = "djohnson.m@gmail.com"; };
  dochang = { name = "Desmond O. Chang"; email = "dochang@gmail.com"; };
  domenkozar = { name = "Domen Kozar"; email = "domen@dev.si"; };
  dotlambda = { name = "Robert Schütz"; email = "rschuetz17@gmail.com"; };
  doublec = { name = "Chris Double"; email = "chris.double@double.co.nz"; };
  dpaetzel = { name = "David Pätzel"; email = "david.a.paetzel@gmail.com"; };
  dpflug = { name = "David Pflug"; email = "david@pflug.email"; };
  drets = { name = "Dmytro Rets"; email = "dmitryrets@gmail.com"; };
  drewkett = { name = "Andrew Burkett"; email = "burkett.andrew@gmail.com"; };
  dsferruzza = { name = "David Sferruzza"; email = "david.sferruzza@gmail.com"; };
  dtzWill = { name = "Will Dietz"; email = "nix@wdtz.org"; };
  dupgit = { name = "Olivier Delhomme"; email = "olivier.delhomme@free.fr"; };
  dywedir = { name = "Vladyslav M."; email = "dywedir@protonmail.ch"; };
  e-user = { name = "Alexander Kahl"; email = "nixos@sodosopa.io"; };
  earldouglas = { name = "James Earl Douglas"; email = "james@earldouglas.com"; };
  ebzzry = { name = "Rommel Martinez"; email = "ebzzry@ebzzry.io"; };
  edanaher = { name = "Evan Danaher"; email = "nixos@edanaher.net"; };
  edef = { name = "edef"; email = "edef@edef.eu"; };
  ederoyd46 = { name = "Matthew Brown"; email = "matt@ederoyd.co.uk"; };
  eduarrrd = { name = "Eduard Bachmakov"; email = "e.bachmakov@gmail.com"; };
  edwtjo = { name = "Edward Tjörnhammar"; email = "ed@cflags.cc"; };
  eelco = { name = "Eelco Dolstra"; email = "eelco.dolstra@logicblox.com"; GitHub = "edolstra"; IRC = "niksnut"; };
  ehegnes = { name = "Eric Hegnes"; email = "eric.hegnes@gmail.com"; };
  ehmry = { name = "Emery Hemingway"; email = "emery@vfemail.net"; };
  eikek = { name = "Eike Kettner"; email = "eike.kettner@posteo.de"; };
  ekleog = { name = "Leo Gaspard"; email = "leo@gaspard.io"; };
  elasticdog = { name = "Aaron Bull Schaefer"; email = "aaron@elasticdog.com"; };
  eleanor = { name = "Dejan Lukan"; email = "dejan@proteansec.com"; };
  elijahcaine = { name = "Elijah Caine"; email = "elijahcainemv@gmail.com"; };
  elitak = { name = "Eric Litak"; email = "elitak@gmail.com"; };
  ellis = { name = "Ellis Whitehead"; email = "nixos@ellisw.net"; };
  eperuffo = { name = "Emanuele Peruffo"; email = "info@emanueleperuffo.com"; };
  epitrochoid = { name = "Mabry Cervin"; email = "mpcervin@uncg.edu"; };
  eqyiel = { name = "Ruben Maher"; email = "r@rkm.id.au"; };
  ericbmerritt = { name = "Eric Merritt"; email = "eric@afiniate.com"; };
  ericsagnes = { name = "Eric Sagnes"; email = "eric.sagnes@gmail.com"; };
  erictapen = { name = "Justin Humm"; email = "justin.humm@posteo.de"; };
  erikryb = { name = "Erik Rybakken"; email = "erik.rybakken@math.ntnu.no"; };
  ertes = { name = "Ertugrul Söylemez"; email = "esz@posteo.de"; };
  ethercrow = { name = "Dmitry Ivanov"; email = "ethercrow@gmail.com"; };
  etu = { name = "Elis Hirwing"; email = "elis@hirwing.se"; };
  exi = { name = "Reno Reckling"; email = "nixos@reckling.org"; };
  exlevan = { name = "Alexey Levan"; email = "exlevan@gmail.com"; };
  expipiplus1 = { name = "Joe Hermaszewski"; email = "nix@monoid.al"; };
  fadenb = { name = "Tristan Helmich"; email = "tristan.helmich+nixos@gmail.com"; };
  falsifian = { name = "James Cook"; email = "james.cook@utoronto.ca"; };
  fare = { name = "Francois-Rene Rideau"; email = "fahree@gmail.com"; };
  fgaz = { name = "Francesco Gazzetta"; email = "francygazz@gmail.com"; };
  flokli = { name = "Florian Klink"; email = "flokli@flokli.de"; };
  florianjacob = { name = "Florian Jacob"; email = "projects+nixos@florianjacob.de"; };
  flosse = { name = "Markus Kohlhase"; email = "mail@markus-kohlhase.de"; };
  fluffynukeit = { name = "Daniel Austin"; email = "dan@fluffynukeit.com"; };
  fmthoma = { name = "Franz Thoma"; email = "f.m.thoma@googlemail.com"; };
  forkk = { name = "Andrew Okin"; email = "forkk@forkk.net"; };
  fornever = { name = "Friedrich von Never"; email = "friedrich@fornever.me"; };
  fpletz = { name = "Franz Pletz"; email = "fpletz@fnordicwalking.de"; };
  fps = { name = "Florian Paul Schmidt"; email = "mista.tapas@gmx.net"; };
  fridh = { name = "Frederik Rietdijk"; email = "fridh@fridh.nl"; };
  frlan = { name = "Frank Lanitz"; email = "frank@frank.uvena.de"; };
  fro_ozen = { name = "fro_ozen"; email = "fro_ozen@gmx.de"; };
  ftrvxmtrx = { name = "Siarhei Zirukin"; email = "ftrvxmtrx@gmail.com"; };
  funfunctor = { name = "Edward O'Callaghan"; email = "eocallaghan@alterapraxis.com"; };
  fuuzetsu = { name = "Mateusz Kowalczyk"; email = "fuuzetsu@fuuzetsu.co.uk"; };
  fuzzy-id = { name = "Thomas Bach"; email = "hacking+nixos@babibo.de"; };
  fxfactorial = { name = "Edgar Aroutiounian"; email = "edgar.factorial@gmail.com"; };
  gabesoft = { name = "Gabriel Adomnicai"; email = "gabesoft@gmail.com"; };
  gal_bolle = { name = "Florent Becker"; email = "florent.becker@ens-lyon.org"; };
  garbas = { name = "Rok Garbas"; email = "rok@garbas.si"; };
  garrison = { name = "Jim Garrison"; email = "jim@garrison.cc"; };
  gavin = { name = "Gavin Rogers"; email = "gavin@praxeology.co.uk"; };
  gebner = { name = "Gabriel Ebner"; email = "gebner@gebner.org"; };
  geistesk = { name = "Alvar Penning"; email = "post@0x21.biz"; };
  georgewhewell = { name = "George Whewell"; email = "georgerw@gmail.com"; };
  gilligan = { name = "Tobias Pflug"; email = "tobias.pflug@gmail.com"; };
  giogadi = { name = "Luis G. Torres"; email = "lgtorres42@gmail.com"; };
  gleber = { name = "Gleb Peregud"; email = "gleber.p@gmail.com"; };
  glenns = { name = "Glenn Searby"; email = "glenn.searby@gmail.com"; };
  globin = { name = "Robin Gloster"; email = "mail@glob.in"; };
  gnidorah = { name = "Alex Ivanov"; email = "yourbestfriend@opmbx.org"; };
  goibhniu = { name = "Cillian de Róiste"; email = "cillian.deroiste@gmail.com"; };
  goodrone = { name = "Andrew Trachenko"; email = "goodrone@gmail.com"; };
  gpyh = { name = "Yacine Hmito"; email = "yacine.hmito@gmail.com"; };
  grahamc = { name = "Graham Christensen"; email = "graham@grahamc.com"; };
  grburst = { name = "Julius Elias"; email = "grburst@openmailbox.org"; };
  gridaphobe = { name = "Eric Seidel"; email = "eric@seidel.io"; };
  guibert = { name = "David Guibert"; email = "david.guibert@gmail.com"; };
  guibou = { name = "Guillaume Bouchard"; email = "guillaum.bouchard@gmail.com"; };
  guillaumekoenig = { name = "Guillaume Koenig"; email = "guillaume.edward.koenig@gmail.com"; };
  guyonvarch = { name = "Joris Guyonvarch"; email = "joris@guyonvarch.me"; };
  hakuch = { name = "Jesse Haber-Kucharsky"; email = "hakuch@gmail.com"; };
  hamhut1066 = { name = "Hamish Hutchings"; email = "github@hamhut1066.com"; };
  havvy = { name = "Ryan Scheel"; email = "ryan.havvy@gmail.com"; };
  hbunke = { name = "Hendrik Bunke"; email = "bunke.hendrik@gmail.com"; };
  hce = { name = "Hans-Christian Esperer"; email = "hc@hcesperer.org"; };
  hectorj = { name = "Hector Jusforgues"; email = "hector.jusforgues+nixos@gmail.com"; };
  hedning = { name = "Tor Hedin Brønner"; email = "torhedinbronner@gmail.com"; };
  heel = { name = "Sergii Paryzhskyi"; email = "parizhskiy@gmail.com"; };
  henrytill = { name = "Henry Till"; email = "henrytill@gmail.com"; };
  hhm = { name = "hhm"; email = "heehooman+nixpkgs@gmail.com"; };
  hinton = { name = "Tom Hinton"; email = "t@larkery.com"; };
  hodapp = { name = "Chris Hodapp"; email = "hodapp87@gmail.com"; };
  hrdinka = { name = "Christoph Hrdinka"; email = "c.nix@hrdinka.at"; };
  htr = { name = "Hugo Tavares Reis"; email = "hugo@linux.com"; };
  iand675 = { name = "Ian Duncan"; email = "ian@iankduncan.com"; };
  ianwookim = { name = "Ian-Woo Kim"; email = "ianwookim@gmail.com"; };
  iblech = { name = "Ingo Blechschmidt"; email = "iblech@speicherleck.de"; };
  igsha = { name = "Igor Sharonov"; email = "igor.sharonov@gmail.com"; };
  ikervagyok = { name = "Balázs Lengyel"; email = "ikervagyok@gmail.com"; };
  infinisil = { name = "Silvan Mosberger"; email = "infinisil@icloud.com"; };
  ironpinguin = { name = "Michele Catalano"; email = "michele@catalano.de"; };
  ivan-tkatchev = { name = "Ivan Tkatchev"; email = "tkatchev@gmail.com"; };
  ixmatus = { name = "Parnell Springmeyer"; email = "parnell@digitalmentat.com"; };
  j-keck = { name = "Jürgen Keck"; email = "jhyphenkeck@gmail.com"; };
  jagajaga = { name = "Arseniy Seroka"; email = "ars.seroka@gmail.com"; };
  jammerful = { name = "jammerful"; email = "jammerful@gmail.com"; };
  jansol = { name = "Jan Solanti"; email = "jan.solanti@paivola.fi"; };
  javaguirre = { name = "Javier Aguirre"; email = "contacto@javaguirre.net"; };
  jb55 = { name = "William Casarin"; email = "jb55@jb55.com"; };
  jbedo = { name = "Justin Bedő"; email = "cu@cua0.org"; };
  jcumming = { name = "Jack Cummings"; email = "jack@mudshark.org"; };
  jdagilliland = { name = "Jason Gilliland"; email = "jdagilliland@gmail.com"; };
  jefdaj = { name = "Jeffrey David Johnson"; email = "jefdaj@gmail.com"; };
  jensbin = { name = "Jens Binkert"; email = "jensbin@protonmail.com"; };
  jerith666 = { name = "Matt McHenry"; email = "github@matt.mchenryfamily.org"; };
  jfb = { name = "James Felix Black"; email = "james@yamtime.com"; };
  jfrankenau = { name = "Johannes Frankenau"; email = "johannes@frankenau.net"; };
  jgeerds = { name = "Jascha Geerds"; email = "jascha@jgeerds.name"; };
  jgertm = { name = "Tim Jaeger"; email = "jger.tm@gmail.com"; };
  jgillich = { name = "Jakob Gillich"; email = "jakob@gillich.me"; };
  jhhuh = { name = "Ji-Haeng Huh"; email = "jhhuh.note@gmail.com"; };
  jirkamarsik = { name = "Jirka Marsik"; email = "jiri.marsik89@gmail.com"; };
  jlesquembre = { name = "José Luis Lafuente"; email = "jl@lafuente.me"; };
  jluttine = { name = "Jaakko Luttinen"; email = "jaakko.luttinen@iki.fi"; };
  joachifm = { name = "Joachim Fasting"; email = "joachifm@fastmail.fm"; };
  joamaki = { name = "Jussi Maki"; email = "joamaki@gmail.com"; };
  joelmo = { name = "Joel Moberg"; email = "joel.moberg@gmail.com"; };
  joelteon = { name = "Joel Taylor"; email = "me@joelt.io"; };
  johbo = { name = "Johannes Bornhold"; email = "johannes@bornhold.name"; };
  johnmh = { name = "John M. Harris, Jr."; email = "johnmh@openblox.org"; };
  johnramsden = { name = "John Ramsden"; email = "johnramsden@riseup.net"; };
  joko = { name = "Ioannis Koutras"; email = "ioannis.koutras@gmail.com"; };
  jonafato = { name = "Jon Banafato"; email = "jon@jonafato.com"; };
  joncojonathan = { name = "Jonathan Haddock"; email = "joncojonathan@gmail.com"; };
  jpierre03 = { name = "Jean-Pierre PRUNARET"; email = "nix@prunetwork.fr"; };
  jpotier = { name = "Martin Potier"; email = "jpo.contributes.to.nixos@marvid.fr"; };
  jraygauthier = { name = "Raymond Gauthier"; email = "jraygauthier@gmail.com"; };
  jtojnar = { name = "Jan Tojnar"; email = "jtojnar@gmail.com"; };
  juliendehos = { name = "Julien Dehos"; email = "dehos@lisic.univ-littoral.fr"; };
  jwiegley = { name = "John Wiegley"; email = "johnw@newartisans.com"; };
  jwilberding = { name = "Jordan Wilberding"; email = "jwilberding@afiniate.com"; };
  jyp = { name = "Jean-Philippe Bernardy"; email = "jeanphilippe.bernardy@gmail.com"; };
  jzellner = { name = "Jeff Zellner"; email = "jeffz@eml.cc"; };
  kaiha = { name = "Kai Harries"; email = "kai.harries@gmail.com"; };
  kamilchm = { name = "Kamil Chmielewski"; email = "kamil.chm@gmail.com"; };
  kampfschlaefer = { name = "Arnold Krille"; email = "arnold@arnoldarts.de"; };
  karolchmist = { name = "karolchmist"; email = "info+nix@chmist.com"; };
  kentjames = { name = "James Kent"; email = "jameschristopherkent@gmail.com"; };
  kevincox = { name = "Kevin Cox"; email = "kevincox@kevincox.ca"; };
  khumba = { name = "Bryan Gardiner"; email = "bog@khumba.net"; };
  kierdavis = { name = "Kier Davis"; email = "kierdavis@gmail.com"; };
  kiloreux = { name = "Kiloreux Emperex"; email = "kiloreux@gmail.com"; };
  kini = { name = "Keshav Kini"; email = "keshav.kini@gmail.com"; };
  kkallio = { name = "Karn Kallio"; email = "tierpluspluslists@gmail.com"; };
  knedlsepp = { name = "Josef Kemetmüller"; email = "josef.kemetmueller@gmail.com"; };
  konimex = { name = "Muhammad Herdiansyah"; email = "herdiansyah@netc.eu"; };
  koral = { name = "Koral"; email = "koral@mailoo.org"; };
  kovirobi = { name = "Kovacsics Robert"; email = "kovirobi@gmail.com"; };
  kquick = { name = "Kevin Quick"; email = "quick@sparq.org"; };
  kragniz = { name = "Louis Taylor"; email = "louis@kragniz.eu"; };
  kristoff3r = { name = "Kristoffer Søholm"; email = "k.soeholm@gmail.com"; };
  ktosiek = { name = "Tomasz Kontusz"; email = "tomasz.kontusz@gmail.com"; };
  kuznero = { name = "Roman Kuznetsov"; email = "roman@kuznero.com"; };
  lassulus = { name = "Lassulus"; email = "lassulus@gmail.com"; };
  layus = { name = "Guillaume Maudoux"; email = "layus.on@gmail.com"; };
  ldesgoui = { name = "Lucas Desgouilles"; email = "ldesgoui@gmail.com"; };
  league = { name = "Christopher League"; email = "league@contrapunctus.net"; };
  lebastr = { name = "Alexander Lebedev"; email = "lebastr@gmail.com"; };
  leemachin = { name = "Lee Machin"; email = "me@mrl.ee"; };
  leenaars = { name = "Michiel Leenaars"; email = "ml.software@leenaa.rs"; };
  leonardoce = { name = "Leonardo Cecchi"; email = "leonardo.cecchi@gmail.com"; };
  lethalman = { name = "Luca Bruno"; email = "lucabru@src.gnome.org"; };
  lewo = { name = "Antoine Eiche"; email = "lewo@abesis.fr"; };
  lheckemann = { name = "Linus Heckemann"; email = "git@sphalerite.org"; };
  lhvwb = { name = "Nathaniel Baxter"; email = "nathaniel.baxter@gmail.com"; };
  lihop = { name = "Leroy Hopson"; email = "nixos@leroy.geek.nz"; };
  linquize = { name = "Linquize"; email = "linquize@yahoo.com.hk"; };
  linus = { name = "Linus Arver"; email = "linusarver@gmail.com"; };
  lluchs = { name = "Lukas Werling"; email = "lukas.werling@gmail.com"; };
  lnl7 = { name = "Daiderd Jordan"; email = "daiderd@gmail.com"; };
  lo1tuma = { name = "Mathias Schreck"; email = "schreck.mathias@gmail.com"; };
  loskutov = { name = "Ignat Loskutov"; email = "ignat.loskutov@gmail.com"; };
  lovek323 = { name = "Jason O'Conal"; email = "jason@oconal.id.au"; };
  lowfatcomputing = { name = "Andreas Wagner"; email = "andreas.wagner@lowfatcomputing.org"; };
  lsix = { name = "Lancelot SIX"; email = "lsix@lancelotsix.com"; };
  ltavard = { name = "Laure Tavard"; email = "laure.tavard@univ-grenoble-alpes.fr"; };
  lucas8 = { name = "Luc Chabassier"; email = "luc.linux@mailoo.org"; };
  ludo = { name = "Ludovic Courtès"; email = "ludo@gnu.org"; };
  lufia = { name = "Kyohei Kadota"; email = "lufia@lufia.org"; };
  luispedro = { name = "Luis Pedro Coelho"; email = "luis@luispedro.org"; };
  lukego = { name = "Luke Gorrie"; email = "luke@snabb.co"; };
  lw = { name = "Sergey Sofeychuk"; email = "lw@fmap.me"; };
  lyt = { name = "Tim Liou"; email = "wheatdoge@gmail.com"; };
  m3tti = { name = "Mathaeus Sander"; email = "mathaeus.peter.sander@gmail.com"; };
  ma27 = { name = "Maximilian Bosch"; email = "maximilian@mbosch.me"; };
  madjar = { name = "Georges Dubus"; email = "georges.dubus@compiletoi.net"; };
  magnetophon = { name = "Bart Brouns"; email = "bart@magnetophon.nl"; };
  mahe = { name = "Matthias Herrmann"; email = "matthias.mh.herrmann@gmail.com"; };
  makefu = { name = "Felix Richter"; email = "makefu@syntax-fehler.de"; };
  malyn = { name = "Michael Alyn Miller"; email = "malyn@strangeGizmo.com"; };
  manveru = { name = "Michael Fellinger"; email = "m.fellinger@gmail.com"; };
  marcweber = { name = "Marc Weber"; email = "marco-oweber@gmx.de"; };
  markWot = { name = "Markus Wotringer"; email = "markus@wotringer.de"; };
  markus1189 = { name = "Markus Hauck"; email = "markus1189@gmail.com"; };
  martijnvermaat = { name = "Martijn Vermaat"; email = "martijn@vermaat.name"; };
  martingms = { name = "Martin Gammelsæter"; email = "martin@mg.am"; };
  matejc = { name = "Matej Cotman"; email = "cotman.matej@gmail.com"; };
  mathnerd314 = { name = "Mathnerd314"; email = "mathnerd314.gph+hs@gmail.com"; };
  matthewbauer = { name = "Matthew Bauer"; email = "mjbauer95@gmail.com"; };
  matthiasbeyer = { name = "Matthias Beyer"; email = "mail@beyermatthias.de"; };
  maurer = { name = "Matthew Maurer"; email = "matthew.r.maurer+nix@gmail.com"; };
  mbakke = { name = "Marius Bakke"; email = "mbakke@fastmail.com"; };
  mbbx6spp = { name = "Susan Potter"; email = "me@susanpotter.net"; };
  mbe = { name = "Brandon Edens"; email = "brandonedens@gmail.com"; };
  mboes = { name = "Mathieu Boespflug"; email = "mboes@tweag.net"; };
  mbrgm = { name = "Marius Bergmann"; email = "marius@yeai.de"; };
  mcmtroffaes = { name = "Matthias C. M. Troffaes"; email = "matthias.troffaes@gmail.com"; };
  mdaiter = { name = "Matthew S. Daiter"; email = "mdaiter8121@gmail.com"; };
  meditans = { name = "Carlo Nucera"; email = "meditans@gmail.com"; };
  mehandes = { name = "Matt Deming"; email = "niewskici@gmail.com"; };
  meisternu = { name = "Matt Miemiec"; email = "meister@krutt.org"; };
  metabar = { name = "Celine Mercier"; email = "softs@metabarcoding.org"; };
  mgdelacroix = { name = "Miguel de la Cruz"; email = "mgdelacroix@gmail.com"; };
  mguentner = { name = "Maximilian Güntner"; email = "code@klandest.in"; };
  mic92 = { name = "Jörg Thalheim"; email = "joerg@thalheim.io"; };
  michaelpj = { name = "Michael Peyton Jones"; email = "michaelpj@gmail.com"; };
  michalrus = { name = "Michal Rus"; email = "m@michalrus.com"; };
  michelk = { name = "Michel Kuhlmann"; email = "michel@kuhlmanns.info"; };
  midchildan = { name = "midchildan"; email = "midchildan+nix@gmail.com"; };
  mikefaille = { name = "Michaël Faille"; email = "michael@faille.io"; };
  miltador = { name = "Vasiliy Solovey"; email = "miltador@yandex.ua"; };
  mimadrid = { name = "Miguel Madrid"; email = "mimadrid@ucm.es"; };
  mirdhyn = { name = "Merlin Gaillard"; email = "mirdhyn@gmail.com"; };
  mirrexagon = { name = "Andrew Abbott"; email = "mirrexagon@mirrexagon.com"; };
  mjanczyk = { name = "Marcin Janczyk"; email = "m@dragonvr.pl"; };
  mlieberman85 = { name = "Michael Lieberman"; email = "mlieberman85@gmail.com"; };
  modulistic = { name = "Pablo Costa"; email = "modulistic@gmail.com"; };
  mog = { name = "Matthew O'Gorman"; email = "mog-lists@rldn.net"; };
  montag451 = { name = "montag451"; email = "montag451@laposte.net"; };
  moosingin3space = { name = "Nathan Moos"; email = "moosingin3space@gmail.com"; };
  moretea = { name = "Maarten Hoogendoorn"; email = "maarten@moretea.nl"; };
  mornfall = { name = "Petr Ročkai"; email = "me@mornfall.net"; };
  mounium = { name = "Katona László"; email = "muoniurn@gmail.com"; };
  mpcsh = { name = "Mark Cohen"; email = "m@mpc.sh"; };
  mpscholten = { name = "Marc Scholten"; email = "marc@mpscholten.de"; };
  mpsyco = { name = "Francis St-Amour"; email = "fr.st-amour@gmail.com"; };
  msackman = { name = "Matthew Sackman"; email = "matthew@wellquite.org"; };
  mschristiansen = { name = "Mikkel Christiansen"; email = "mikkel@rheosystems.com"; };
  msteen = { name = "Matthijs Steen"; email = "emailmatthijs@gmail.com"; };
  mt-caret = { name = "Masayuki Takeda"; email = "mtakeda.enigsol@gmail.com"; };
  mtreskin = { name = "Max Treskin"; email = "zerthurd@gmail.com"; };
  mudri = { name = "James Wood"; email = "lamudri@gmail.com"; };
  muflax = { name = "Stefan Dorn"; email = "mail@muflax.com"; };
  myrl = { name = "Myrl Hex"; email = "myrl.0xf@gmail.com"; };
  namore = { name = "Roman Naumann"; email = "namor@hemio.de"; };
  nand0p = { name = "Fernando Jose Pando"; email = "nando@hex7.com"; };
  nathan-gs = { name = "Nathan Bijnens"; email = "nathan@nathan.gs"; };
  nckx = { name = "Tobias Geerinckx-Rice"; email = "github@tobias.gr"; };
  ndowens = { name = "Nathan Owens"; email = "ndowens04@gmail.com"; };
  neeasade = { name = "Nathan Isom"; email = "nathanisom27@gmail.com"; };
  nequissimus = { name = "Tim Steinbach"; email = "tim@nequissimus.com"; };
  nfjinjing = { name = "Jinjing Wang"; email = "nfjinjing@gmail.com"; };
  nh2 = { name = "Niklas Hambüchen"; email = "mail@nh2.me"; };
  nhooyr = { name = "Anmol Sethi"; email = "anmol@aubble.com"; };
  nickhu = { name = "Nick Hu"; email = "me@nickhu.co.uk"; };
  nicknovitski = { name = "Nick Novitski"; email = "nixpkgs@nicknovitski.com"; };
  nico202 = { name = "Nicolò Balzarotti"; email = "anothersms@gmail.com"; };
  nixy = { name = "Andrew R. M."; email = "nixy@nixy.moe"; };
  nocoolnametom = { name = "Tom Doggett"; email = "nocoolnametom@gmail.com"; };
  notthemessiah = { name = "Brian Cohen"; email = "brian.cohen.88@gmail.com"; };
  np = { name = "Nicolas Pouillard"; email = "np.nix@nicolaspouillard.fr"; };
  nslqqq = { name = "Nikita Mikhailov"; email = "nslqqq@gmail.com"; };
  nthorne = { name = "Niklas Thörne"; email = "notrupertthorne@gmail.com"; };
  nyarly = { name = "Judson Lester"; email = "nyarly@gmail.com"; };
  obadz = { name = "obadz"; email = "obadz-nixos@obadz.com"; };
  ocharles = { name = "Oliver Charles"; email = "ollie@ocharles.org.uk"; };
  odi = { name = "Oliver Dunkl"; email = "oliver.dunkl@gmail.com"; };
  offline = { name = "Jaka Hudoklin"; email = "jakahudoklin@gmail.com"; };
  oida = { name = "oida"; email = "oida@posteo.de"; };
  okasu = { name = "Okasu"; email = "oka.sux@gmail.com"; };
  olcai = { name = "Erik Timan"; email = "dev@timan.info"; };
  olejorgenb = { name = "Ole Jørgen Brønner"; email = "olejorgenb@yahoo.no"; };
  olynch = { name = "Owen Lynch"; email = "owen@olynch.me"; };
  orbekk = { name = "KJ Ørbekk"; email = "kjetil.orbekk@gmail.com"; };
  orbitz = { name = "Malcolm Matalka"; email = "mmatalka@gmail.com"; };
  orivej = { name = "Orivej Desh"; email = "orivej@gmx.fr"; };
  osener = { name = "Ozan Sener"; email = "ozan@ozansener.com"; };
  otwieracz = { name = "Slawomir Gonet"; email = "slawek@otwiera.cz"; };
  oxij = { name = "Jan Malakhovski"; email = "oxij@oxij.org"; };
  pSub = { name = "Pascal Wittmann"; email = "mail@pascal-wittmann.de"; };
  paholg = { name = "Paho Lurie-Gregg"; email = "paho@paholg.com"; };
  pakhfn = { name = "Fedor Pakhomov"; email = "pakhfn@gmail.com"; };
  palo = { name = "Ingolf Wanger"; email = "palipalo9@googlemail.com"; };
  panaeon = { name = "Vitalii Voloshyn"; email = "vitalii.voloshyn@gmail.com"; };
  paperdigits = { name = "Mica Semrick"; email = "mica@silentumbrella.com"; };
  pashev = { name = "Igor Pashev"; email = "pashev.igor@gmail.com"; };
  patternspandemic = { name = "Brad Christensen"; email = "patternspandemic@live.com"; };
  pawelpacana = { name = "Paweł Pacana"; email = "pawel.pacana@gmail.com"; };
  pbogdan = { name = "Piotr Bogdan"; email = "ppbogdan@gmail.com"; };
  periklis = { name = "Periklis Tsirakidis"; email = "theopompos@gmail.com"; };
  pesterhazy = { name = "Paulus Esterhazy"; email = "pesterhazy@gmail.com"; };
  peterhoeg = { name = "Peter Hoeg"; email = "peter@hoeg.com"; };
  peterromfeldhk = { name = "Peter Romfeld"; email = "peter.romfeld.hk@gmail.com"; };
  peti = { name = "Peter Simons"; email = "simons@cryp.to"; };
  philandstuff = { name = "Philip Potter"; email = "philip.g.potter@gmail.com"; };
  phile314 = { name = "Philipp Hausmann"; email = "nix@314.ch"; };
  phreedom = { name = "Evgeny Egorochkin"; email = "phreedom@yandex.ru"; };
  phunehehe = { name = "Hoang Xuan Phu"; email = "phunehehe@gmail.com"; };
  pierrer = { name = "Pierre Radermecker"; email = "pierrer@pi3r.be"; };
  pierron = { name = "Nicolas B. Pierron"; email = "nixos@nbp.name"; };
  piotr = { name = "Piotr Pietraszkiewicz"; email = "ppietrasa@gmail.com"; };
  pjbarnoy = { name = "Perry Barnoy"; email = "pjbarnoy@gmail.com"; };
  pjones = { name = "Peter Jones"; email = "pjones@devalot.com"; };
  pkmx = { name = "Chih-Mao Chen"; email = "pkmx.tw@gmail.com"; };
  plcplc = { name = "Philip Lykke Carlsen"; email = "plcplc@gmail.com"; };
  plumps = { name = "Maksim Bronsky"; email = "maks.bronsky@web.de"; };
  pmahoney = { name = "Patrick Mahoney"; email = "pat@polycrystal.org"; };
  pmiddend = { name = "Philipp Middendorf"; email = "pmidden@secure.mailbox.org"; };
  polyrod = { name = "Maurizio Di Pietro"; email = "dc1mdp@gmail.com"; };
  pradeepchhetri = { name = "Pradeep Chhetri"; email = "pradeep.chhetri89@gmail.com"; };
  prikhi = { name = "Pavan Rikhi"; email = "pavan.rikhi@gmail.com"; };
  primeos = { name = "Michael Weiss"; email = "dev.primeos@gmail.com"; };
  profpatsch = { name = "Profpatsch"; email = "mail@profpatsch.de"; };
  proglodyte = { name = "Proglodyte"; email = "proglodyte23@gmail.com"; };
  pshendry = { name = "Paul Hendry"; email = "paul@pshendry.com"; };
  psibi = { name = "Sibi"; email = "sibi@psibi.in"; };
  pstn = { name = "Philipp Steinpaß"; email = "philipp@xndr.de"; };
  puffnfresh = { name = "Brian McKenna"; email = "brian@brianmckenna.org"; };
  pxc = { name = "Patrick Callahan"; email = "patrick.callahan@latitudeengineering.com"; };
  qknight = { name = "Joachim Schiele"; email = "js@lastlog.de"; };
  ragge = { name = "Ragnar Dahlen"; email = "r.dahlen@gmail.com"; };
  ralith = { name = "Benjamin Saunders"; email = "ben.e.saunders@gmail.com"; };
  ramkromberg = { name = "Ram Kromberg"; email = "ramkromberg@mail.com"; };
  rardiol = { name = "Ricardo Ardissone"; email = "ricardo.ardissone@gmail.com"; };
  rasendubi = { name = "Alexey Shmalko"; email = "rasen.dubi@gmail.com"; };
  raskin = { name = "Michael Raskin"; email = "7c6f434c@mail.ru"; };
  ravloony = { name = "Tom Macdonald"; email = "ravloony@gmail.com"; };
  rbasso = { name = "Rafael Basso"; email = "rbasso@sharpgeeks.net"; };
  redbaron = { name = "Maxim Ivanov"; email = "ivanov.maxim@gmail.com"; };
  redvers = { name = "Redvers Davies"; email = "red@infect.me"; };
  refnil = { name = "Martin Lavoie"; email = "broemartino@gmail.com"; };
  regnat = { name = "Théophane Hufschmitt"; email = "regnat@regnat.ovh"; };
  relrod = { name = "Ricky Elrod"; email = "ricky@elrod.me"; };
  renzo = { name = "Renzo Carbonara"; email = "renzocarbonara@gmail.com"; };
  retrry = { name = "Tadas Barzdžius"; email = "retrry@gmail.com"; };
  rht = { name = "rht"; email = "rhtbot@protonmail.com"; };
  richardipsum = { name = "Richard Ipsum"; email = "richardipsum@fastmail.co.uk"; };
  rick68 = { name = "Wei-Ming Yang"; email = "rick68@gmail.com"; };
  rickynils = { name = "Rickard Nilsson"; email = "rickynils@gmail.com"; };
  ris = { name = "Robert Scott"; email = "code@humanleg.org.uk"; };
  rlupton20 = { name = "Richard Lupton"; email = "richard.lupton@gmail.com"; };
  rnhmjoj = { name = "Michele Guerini Rocco"; email = "micheleguerinirocco@me.com"; };
  rob = { name = "Rob Vermaas"; email = "rob.vermaas@gmail.com"; };
  robberer = { name = "Longrin Wischnewski"; email = "robberer@freakmail.de"; };
  robbinch = { name = "Robbin C."; email = "robbinch33@gmail.com"; };
  roberth = { name = "Robert Hensing"; email = "nixpkgs@roberthensing.nl"; };
  robertodr = { name = "Roberto Di Remigio"; email = "roberto.diremigio@gmail.com"; };
  robgssp = { name = "Rob Glossop"; email = "robgssp@gmail.com"; };
  roblabla = { name = "Robin Lambertz"; email = "robinlambertz+dev@gmail.com"; };
  roconnor = { name = "Russell O'Connor"; email = "roconnor@theorem.ca"; };
  romildo = { name = "José Romildo Malaquias"; email = "malaquias@gmail.com"; };
  rongcuid = { name = "Rongcui Dong"; email = "rongcuid@outlook.com"; };
  rszibele = { name = "Richard Szibele"; email = "richard@szibele.com"; };
  rtreffer = { name = "Rene Treffer"; email = "treffer+nixos@measite.de"; };
  rushmorem = { name = "Rushmore Mushambi"; email = "rushmore@webenchanter.com"; };
  rvl = { name = "Rodney Lorrimar"; email = "dev+nix@rodney.id.au"; };
  rvlander = { name = "Gaëtan André"; email = "rvlander@gaetanandre.eu"; };
  rvolosatovs = { name = "Roman Volosatovs"; email = "rvolosatovs@riseup.net"; };
  ryanartecona = { name = "Ryan Artecona"; email = "ryanartecona@gmail.com"; };
  ryansydnor = { name = "Ryan Sydnor"; email = "ryan.t.sydnor@gmail.com"; };
  ryantm = { name = "Ryan Mulligan"; email = "ryan@ryantm.com"; };
  rybern = { name = "Ryan Bernstein"; email = "ryan.bernstein@columbia.edu"; };
  rycee = { name = "Robert Helgesson"; email = "robert@rycee.net"; };
  ryneeverett = { name = "Ryne Everett"; email = "ryneeverett@gmail.com"; };
  rzetterberg = { name = "Richard Zetterberg"; email = "richard.zetterberg@gmail.com"; };
  s1lvester = { name = "Markus Silvester"; email = "s1lvester@bockhacker.me"; };
  samdroid-apps = { name = "Sam Parkinson"; email = "sam@sam.today"; };
  samuelrivas = { name = "Samuel Rivas"; email = "samuelrivas@gmail.com"; };
  sander = { name = "Sander van der Burg"; email = "s.vanderburg@tudelft.nl"; };
  sargon = { name = "Daniel Ehlers"; email = "danielehlers@mindeye.net"; };
  sauyon = { name = "Sauyon Lee"; email = "s@uyon.co"; };
  schmitthenner = { name = "Fabian Schmitthenner"; email = "development@schmitthenner.eu"; };
  schneefux = { name = "schneefux"; email = "schneefux+nixos_pkg@schneefux.xyz"; };
  schristo = { name = "Scott Christopher"; email = "schristopher@konputa.com"; };
  scolobb = { name = "Sergiu Ivanov"; email = "sivanov@colimite.fr"; };
  sdll = { name = "Sasha Illarionov"; email = "sasha.delly@gmail.com"; };
  sepi = { name = "Raffael Mancini"; email = "raffael@mancini.lu"; };
  seppeljordan = { name = "Sebastian Jordan"; email = "sebastian.jordan.mail@googlemail.com"; };
  shanemikel = { name = "Shane Pearlman"; email = "shanemikel1@gmail.com"; };
  shawndellysse = { name = "Shawn Dellysse"; email = "sdellysse@gmail.com"; };
  sheenobu = { name = "Sheena Artrip"; email = "sheena.artrip@gmail.com"; };
  sheganinans = { name = "Aistis Raulinaitis"; email = "sheganinans@gmail.com"; };
  shell = { name = "Shell Turner"; email = "cam.turn@gmail.com"; };
  shlevy = { name = "Shea Levy"; email = "shea@shealevy.com"; };
  siddharthist = { name = "Langston Barrett"; email = "langston.barrett@gmail.com"; };
  sifmelcara = { name = "Ming Chuan"; email = "ming@culpring.com"; };
  sigma = { name = "Yann Hodique"; email = "yann.hodique@gmail.com"; };
  simonvandel = { name = "Simon Vandel Sillesen"; email = "simon.vandel@gmail.com"; };
  sivteck = { name = "Sivaram Balakrishnan"; email = "sivaram1992@gmail.com"; };
  sjagoe = { name = "Simon Jagoe"; email = "simon@simonjagoe.com"; };
  sjmackenzie = { name = "Stewart Mackenzie"; email = "setori88@gmail.com"; };
  sjourdois = { name = "Stéphane ‘kwisatz’ Jourdois"; email = "sjourdois@gmail.com"; };
  skeidel = { name = "Sven Keidel"; email = "svenkeidel@gmail.com"; };
  skrzyp = { name = "Jakub Skrzypnik"; email = "jot.skrzyp@gmail.com"; };
  sleexyz = { name = "Sean Lee"; email = "freshdried@gmail.com"; };
  smironov = { name = "Sergey Mironov"; email = "grrwlf@gmail.com"; };
  snyh = { name = "Xia Bin"; email = "snyh@snyh.org"; };
  solson = { name = "Scott Olson"; email = "scott@solson.me"; };
  sorki = { name = "Richard Marko"; email = "srk@48.io"; };
  sorpaas = { name = "Wei Tang"; email = "hi@that.world"; };
  spacefrogg = { name = "Michael Raitza"; email = "spacefrogg-nixos@meterriblecrew.net"; };
  spencerjanssen = { name = "Spencer Janssen"; email = "spencerjanssen@gmail.com"; };
  spinus = { name = "Tomasz Czyż"; email = "tomasz.czyz@gmail.com"; };
  sprock = { name = "Roger Mason"; email = "rmason@mun.ca"; };
  spwhitt = { name = "Spencer Whitt"; email = "sw@swhitt.me"; };
  srhb = { name = "Sarah Brofeldt"; email = "sbrofeldt@gmail.com"; };
  stephenmw = { name = "Stephen Weinberg"; email = "stephen@q5comm.com"; };
  sternenseemann = { name = "Lukas Epple"; email = "post@lukasepple.de"; };
  stesie = { name = "Stefan Siegl"; email = "stesie@brokenpipe.de"; };
  steveej = { name = "Stefan Junker"; email = "mail@stefanjunker.de"; };
  stumoss = { name = "Stuart Moss"; email = "samoss@gmail.com"; };
  swarren83 = { name = "Shawn Warren"; email = "shawn.w.warren@gmail.com"; };
  swflint = { name = "Samuel W. Flint"; email = "swflint@flintfam.org"; };
  swistak35 = { name = "Rafał Łasocha"; email = "me@swistak35.com"; };
  symphorien = { name = "Guillaume Girol"; email = "symphorien_nixpkgs@xlumurb.eu"; };
  szczyp = { name = "Szczyp"; email = "qb@szczyp.com"; };
  sztupi = { name = "Attila Sztupak"; email = "attila.sztupak@gmail.com"; };
  taeer = { name = "Taeer Bar-Yam"; email = "taeer@necsi.edu"; };
  tailhook = { name = "Paul Colomiets"; email = "paul@colomiets.name"; };
  taketwo = { name = "Sergey Alexandrov"; email = "alexandrov88@gmail.com"; };
  takikawa = { name = "Asumu Takikawa"; email = "asumu@igalia.com"; };
  taktoa = { name = "Remy Goldschmidt"; email = "taktoa@gmail.com"; };
  taku0 = { name = "Takuo Yonezawa"; email = "mxxouy6x3m_github@tatapa.org"; };
  tari = { name = "Peter Marheine"; email = "peter@taricorp.net"; };
  tavyc = { name = "Octavian Cerna"; email = "octavian.cerna@gmail.com"; };
  teh = { name = "Tom Hunger"; email = "tehunger@gmail.com"; };
  telotortium = { name = "Robert Irelan"; email = "rirelan@gmail.com"; };
  teto = { name = "Matthieu Coudron"; email = "mcoudron@hotmail.com"; };
  tex = { name = "Milan Svoboda"; email = "milan.svoboda@centrum.cz"; };
  thall = { name = "Niclas Thall"; email = "niclas.thall@gmail.com"; };
  thammers = { name = "Tobias Hammerschmidt"; email = "jawr@gmx.de"; };
  the-kenny = { name = "Moritz Ulrich"; email = "moritz@tarn-vedra.de"; };
  theuni = { name = "Christian Theune"; email = "ct@flyingcircus.io"; };
  thoughtpolice = { name = "Austin Seipp"; email = "aseipp@pobox.com"; };
  timbertson = { name = "Tim Cuthbertson"; email = "tim@gfxmonk.net"; };
  timokau = { name = "Timo Kaufmann"; email = "timokau@zoho.com"; };
  titanous = { name = "Jonathan Rudenberg"; email = "jonathan@titanous.com"; };
  tnias = { name = "Philipp Bartsch"; email = "phil@grmr.de"; };
  tohl = { name = "Tomas Hlavaty"; email = "tom@logand.com"; };
  tokudan = { name = "Daniel Frank"; email = "git@danielfrank.net"; };
  tomberek = { name = "Thomas Bereknyei"; email = "tomberek@gmail.com"; };
  tomsmeets = { name = "Tom Smeets"; email = "tom@tsmeets.nl"; };
  travisbhartwell = { name = "Travis B. Hartwell"; email = "nafai@travishartwell.net"; };
  trevorj = { name = "Trevor Joynson"; email = "nix@trevor.joynson.io"; };
  trino = { name = "Hubert Mühlhans"; email = "muehlhans.hubert@ekodia.de"; };
  tstrobel = { name = "Thomas Strobel"; email = "4ZKTUB6TEP74PYJOPWIR013S2AV29YUBW5F9ZH2F4D5UMJUJ6S@hash.domains"; };
  ttuegel = { name = "Thomas Tuegel"; email = "ttuegel@mailbox.org"; };
  tv = { name = "Tomislav Viljetić"; email = "tv@shackspace.de"; };
  tvestelind = { name = "Tomas Vestelind"; email = "tomas.vestelind@fripost.org"; };
  tvorog = { name = "Marsel Zaripov"; email = "marszaripov@gmail.com"; };
  tweber = { name = "Thorsten Weber"; email = "tw+nixpkgs@360vier.de"; };
  twey = { name = "James ‘Twey’ Kay"; email = "twey@twey.co.uk"; };
  uralbash = { name = "Svintsov Dmitry"; email = "root@uralbash.ru"; };
  utdemir = { name = "Utku Demir"; email = "me@utdemir.com"; };
  uwap = { name = "uwap"; email = "me@uwap.name"; };
  vaibhavsagar = { name = "Vaibhav Sagar"; email = "vaibhavsagar@gmail.com"; };
  valeriangalliat = { name = "Valérian Galliat"; email = "val@codejam.info"; };
  vandenoever = { name = "Jos van den Oever"; email = "jos@vandenoever.info"; };
  vanschelven = { name = "Klaas van Schelven"; email = "klaas@vanschelven.com"; };
  vanzef = { name = "Ivan Solyankin"; email = "vanzef@gmail.com"; };
  vbgl = { name = "Vincent Laporte"; email = "Vincent.Laporte@gmail.com"; };
  vbmithr = { name = "Vincent Bernardoff"; email = "vb@luminar.eu.org"; };
  vcunat = { name = "Vladimír Čunát"; email = "vcunat@gmail.com"; };
  vdemeester = { name = "Vincent Demeester"; email = "vincent@sbr.pm"; };
  veprbl = { name = "Dmitry Kalinkin"; email = "veprbl@gmail.com"; };
  vifino = { name = "Adrian Pistol"; email = "vifino@tty.sh"; };
  vinymeuh = { name = "VinyMeuh"; email = "vinymeuh@gmail.com"; };
  viric = { name = "Lluís Batlle i Rossell"; email = "viric@viric.name"; };
  vizanto = { name = "Danny Wilson"; email = "danny@prime.vc"; };
  vklquevs = { name = "vklquevs"; email = "vklquevs@gmail.com"; };
  vlstill = { name = "Vladimír Štill"; email = "xstill@fi.muni.cz"; };
  vmandela = { name = "Venkateswara Rao Mandela"; email = "venkat.mandela@gmail.com"; };
  vmchale = { name = "Vanessa McHale"; email = "tmchale@wisc.edu"; };
  volhovm = { name = "Mikhail Volkhov"; email = "volhovm.cs@gmail.com"; };
  volth = { name = "Jaroslavas Pocepko"; email = "jaroslavas@volth.com"; };
  vozz = { name = "Oliver Hunt"; email = "oliver.huntuk@gmail.com"; };
  vrthra = { name = "Rahul Gopinath"; email = "rahul@gopinath.org"; };
  vyp = { name = "vyp"; email = "elisp.vim@gmail.com"; };
  wedens = { name = "wedens"; email = "kirill.wedens@gmail.com"; };
  willibutz = { name = "Willi Butz"; email = "willibutz@posteo.de"; };
  willtim = { name = "Tim Philip Williams"; email = "tim.williams.public@gmail.com"; };
  winden = { name = "Antonio Vargas Gonzalez"; email = "windenntw@gmail.com"; };
  wizeman = { name = "Ricardo M. Correia"; email = "rcorreia@wizy.org"; };
  wjlroe = { name = "William Roe"; email = "willroe@gmail.com"; };
  wkennington = { name = "William A. Kennington III"; email = "william@wkennington.com"; };
  wmertens = { name = "Wout Mertens"; email = "Wout.Mertens@gmail.com"; };
  woffs = { name = "Frank Doepper"; email = "github@woffs.de"; };
  womfoo = { name = "Kranium Gikos Mendoza"; email = "kranium@gikos.net"; };
  wscott = { name = "Wayne Scott"; email = "wsc9tt@gmail.com"; };
  wyvie = { name = "Elijah Rum"; email = "elijahrum@gmail.com"; };
  xnwdd = { name = "Guillermo NWDD"; email = "nwdd+nixos@no.team"; };
  xvapx = { name = "Marti Serra"; email = "marti.serra.coscollano@gmail.com"; };
  xwvvvvwx = { name = "David Terry"; email = "davidterry@posteo.de"; };
  xzfc = { name = "Albert Safin"; email = "xzfcpw@gmail.com"; };
  yarr = { name = "Dmitry V."; email = "savraz@gmail.com"; };
  yegortimoshenko = { name = "Yegor Timoshenko"; email = "yegortimoshenko@gmail.com"; };
  ylwghst = { name = "Burim Augustin Berisa"; email = "ylwghst@onionmail.info"; };
  yochai = { name = "Yochai"; email = "yochai@titat.info"; };
  yorickvp = { name = "Yorick van Pelt"; email = "yorickvanpelt@gmail.com"; };
  yuriaisaka = { name = "Yuri Aisaka"; email = "yuri.aisaka+nix@gmail.com"; };
  yurrriq = { name = "Eric Bailey"; email = "eric@ericb.me"; };
  z77z = { name = "Marco Maggesi"; email = "maggesi@math.unifi.it"; };
  zagy = { name = "Christian Zagrodnick"; email = "cz@flyingcircus.io"; };
  zalakain = { name = "Unai Zalakain"; email = "contact@unaizalakain.info"; };
  zarelit = { name = "David Costa"; email = "david@zarel.net"; };
  zauberpony = { name = "Elmar Athmer"; email = "elmar@athmer.org"; };
  zef = { name = "Zef Hemel"; email = "zef@zef.me"; };
  zimbatm = { name = "zimbatm"; email = "zimbatm@zimbatm.com"; };
  zohl = { name = "Al Zohali"; email = "zohl@fmap.me"; };
  zoomulator = { name = "Kim Simmons"; email = "zoomulator@gmail.com"; };
  zraexy = { name = "David Mell"; email = "zraexy@gmail.com"; };
  zx2c4 = { name = "Jason A. Donenfeld"; email = "Jason@zx2c4.com"; };
  zzamboni = { name = "Diego Zamboni"; email = "diego@zzamboni.org"; };
};

lib = import ./.;

addGitHub = maintainer: details:
              if !builtins.hasAttr "GitHub" details
              then details // { GitHub = maintainer; }
              else details;

addIRC = maintainer: details:
          if !builtins.hasAttr "IRC" details
          then details // { IRC = null; }
          else details;
in
lib.mapAttrs (maintainer: details: addGitHub maintainer (addIRC maintainer details)) maintainers
