query IssueCommentsFor($login:String!, $after:String, $pageSize:Int!) {
  user(login:$login) {
    ...issueCommentFields
  }
}

fragment issueCommentFields on User {
  issueComments(
    first: $pageSize, after: $after, orderBy: {
      field: UPDATED_AT,
      direction: DESC
    }){
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      updatedAt
      url
      repository {
        id
        # name
        # owner { login }
      }
    }
  }
}

## this file is used as a prelude to construct named queries, to fetch
## many users at once
