# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "gnome-dictionary-3.24.0";

  src = fetchurl {
    url = mirror://gnome/sources/gnome-dictionary/3.24/gnome-dictionary-3.24.0.tar.xz;
    sha256 = "41e7064a0cfab18e881a95ce9f1712ee5c9f426904b16f3bc04c35ebd1bbd9f2";
  };
}
