# This file is autogenerated! Run ./update.sh to regenerate.
{
  version = "20240312";
  revision = "20240312";
  sourceHash = "sha256-fDrnI7H87vG4OpcmjMcRTio01oHI0Z2KUfe3NNeY3JY=";
  outputHash = "sha256-GYmRaW6wsOR+pqeQDyGYUDh6HfEs+sEi5vQoBHEeX9I=";
}
