#! /bin/sh -e

url=$1
rev=$2
expHash=$3

hashType=$NIX_HASH_ALGO
if test -z "$hashType"; then
    hashType=md5
fi

if test -z "$url"; then
    echo "syntax: nix-prefetch-git URL [REVISION [EXPECTED-HASH]]" >&2
    exit 1
fi

# If the hash was given, a file with that hash may already be in the
# store.
if test -n "$expHash"; then
    finalPath=$(nix-store --print-fixed-path --recursive "$hashType" "$expHash" git-export)
    if ! nix-store --check-validity "$finalPath" 2> /dev/null; then
        finalPath=
    fi
    hash=$expHash
fi


# If we don't know the hash or a path with that hash doesn't exist,
# download the file and add it to the store.
if test -z "$finalPath"; then

    tmpPath=/tmp/git-checkout-tmp-$$
    tmpFile=$tmpPath/git-export
    mkdir $tmpPath

    trap "rm -rf $tmpPath" EXIT

    # Perform the checkout.
    git clone "$url" $tmpFile 1>&2
    if test -n "$rev"; then
      cd $tmpFile
      echo $tmpFile
      git checkout $rev 1>&2
    fi
    # Allow doing additional processing before .git removal
    eval "$NIX_PREFETCH_GIT_CHECKOUT_HOOK"
    if test "$NIX_PREFETCH_GIT_LEAVE_DOT_GIT" != 1
    then
	echo "removing \`.git'..."
	rm -rf .git
    fi

    # Compute the hash.
    hash=$(nix-hash --type $hashType $hashFormat $tmpFile)
    if ! test -n "$QUIET"; then echo "hash is $hash" >&2; fi

    # Add the downloaded file to the Nix store.
    finalPath=$(nix-store --add-fixed --recursive "$hashType" $tmpFile)

    if test -n "$expHash" -a "$expHash" != "$hash"; then
        echo "hash mismatch for URL \`$url'"
        exit 1
    fi
fi

if ! test -n "$QUIET"; then echo "path is $finalPath" >&2; fi

echo $hash

if test -n "$PRINT_PATH"; then
    echo $finalPath
fi
