#!/usr/bin/env bash
set -eu -o pipefail
HOARDER_LIB_PATH=
RELEASE=
NODE_ENV=production

[[ -d "$DATA_DIR" ]]	# Ensure DATA_DIR is defined and exists

export RELEASE NODE_ENV
exec "$HOARDER_LIB_PATH/node_modules/.bin/tsx" "$HOARDER_LIB_PATH/packages/db/migrate.ts" "$@"
