#! @bash@/bin/bash

PATH=@coreutils@/bin:$PATH

export FREENET_HOME="$HOME/.local/share/freenet"
if [ -n "$XDG_DATA_HOME" ]
  then export FREENET_HOME="$XDG_DATA_HOME/freenet"
fi

if [ ! -d $FREENET_HOME ]; then
  mkdir -p $FREENET_HOME
fi

cp -u @seednodes@ $FREENET_HOME/seednodes.fref
chmod u+rw $FREENET_HOME/seednodes.fref

cd $FREENET_HOME
@jre@/bin/java -cp @freenet@/share/freenet/bcprov-jdk15on-152.jar:@freenet@/share/freenet/freenet-ext.jar:@freenet@/share/freenet/freenet.jar -Xmx1024M freenet.node.NodeStarter
