diff -Nuar cryptokit-1.3/Makefile cryptokit-1.3.nixos/Makefile
--- cryptokit-1.3/Makefile	2005-04-20 15:19:54.000000000 +0200
+++ cryptokit-1.3.nixos/Makefile	2010-08-17 15:22:07.000000000 +0200
@@ -9,14 +9,13 @@
 
 # The directory containing the Zlib library (libz.a or libz.so)
 # Leave blank if you don't have Zlib.
-ZLIB_LIBDIR=/usr/lib
-#ZLIB_LIBDIR=/usr/lib64    # for x86-64 Linux
+ZLIB_LIBDIR=@ZLIB_LIBDIR@
 
 # The directory containing the Zlib header file (zlib.h)
-ZLIB_INCLUDE=/usr/include
+ZLIB_INCLUDE=@ZLIB_INCLUDE@
 
 # Where to install the library. By default: OCaml's standard library directory.
-INSTALLDIR=`$(OCAMLC) -where`
+INSTALLDIR=@INSTALLDIR@
 
 # Flags for the C compiler.
 CFLAGS=-O -I$(ZLIB_INCLUDE) $(ZLIB)
