<?xml version="1.0"?>
<KeyTextList>
<Item key="CNSrcOption_OptCas1">550 Sheet Drawer</Item>
<Item key="CNSrcOption_OptCas2">550 Sheet Drawer x 2</Item>
<Item key="CNSrcOption_OptCas3">550 Sheet Drawer x 3</Item>
<Item key="CNDraftMode">Draft Mode:</Item>
<Item key="CNDetectPaperSize">Detect Paper Size When 1-sided Printing is Set</Item>
<Item key="MediaType_CoatedPaper1">Coated Paper 1</Item>
<Item key="MediaType_CoatedPaper2">Coated Paper 2</Item>
<Item key="MediaType_CoatedPaper3">Coated Paper 3</Item>
<Item key="InputSlot_Manual">Multi-purpose Tray</Item>
<Item key="InputSlot_Cas1">Drawer 1</Item>
<Item key="InputSlot_Cas2">Drawer 2</Item>
<Item key="InputSlot_Cas3">Drawer 3</Item>
<Item key="InputSlot_Cas4">Drawer 4</Item>
<Item key="CNSpecialPrintMode">Special Print Mode: </Item>
<Item key="CNSpecialPrintMode_Settings1">Special Settings A1</Item>
<Item key="CNSpecialPrintMode_Settings2">Special Settings A2</Item>
<Item key="CNSpecialPrintMode_Settings3">Special Settings A5</Item>
<Item key="CNSpecialPrintMode_Settings4">Special Settings B4</Item>
<Item key="CNSpecialPrintMode_Settings5">Special Settings B5</Item>
<Item key="CNSpecialPrintMode_Settings6">Special Settings B6</Item>
<Item key="CNSpecialPrintMode_Settings7">Special Settings C1</Item>
<Item key="CNSpecialPrintMode_Settings8">Special Settings C2</Item>
<Item key="CNSpecialPrintMode_Settings9">Special Settings C3</Item>
<Item key="CNSpecialPrintMode_Settings10">Special Settings C4</Item>
<Item key="CNSpecialPrintMode_Settings11">Special Settings C7</Item>
<Item key="CNSpecialPrintMode_Settings12">Special Settings D1</Item>
<Item key="CNSpecialPrintMode_Settings13">Special Settings E1</Item>
<Item key="CNSpecialPrintMode_Settings14">Special Settings G2</Item>
<Item key="CNSpecialPrintMode_Settings15">Special Settings H1</Item>
<Item key="CNSpecialPrintMode_Settings16">Special Settings H7</Item>
<Item key="CNSpecialPrintMode_Settings17">Special Settings J2</Item>
<Item key="CNSpecialPrintMode_Service">Service Settings</Item>
<Item key="CNTonerDensity_1">-8 (Light)</Item>
<Item key="CNTonerDensity_2">-7 (Light)</Item>
<Item key="CNTonerDensity_3">-6 (Light)</Item>
<Item key="CNTonerDensity_4">-5 (Light)</Item>
<Item key="CNTonerDensity_5">-4 (Light)</Item>
<Item key="CNTonerDensity_6">-3 (Light)</Item>
<Item key="CNTonerDensity_7">-2 (Light)</Item>
<Item key="CNTonerDensity_8">-1 (Light)</Item>
<Item key="CNTonerDensity_9">0 (Standard)</Item>
<Item key="CNTonerDensity_10">1 (Dark)</Item>
<Item key="CNTonerDensity_11">2 (Dark)</Item>
<Item key="CNTonerDensity_12">3 (Dark)</Item>
<Item key="CNTonerDensity_13">4 (Dark)</Item>
<Item key="CNTonerDensity_14">5 (Dark)</Item>
<Item key="CNTonerDensity_15">6 (Dark)</Item>
<Item key="CNTonerDensity_16">7 (Dark)</Item>
<Item key="CNTonerDensity_17">8 (Dark)</Item>
<Item key="CNCTonerDensity_1">-8 (Light)</Item>
<Item key="CNCTonerDensity_2">-7 (Light)</Item>
<Item key="CNCTonerDensity_3">-6 (Light)</Item>
<Item key="CNCTonerDensity_4">-5 (Light)</Item>
<Item key="CNCTonerDensity_5">-4 (Light)</Item>
<Item key="CNCTonerDensity_6">-3 (Light)</Item>
<Item key="CNCTonerDensity_7">-2 (Light)</Item>
<Item key="CNCTonerDensity_8">-1 (Light)</Item>
<Item key="CNCTonerDensity_9">0 (Standard)</Item>
<Item key="CNCTonerDensity_10">1 (Dark)</Item>
<Item key="CNCTonerDensity_11">2 (Dark)</Item>
<Item key="CNCTonerDensity_12">3 (Dark)</Item>
<Item key="CNCTonerDensity_13">4 (Dark)</Item>
<Item key="CNCTonerDensity_14">5 (Dark)</Item>
<Item key="CNCTonerDensity_15">6 (Dark)</Item>
<Item key="CNCTonerDensity_16">7 (Dark)</Item>
<Item key="CNCTonerDensity_17">8 (Dark)</Item>
<Item key="CNMTonerDensity_1">-8 (Light)</Item>
<Item key="CNMTonerDensity_2">-7 (Light)</Item>
<Item key="CNMTonerDensity_3">-6 (Light)</Item>
<Item key="CNMTonerDensity_4">-5 (Light)</Item>
<Item key="CNMTonerDensity_5">-4 (Light)</Item>
<Item key="CNMTonerDensity_6">-3 (Light)</Item>
<Item key="CNMTonerDensity_7">-2 (Light)</Item>
<Item key="CNMTonerDensity_8">-1 (Light)</Item>
<Item key="CNMTonerDensity_9">0 (Standard)</Item>
<Item key="CNMTonerDensity_10">1 (Dark)</Item>
<Item key="CNMTonerDensity_11">2 (Dark)</Item>
<Item key="CNMTonerDensity_12">3 (Dark)</Item>
<Item key="CNMTonerDensity_13">4 (Dark)</Item>
<Item key="CNMTonerDensity_14">5 (Dark)</Item>
<Item key="CNMTonerDensity_15">6 (Dark)</Item>
<Item key="CNMTonerDensity_16">7 (Dark)</Item>
<Item key="CNMTonerDensity_17">8 (Dark)</Item>
<Item key="CNYTonerDensity_1">-8 (Light)</Item>
<Item key="CNYTonerDensity_2">-7 (Light)</Item>
<Item key="CNYTonerDensity_3">-6 (Light)</Item>
<Item key="CNYTonerDensity_4">-5 (Light)</Item>
<Item key="CNYTonerDensity_5">-4 (Light)</Item>
<Item key="CNYTonerDensity_6">-3 (Light)</Item>
<Item key="CNYTonerDensity_7">-2 (Light)</Item>
<Item key="CNYTonerDensity_8">-1 (Light)</Item>
<Item key="CNYTonerDensity_9">0 (Standard)</Item>
<Item key="CNYTonerDensity_10">1 (Dark)</Item>
<Item key="CNYTonerDensity_11">2 (Dark)</Item>
<Item key="CNYTonerDensity_12">3 (Dark)</Item>
<Item key="CNYTonerDensity_13">4 (Dark)</Item>
<Item key="CNYTonerDensity_14">5 (Dark)</Item>
<Item key="CNYTonerDensity_15">6 (Dark)</Item>
<Item key="CNYTonerDensity_16">7 (Dark)</Item>
<Item key="CNYTonerDensity_17">8 (Dark)</Item>
</KeyTextList>
