<?xml version="1.0"?>
<KeyTextList>
<Item key="CNSrcOption_OptCas1">550 Sheet Cassette</Item>
<Item key="CNSrcOption_OptCas2">550 Sheet Cassette x 2</Item>
<Item key="CNSrcOption_OptCas3">550 Sheet Cassette x 3</Item>
<Item key="CNDraftMode">Toner Save: </Item>
<Item key="CNDetectPaperSize">Detect Paper Size When 1-sided Printing is Set</Item>
<Item key="MediaType_CoatedPaper1">Coated Paper 1</Item>
<Item key="MediaType_CoatedPaper2">Coated Paper 2</Item>
<Item key="MediaType_CoatedPaper3">Coated Paper 3</Item>
<Item key="CNSpecialPrintMode">Special Print Mode: </Item>
<Item key="CNSpecialPrintMode_Settings1">Special Settings A1</Item>
<Item key="CNSpecialPrintMode_Settings2">Special Settings A2</Item>
<Item key="CNSpecialPrintMode_Settings3">Special Settings A5</Item>
<Item key="CNSpecialPrintMode_Settings4">Special Settings B4</Item>
<Item key="CNSpecialPrintMode_Settings5">Special Settings B5</Item>
<Item key="CNSpecialPrintMode_Settings6">Special Settings B6</Item>
<Item key="CNSpecialPrintMode_Settings7">Special Settings C1</Item>
<Item key="CNSpecialPrintMode_Settings8">Special Settings C2</Item>
<Item key="CNSpecialPrintMode_Settings9">Special Settings C3</Item>
<Item key="CNSpecialPrintMode_Settings10">Special Settings C4</Item>
<Item key="CNSpecialPrintMode_Settings11">Special Settings C7</Item>
<Item key="CNSpecialPrintMode_Settings12">Special Settings D1</Item>
<Item key="CNSpecialPrintMode_Settings13">Special Settings E1</Item>
<Item key="CNSpecialPrintMode_Settings14">Special Settings G2</Item>
<Item key="CNSpecialPrintMode_Settings15">Special Settings H1</Item>
<Item key="CNSpecialPrintMode_Settings16">Special Settings H7</Item>
<Item key="CNSpecialPrintMode_Settings17">Special Settings J2</Item>
<Item key="CNSpecialPrintMode_Service">Service Settings</Item>
</KeyTextList>
