<?xml version="1.0"?>
<KeyTextList>
<Item key="CNSrcOption_None">None </Item>
<Item key="CNSrcOption_OptCas1">250 Sheet Drawer</Item>
<Item key="CNSrcOption_OptCas2">250 Sheet Drawer x 2</Item>
<Item key="CNSrcOption_OptCas3">250 Sheet Drawer x 3</Item>
<Item key="Resolution_1200">1200 dpi</Item>
<Item key="Resolution_600">600 dpi</Item>
<Item key="Resolution_300">300 dpi</Item>
<Item key="CNOutputAdjustment_True">On</Item>
<Item key="CNOutputAdjustment_False">Off</Item>
<Item key="CNPrintImageAdjustment_Mode1">Mode 1</Item>
<Item key="CNPrintImageAdjustment_Mode2">Mode 2</Item>
<Item key="CNDraftMode_True">On</Item>
<Item key="CNDraftMode_False">Off</Item>
<Item key="CNCurlCorrection_None">Off</Item>
<Item key="CNCurlCorrection_Front">Front Side Correction(Minus Curl)</Item>
<Item key="CNCurlCorrection_Back">Back Side Correction(Plus Curl)</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode1">Mode 1</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode2">Mode 2</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode3">Mode 3</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode4">Mode 4</Item>
<Item key="CNSpecialPrintAdjustmentB_Off">Off</Item>
<Item key="CNSpecialPrintAdjustmentB_Mode1">Mode 1</Item>
<Item key="CNSpecialPrintAdjustmentB_Mode2">Mode 2</Item>
<Item key="CNSpecialPrintAdjustmentB_Mode3">Mode 3</Item>
<Item key="CNRevicePostcard_Off">Off </Item>
<Item key="CNRevicePostcard_Level1">Level 1</Item>
<Item key="CNRevicePostcard_Level2">Level 2</Item>
<Item key="CNRevicePostcard_Level3">Level 3</Item>
<Item key="CNTonerSaving_Auto">Printer Default</Item>
<Item key="CNTonerSaving_True">On</Item>
<Item key="CNTonerSaving_False">Off</Item>
<Item key="MediaType_Auto">Auto</Item>
<Item key="MediaType_PlainPaper">Plain Paper</Item>
<Item key="MediaType_PlainLPaper">Plain Paper L </Item>
<Item key="MediaType_PlainPaperL">Plain Paper L</Item>
<Item key="MediaType_HEAVY">Heavy Paper</Item>
<Item key="MediaType_HEAVY1">Heavy Paper 1</Item>
<Item key="MediaType_HEAVY2">Heavy Paper 2</Item>
<Item key="MediaType_HEAVY3">Heavy Paper 3</Item>
<Item key="MediaType_HEAVYL">Heavy Paper L</Item>
<Item key="MediaType_PlainHPaper">Plain Paper H </Item>
<Item key="MediaType_ThickPaperL">Heavy Paper L </Item>
<Item key="MediaType_ThickPaperH">Heavy Paper H</Item>
<Item key="MediaType_ohp">Transparency</Item>
<Item key="MediaType_ThickPaper">Heavy Paper </Item>
<Item key="MediaType_POSTCARD">Postcard</Item>
<Item key="MediaType_LABELS">Label</Item>
<Item key="MediaType_Postcard">Postcard</Item>
<Item key="MediaType_Envelope">Envelope</Item>
<Item key="MediaType_PostcardH">Postcard H</Item>
<Item key="MediaType_Postcard_L">Postcard L</Item>
<Item key="MediaType_ThickThickL">Heavy/HeavyL</Item>
<Item key="MediaType_CoatedPaper">Coated Paper</Item>
<Item key="MediaType_ROUGH">Rough Paper</Item>
<Item key="MediaType_ROUGH1">Rough Paper 1</Item>
<Item key="MediaType_ROUGH2">Rough Paper 2</Item>
<Item key="MediaType_EnvelopeL">Envelope L</Item>
<Item key="MediaType_EnvelopeH">Envelope H</Item>
<Item key="MediaType_COATED">Glossy Film</Item>
<Item key="CNFeedAFiveVertically_True">On </Item>
<Item key="CNFeedAFiveVertically_False">Off </Item>
<Item key="CNGlossyPlainPaperProc_True">On </Item>
<Item key="CNGlossyPlainPaperProc_False">Off </Item>
<Item key="InputSlot_Auto">Auto</Item>
<Item key="InputSlot_0">Auto </Item>
<Item key="InputSlot_Manual">Multi-purpose Tray </Item>
<Item key="InputSlot_Cas1">Cassette 1</Item>
<Item key="InputSlot_Cas2">Cassette 2</Item>
<Item key="InputSlot_Cas3">Cassette 3</Item>
<Item key="InputSlot_Cas4">Cassette 4</Item>
<Item key="CNSpecialSmooth_None">Printer Default</Item>
<Item key="CNSpecialSmooth_Mode1">Mode 1</Item>
<Item key="CNSpecialSmooth_Mode2">Mode 2</Item>
<Item key="CNSpecialSmooth_Mode3">Mode 3</Item>
<Item key="CNSpecialSmooth_Mode4">Mode 4</Item>
<Item key="CNSpecialSmooth_Mode5">Mode 5</Item>
<Item key="CNSpecialSmooth_Mode6">Mode 6</Item>
<Item key="CNSpecialPrintMode_Off">Off </Item>
<Item key="CNSpecialPrintMode_Settings1">Special Settings 1</Item>
<Item key="CNSpecialPrintMode_Settings2">Special Settings 2</Item>
<Item key="CNSpecialPrintMode_Settings3">Special Settings 3</Item>
<Item key="CNSpecialPrintMode_Settings4">Special Settings 4</Item>
<Item key="CNSpecialPrintMode_Settings5">Special Settings 5</Item>
<Item key="CNSpecialPrintMode_Settings6">Special Settings 6</Item>
<Item key="CNSpecialPrintMode_Settings7">Special Settings 7</Item>
<Item key="CNSpecialPrintMode_Settings8">Special Settings 8</Item>
<Item key="CNSpecialPrintMode_Settings9">Special Settings 9</Item>
<Item key="CNSpecialPrintMode_Settings10">Special Settings 10</Item>
<Item key="CNSpecialPrintMode_Settings11">Special Settings 11</Item>
<Item key="CNSpecialPrintMode_Settings12">Special Settings 12</Item>
<Item key="CNSpecialPrintMode_Settings13">Special Settings 13</Item>
<Item key="CNSpecialPrintMode_Settings14">Special Settings 14</Item>
<Item key="CNSpecialPrintMode_Settings15">Special Settings 15</Item>
<Item key="CNSpecialPrintingModeA_None">Off </Item>
<Item key="CNSpecialPrintingModeA_Settings1">Special Settings A5</Item>
<Item key="CNSpecialPrintingModeA_Settings2">Special Settings B5</Item>
<Item key="CNSpecialPrintingModeB_None">Off </Item>
<Item key="CNSpecialPrintingModeB_Settings1">Special Settings 1</Item>
<Item key="CNSpecialPrintingModeB_Settings2">Special Settings 2</Item>
<Item key="CNSpecialPrintAdjustmentA_Off">Off</Item>
<Item key="CNSpecialPrintAdjustmentA_None">Printer Default</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode1">Mode 1</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode2">Mode 2</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode3">Mode 3</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode4">Mode 4</Item>
<Item key="CNSpecialPrintAdjustmentB_Off">Off</Item>
<Item key="CNSpecialPrintAdjustmentB_Mode1">Mode 1</Item>
<Item key="CNSpecialPrintAdjustmentB_Mode2">Mode 2</Item>
<Item key="CNSpecialPrintAdjustmentB_Mode3">Mode 3</Item>
<Item key="CNWrinklesCorrectionOutput_Off">Off </Item>
<Item key="CNWrinklesCorrectionOutput_Level1">Level 1</Item>
<Item key="CNWrinklesCorrectionOutput_Level2">Level 2</Item>
<Item key="BindEdge_Left">Long Edge (Left)</Item>
<Item key="BindEdge_Right">Long Edge (Right)</Item>
<Item key="BindEdge_Top">Short Edge (Top)</Item>
<Item key="BindEdge_Bottom">Short Edge (Bottom)</Item>
<Item key="Collate_True">Collate </Item>
<Item key="Collate_False">Group</Item>
<Item key="Collate_Group">Group</Item>
<Item key="Collate_Staple">Staple</Item>
<Item key="Collate_StapleCollate">Staple &amp; Collate</Item>
<Item key="Collate_StapleGroup">Staple &amp; Group</Item>
<Item key="OutputBin_Auto">Auto</Item>
<Item key="OutputBin_Tray">Output Tray</Item>
<Item key="OutputBin_SubTray">Sub-output Tray</Item>
<Item key="CNColorMode_color">Color</Item>
<Item key="CNColorMode_mono">Black and White</Item>
<Item key="CNColorMode_Mono">Black and White</Item>
<Item key="CNColorMode_Color">Color</Item>
<Item key="CNColorMode_Auto">Auto Detect</Item>
<Item key="CNKeepGray_Always">Always</Item>
<Item key="CNKeepGray_Standard">Standard</Item>
<Item key="CNKeepGray_Never">Never</Item>
<Item key="CNSuperSmooth_None">Printer Default</Item>
<Item key="CNSuperSmooth_True">On</Item>
<Item key="CNSuperSmooth_False">Off</Item>
<Item key="CNColorHalftone_None">Printer Default</Item>
<Item key="CNColorHalftone_Resolution">Resolution</Item>
<Item key="CNColorHalftone_Gradation">Gradation</Item>
<Item key="CNColorHalftone_ColorTone">Color Tone</Item>
<Item key="CNColorHalftone_pattern1">Pattern 1</Item>
<Item key="CNColorHalftone_pattern2">Pattern 2</Item>
<Item key="CNHalftone_None">Printer Default</Item>
<Item key="CNHalftone_pattern1">Pattern 1</Item>
<Item key="CNHalftone_pattern2">Pattern 2</Item>
<Item key="CNHalftone_pattern3">Pattern 3</Item>
<Item key="CNHalftone_Resolution">Resolution</Item>
<Item key="CNHalftone_Gradation">Gradation</Item>
<Item key="CNHalftone_ColorTone">Color Tone</Item>
<Item key="CNHalftone_Off">None (Solid)</Item>
<Item key="CNTonerDensity_1">-7 (Light)</Item>
<Item key="CNTonerDensity_2">-6 (Light)</Item>
<Item key="CNTonerDensity_3">-5 (Light)</Item>
<Item key="CNTonerDensity_4">-4 (Light)</Item>
<Item key="CNTonerDensity_5">-3 (Light)</Item>
<Item key="CNTonerDensity_6">-2 (Light)</Item>
<Item key="CNTonerDensity_7">-1 (Light)</Item>
<Item key="CNTonerDensity_8">0 (Standard)</Item>
<Item key="CNTonerDensity_9">1 (Dark)</Item>
<Item key="CNTonerDensity_10">2 (Dark)</Item>
<Item key="CNTonerDensity_11">3 (Dark)</Item>
<Item key="CNTonerDensity_12">4 (Dark)</Item>
<Item key="CNTonerDensity_13">5 (Dark)</Item>
<Item key="CNTonerDensity_14">6 (Dark)</Item>
<Item key="CNTonerDensity_15">7 (Dark)</Item>
<Item key="CNTonerDensity_16">8 (Dark)</Item>
<Item key="CNCTonerDensity_1">-7 (Light)</Item>
<Item key="CNCTonerDensity_2">-6 (Light)</Item>
<Item key="CNCTonerDensity_3">-5 (Light)</Item>
<Item key="CNCTonerDensity_4">-4 (Light)</Item>
<Item key="CNCTonerDensity_5">-3 (Light)</Item>
<Item key="CNCTonerDensity_6">-2 (Light)</Item>
<Item key="CNCTonerDensity_7">-1 (Light)</Item>
<Item key="CNCTonerDensity_8">0 (Standard)</Item>
<Item key="CNCTonerDensity_9">1 (Dark)</Item>
<Item key="CNCTonerDensity_10">2 (Dark)</Item>
<Item key="CNCTonerDensity_11">3 (Dark)</Item>
<Item key="CNCTonerDensity_12">4 (Dark)</Item>
<Item key="CNCTonerDensity_13">5 (Dark)</Item>
<Item key="CNCTonerDensity_14">6 (Dark)</Item>
<Item key="CNCTonerDensity_15">7 (Dark)</Item>
<Item key="CNCTonerDensity_16">8 (Dark)</Item>
<Item key="CNMTonerDensity_1">-7 (Light)</Item>
<Item key="CNMTonerDensity_2">-6 (Light)</Item>
<Item key="CNMTonerDensity_3">-5 (Light)</Item>
<Item key="CNMTonerDensity_4">-4 (Light)</Item>
<Item key="CNMTonerDensity_5">-3 (Light)</Item>
<Item key="CNMTonerDensity_6">-2 (Light)</Item>
<Item key="CNMTonerDensity_7">-1 (Light)</Item>
<Item key="CNMTonerDensity_8">0 (Standard)</Item>
<Item key="CNMTonerDensity_9">1 (Dark)</Item>
<Item key="CNMTonerDensity_10">2 (Dark)</Item>
<Item key="CNMTonerDensity_11">3 (Dark)</Item>
<Item key="CNMTonerDensity_12">4 (Dark)</Item>
<Item key="CNMTonerDensity_13">5 (Dark)</Item>
<Item key="CNMTonerDensity_14">6 (Dark)</Item>
<Item key="CNMTonerDensity_15">7 (Dark)</Item>
<Item key="CNMTonerDensity_16">8 (Dark)</Item>
<Item key="CNYTonerDensity_1">-7 (Light)</Item>
<Item key="CNYTonerDensity_2">-6 (Light)</Item>
<Item key="CNYTonerDensity_3">-5 (Light)</Item>
<Item key="CNYTonerDensity_4">-4 (Light)</Item>
<Item key="CNYTonerDensity_5">-3 (Light)</Item>
<Item key="CNYTonerDensity_6">-2 (Light)</Item>
<Item key="CNYTonerDensity_7">-1 (Light)</Item>
<Item key="CNYTonerDensity_8">0 (Standard)</Item>
<Item key="CNYTonerDensity_9">1 (Dark)</Item>
<Item key="CNYTonerDensity_10">2 (Dark)</Item>
<Item key="CNYTonerDensity_11">3 (Dark)</Item>
<Item key="CNYTonerDensity_12">4 (Dark)</Item>
<Item key="CNYTonerDensity_13">5 (Dark)</Item>
<Item key="CNYTonerDensity_14">6 (Dark)</Item>
<Item key="CNYTonerDensity_15">7 (Dark)</Item>
<Item key="CNYTonerDensity_16">8 (Dark)</Item>
<Item key="CNFixingMode_None">Off</Item>
<Item key="CNFixingMode_Mode1">Mode 1</Item>
<Item key="CNFixingMode_Mode2">Mode 2</Item>
<Item key="CNFixingMode_Mode3">Mode 3</Item>
<Item key="CNFixingMode_Mode4">Mode 4</Item>
<Item key="PageSize_A4">A4</Item>
<Item key="PageSize_B5">B5</Item>
<Item key="PageSize_A5">A5</Item>
<Item key="PageSize_Letter">Letter</Item>
<Item key="PageSize_11x17">11x17</Item>
<Item key="PageSize_Ledger">11x17 </Item>
<Item key="PageSize_Statement">Statement</Item>
<Item key="PageSize_Legal">Legal</Item>
<Item key="PageSize_Executive">Executive</Item>
<Item key="PageSize_A6">A6</Item>
<Item key="PageSize_B4">B4</Item>
<Item key="PageSize_A3">A3</Item>
<Item key="PageSize_jenv_you2">Envelope YOUGATA 2</Item>
<Item key="PageSize_jenv_you4">Envelope YOUGATA 4</Item>
<Item key="PageSize_jenv_kaku2">Envelope KAKUGATA 2</Item>
<Item key="PageSize_Postcard">Postcard</Item>
<Item key="PageSize_16K">16K</Item>
<Item key="PageSize_dbl_postcard">Reply Postcard</Item>
<Item key="PageSize_4x_postcard">4 on 1 Postcard</Item>
<Item key="PageSize_jenv_you_chou3">Envelope YOUGATANAGA 3</Item>
<Item key="PageSize_jenv_kaku4">Envelope KAKUGATA 4</Item>
<Item key="PageSize_jenv_chou2">Envelope NAGAGATA 2</Item>
<Item key="PageSize_jenv_chou3">Envelope NAGAGATA 3</Item>
<Item key="PageSize_Index_3x5">Index Card</Item>
<Item key="PageSize_Envelope_C5">Envelope C5</Item>
<Item key="PageSize_Com10">Envelope COM10</Item>
<Item key="PageSize_12x18">12x18</Item>
<Item key="PageSize_Monarch">Envelope Monarch</Item>
<Item key="PageSize_dl_envelope">Envelope DL</Item>
<Item key="PageSize_Envelope_B5">Envelope B5</Item>
<Item key="PageSize_SRA3">SRA3</Item>
<Item key="PageSize_13x19">13x19</Item>
<Item key="PageSize_Foolscap">Foolscap</Item>
<Item key="PageSize_8K">8K</Item>
<Item key="BindEdge_L_Left">Long Edge (Top)</Item>
<Item key="BindEdge_L_Right">Long Edge (Bottom)</Item>
<Item key="BindEdge_L_Top">Short Edge (Right)</Item>
<Item key="BindEdge_L_Bottom">Short Edge (Left)</Item>
<Item key="BindEdge_R_Left">Long Edge (Right)</Item>
<Item key="BindEdge_R_Right">Long Edge (Left)</Item>
<Item key="BindEdge_R_Top">Short Edge (Bottom)</Item>
<Item key="BindEdge_R_Bottom">Short Edge (Top)</Item>
<Item key="BindEdge_RL_Left">Long Edge (Bottom)</Item>
<Item key="BindEdge_RL_Right">Long Edge (Top)</Item>
<Item key="BindEdge_RL_Top">Short Edge (Left)</Item>
<Item key="BindEdge_RL_Bottom">Short Edge (Right)</Item>
<Item key="number-up_1 Page per Sheet">1 Page per Sheet</Item>
<Item key="number-up_2 Pages per Sheet">2 Pages per Sheet</Item>
<Item key="number-up_4 Pages per Sheet">4 Pages per Sheet</Item>
<Item key="number-up_6 Pages per Sheet">6 Pages per Sheet</Item>
<Item key="number-up_9 Pages per Sheet">9 Pages per Sheet</Item>
<Item key="number-up_16 Pages per Sheet">16 Pages per Sheet</Item>
<Item key="CNPrintStyle_1-sided Printing">1-sided Printing</Item>
<Item key="CNPrintStyle_2-sided Printing">2-sided Printing</Item>
<Item key="GutterValue_d">&quot; (0 to %.1f)</Item>
<Item key="GutterValue">mm (0 to %d)</Item>
<Item key="BlackTonerDensity">Toner Density (Black):</Item>
<Item key="TonerDensity">Toner Density:</Item>
<Item key="Halftone">Halftones:</Item>
<Item key="BWHalftone">B &amp; W Halftones:</Item>
</KeyTextList>
