#!/usr/bin/env bash
set -eu -o pipefail

[[ -d "$DATA_DIR" ]]	# Ensure DATA_DIR is defined and exists

export RELEASE=@VERSION@
export NODE_ENV=production

exec @NODEJS@/bin/node  \
     "@KARAKEEP_LIB_PATH@"/apps/web/.next/standalone/apps/web/server.js
