# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "gnome-photos-3.22.0";

  src = fetchurl {
    url = mirror://gnome/sources/gnome-photos/3.22/gnome-photos-3.22.0.tar.xz;
    sha256 = "568329142855901a85f325ee014176e24f735b15a496842bcd31f5cb2615ba53";
  };
}
