# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "flyingcircus/nixos-15.09-x86_64"
  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
  end

  config.vm.synced_folder "../../../", "/root/nixpkgs"
  config.vm.network "private_network", ip: "192.168.50.4"

end
