# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "flyingcircus/nixos-15.09-x86_64"
  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
  end

  config.vm.synced_folder "../../../", "/root/nixos"

  config.vm.network "private_network", mac: "100000021225", ip: "192.168.12.146"
  config.vm.network "private_network", mac: "100000031225", ip: "192.168.13.146"

  config.vm.provision :nixos, :verbose => true, :inline => '
    { config, lib, pkgs, ... }:
    with config;
    {
      fcio.enc = {
        parameters = {
          interfaces = {
            fe = {
              bridged = false;
              mac = "10:00:00:02:12:25";
              networks = {
                "195.62.125.0/25" = [];
                "192.168.12.0/24" = ["192.168.12.146" "192.168.12.147"];
                "fd:248:101:62::/64" = [];
              };
              gateways = {
               "192.168.12.0/24" = "192.168.12.1";
               "fd:248:101:62::/64" = "fd:248:101:62::1";
              };
            };
            srv = {
              bridged = false;
              mac = "10:00:00:03:12:25";
              networks = {
                "192.168.13.0/24" = ["192.168.13.146"];
                "195.62.125.128/25" = [];
                "195.62.126.128/25" = [];
                "fd:248:101:63::/64" = ["fd:248:101:63::110a"];
              };
              gateways = {
                "fd:248:101:63::/64" = "fd:248:101:63::1";
                "192.168.13.0/24" = "192.168.13.1";
              };
            };
          };
        };
      };
    }
'
end
