# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "flyingcircus/nixos-15.09-x86_64"
  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
  end

  config.vm.synced_folder "../../../", "/root/nixpkgs"

  config.vm.network "private_network", mac: "020000021225", ip: "192.168.12.146"
  config.vm.network "private_network", mac: "020000031225", ip: "192.168.13.146"

  config.vm.provision :shell, :inline => <<SCRIPT
    cp /root/nixpkgs/nixos/modules/flyingcircus/vagrant-provision.nix /etc/nixos/local.nix
    fc-manage --dev

SCRIPT

end
