diff -rc procps-orig/Makefile procps-3.2.4/Makefile
*** procps-orig/Makefile	2004-10-10 23:31:12.000000000 +0200
--- procps-3.2.4/Makefile	2005-01-21 19:33:49.700437229 +0100
***************
*** 24,47 ****
  ############ vars
  
  # so you can disable them or choose alternates
! ldconfig := ldconfig
  ln_f     := ln -f
  ln_sf    := ln -sf
! install  := install -D --owner 0 --group 0
  
  # Lame x86-64 /lib64 and /usr/lib64 abomination:
  lib64    := lib$(shell [ -d /lib64 ] && echo 64)
  
! usr/bin                  := $(DESTDIR)/usr/bin/
  bin                      := $(DESTDIR)/bin/
  sbin                     := $(DESTDIR)/sbin/
! usr/proc/bin             := $(DESTDIR)/usr/bin/
! man1                     := $(DESTDIR)/usr/share/man/man1/
! man5                     := $(DESTDIR)/usr/share/man/man5/
! man8                     := $(DESTDIR)/usr/share/man/man8/
! lib                      := $(DESTDIR)/$(lib64)/
! usr/lib                  := $(DESTDIR)/usr/$(lib64)/
! usr/include              := $(DESTDIR)/usr/include/
  
  #SKIP     := $(bin)kill $(man1)kill.1
  
--- 24,47 ----
  ############ vars
  
  # so you can disable them or choose alternates
! ldconfig := true
  ln_f     := ln -f
  ln_sf    := ln -sf
! install  := install -D
  
  # Lame x86-64 /lib64 and /usr/lib64 abomination:
  lib64    := lib$(shell [ -d /lib64 ] && echo 64)
  
! usr/bin                  := $(DESTDIR)/bin/
  bin                      := $(DESTDIR)/bin/
  sbin                     := $(DESTDIR)/sbin/
! usr/proc/bin             := $(DESTDIR)/bin/
! man1                     := $(DESTDIR)/share/man/man1/
! man5                     := $(DESTDIR)/share/man/man5/
! man8                     := $(DESTDIR)/share/man/man8/
! lib                      := $(DESTDIR)/lib/
! usr/lib                  := $(DESTDIR)/lib/
! usr/include              := $(DESTDIR)/include/
  
  #SKIP     := $(bin)kill $(man1)kill.1
  
***************
*** 71,77 ****
  
  # Preprocessor flags.
  PKG_CPPFLAGS := -D_GNU_SOURCE -I proc
! CPPFLAGS     := -I/usr/include/ncurses
  ALL_CPPFLAGS := $(PKG_CPPFLAGS) $(CPPFLAGS)
  
  # Left out -Wconversion due to noise in glibc headers.
--- 71,77 ----
  
  # Preprocessor flags.
  PKG_CPPFLAGS := -D_GNU_SOURCE -I proc
! CPPFLAGS     := 
  ALL_CPPFLAGS := $(PKG_CPPFLAGS) $(CPPFLAGS)
  
  # Left out -Wconversion due to noise in glibc headers.
