source "https://rubygems.org"

gem "rails", "~> 5.2.0"
gem "pg", "< 1" # < 1 for Debian 7 and CentOS 6 builds
gem "pghero" #, git: "https://github.com/ankane/pghero.git"
gem "pg_query"
gem "aws-sdk-cloudwatch"
gem "puma"
gem "activerecord-nulldb-adapter", require: false
gem "tzinfo-data"
