# DO NOT EDIT. This file is generated by update.sh
{ fetchFromGitHub }: {

  version = "5.9.2";

  cmake = fetchFromGitHub {
    owner = "KitWare";
    repo = "CMake";
    rev = "0ecd9de6ddcaf951968d053ae491949d68d6175f";
    hash = "sha256-jaPm1KcK/80ahoIyDP5txEQ3Fihqmwr5DnCz8frzWyk=";
  };

  cmark = fetchFromGitHub {
    owner = "apple";
    repo = "swift-cmark";
    rev = "f218e5d7691f78b55bfa39b367763f4612486c35";
    hash = "sha256-qJpDdwGFf4AwSBsSGJ5yTMh8pr+Xvf0HftWS0NPxQB8=";
  };

  icu = fetchFromGitHub {
    owner = "unicode-org";
    repo = "icu";
    rev = "fd123bf023882f07bfacf51c39111be2f946d8f8";
    hash = "sha256-RKJVoKv40nJqDLqUCtEOaP19OxVk9xjfg8mGfRS1a1k=";
  };

  indexstore-db = fetchFromGitHub {
    owner = "apple";
    repo = "indexstore-db";
    rev = "89ec16c2ac1bb271614e734a2ee792224809eb20";
    hash = "sha256-2EIzEaVLHZ5vwO8skTaq9HoAaLuT9WFVLMgcgGYuVAk=";
  };

  llbuild = fetchFromGitHub {
    owner = "apple";
    repo = "swift-llbuild";
    rev = "d73a305d6e5a82e4bf3bf1727da3d1376e87efab";
    hash = "sha256-wxIpYupJpU0QkAUV/HBmLoWQKGDytIhDOOLzLRjXnw0=";
  };

  llvm-project = fetchFromGitHub {
    owner = "apple";
    repo = "llvm-project";
    rev = "2b42c5ce063a374fb22676e27505a22fe411ea8c";
    hash = "sha256-tup4VEbehYhALECe9LFYz4lC3LGOg7WQ7Fl5JWbYIdk=";
  };

  ninja = fetchFromGitHub {
    owner = "ninja-build";
    repo = "ninja";
    rev = "448ae1ccacd17025457ace965d78a45a113c70c6";
    hash = "sha256-SDCF3yzgb3XV3kCi8vbAlas+5UyfXjVvNdR9SDbGQPM=";
  };

  sourcekit-lsp = fetchFromGitHub {
    owner = "apple";
    repo = "sourcekit-lsp";
    rev = "cb4fb91f772bc40923e30eea38a31206b1a6f912";
    hash = "sha256-YG8TMLLvb5UwgV3wiwgomjk267TEHQV0PNw2OuVugbg=";
  };

  swift = fetchFromGitHub {
    owner = "apple";
    repo = "swift";
    rev = "9142833603ab2e876bd766c08194d76741e09a27";
    hash = "sha256-qm7Z2qlOVRqP7W8LWzlymUx4y8OY4jmnHmv3LqKqsbY=";
  };

  swift-argument-parser = fetchFromGitHub {
    owner = "apple";
    repo = "swift-argument-parser";
    rev = "fee6933f37fde9a5e12a1e4aeaa93fe60116ff2a";
    hash = "sha256-G4Tz/AdL5WbRq93aJnQhMjHLH7dEuhmXL3PPn+0H6vM=";
  };

  swift-asn1 = fetchFromGitHub {
    owner = "apple";
    repo = "swift-asn1";
    rev = "805deae27a7506dcad043604c00a9dc52d465dcb";
    hash = "sha256-jUQ/EewNzssb08IHDZDNhlntv4ACso1hzy6OKpg5n0I=";
  };

  swift-atomics = fetchFromGitHub {
    owner = "apple";
    repo = "swift-atomics";
    rev = "919eb1d83e02121cdb434c7bfc1f0c66ef17febe";
    hash = "sha256-6fMm8q57/KUS+1xRKzCWO+a45tAxK6SKrhXwOuxhZas=";
  };

  swift-certificates = fetchFromGitHub {
    owner = "apple";
    repo = "swift-certificates";
    rev = "35a7df2d9d71c401a47de9be2e3de629a01370c2";
    hash = "sha256-8hy+uMgPJuaoXBwuri8DseVM7eci9YAAv/HuUFbHPTo=";
  };

  swift-cmark-gfm = fetchFromGitHub {
    owner = "apple";
    repo = "swift-cmark";
    rev = "f218e5d7691f78b55bfa39b367763f4612486c35";
    hash = "sha256-qJpDdwGFf4AwSBsSGJ5yTMh8pr+Xvf0HftWS0NPxQB8=";
  };

  swift-collections = fetchFromGitHub {
    owner = "apple";
    repo = "swift-collections";
    rev = "2d33a0ea89c961dcb2b3da2157963d9c0370347e";
    hash = "sha256-vd3yaYKG0xIeH1sCSlNuQUB38NNFzr6C1lme+MUg70w=";
  };

  swift-corelibs-foundation = fetchFromGitHub {
    owner = "apple";
    repo = "swift-corelibs-foundation";
    rev = "5aff3b2861224459fe1f4ba1979d9ca5c4cbb4d3";
    hash = "sha256-9EBBzX4DpjfJHaRp6QWBuMIOFKASrgrt3ILD6aRPzHM=";
  };

  swift-corelibs-libdispatch = fetchFromGitHub {
    owner = "apple";
    repo = "swift-corelibs-libdispatch";
    rev = "2053307c15ce83a68fa50e1c97012c4b6961d6d2";
    hash = "sha256-pta3wJj2LJ/lsYAWQpw0wSGLDMO41mN8Zbl78LUCaQo=";
  };

  swift-corelibs-xctest = fetchFromGitHub {
    owner = "apple";
    repo = "swift-corelibs-xctest";
    rev = "17df9675d90246edd0b5e747d7923c577717b6e1";
    hash = "sha256-5khqzW4YwZHESiV1lmxlPe6kO4GhYsY6LLxvvcbDOEA=";
  };

  swift-crypto = fetchFromGitHub {
    owner = "apple";
    repo = "swift-crypto";
    rev = "33a20e650c33f6d72d822d558333f2085effa3dc";
    hash = "sha256-vBDjXtynl3HMq1RK/hMOu36b+0hX2SRRnwhPNjPUOsU=";
  };

  swift-docc = fetchFromGitHub {
    owner = "apple";
    repo = "swift-docc";
    rev = "a0644adfbe854573d2a2a180be396d9a835460c8";
    hash = "sha256-EXkVgI1hxwa1iu6cBcnHDAhT+oTF4U9cgJ3lKlPSR8c=";
  };

  swift-docc-render-artifact = fetchFromGitHub {
    owner = "apple";
    repo = "swift-docc-render-artifact";
    rev = "71b756c8944e531c88ad0642762e7f2337d1a191";
    hash = "sha256-zmeUjawNzhNB0psR85EKaRIhW++NAgrBifhm3TeMYy0=";
  };

  swift-docc-symbolkit = fetchFromGitHub {
    owner = "apple";
    repo = "swift-docc-symbolkit";
    rev = "d42e3db1c0f97f4a3be9a4552f7003c2959268d5";
    hash = "sha256-wZEcUSjjX79K1v4kzaGWNyXvKTtoWhVtAmLLBA2BtJs=";
  };

  swift-driver = fetchFromGitHub {
    owner = "apple";
    repo = "swift-driver";
    rev = "1b2b851ae4718caffa5f18fd1861bc0ddd1791a3";
    hash = "sha256-bZRw/YE6yNS4YLf4R4RvfrH5NzgiD2OEpSMeQRICAtQ=";
  };

  swift-experimental-string-processing = fetchFromGitHub {
    owner = "apple";
    repo = "swift-experimental-string-processing";
    rev = "e659e86188d88dd4639acb7607e5f4d7f6eab1fd";
    hash = "sha256-SlP2NHidHJ0ABQ/hRqdUkqJgBPvy1DHZCGEEgxz4Nrw=";
  };

  swift-format = fetchFromGitHub {
    owner = "apple";
    repo = "swift-format";
    rev = "1323e87eced56bdcfed1bb78af1f16f39274d032";
    hash = "sha256-TnDZUexCkVxGwcpgsCR2E4fS7kNecP7Sl4wfWk6Ghnw=";
  };

  swift-installer-scripts = fetchFromGitHub {
    owner = "apple";
    repo = "swift-installer-scripts";
    rev = "4d5a3519ca1ed98f556c74e1d99e44bf661ae42b";
    hash = "sha256-s57ABZ1GJkJ7bfOfeyIY1H+fbnCF9MnhndoGf4pr5tw=";
  };

  swift-integration-tests = fetchFromGitHub {
    owner = "apple";
    repo = "swift-integration-tests";
    rev = "dfb0a0a3f3aade3a928c1fc91418727b1044f9cc";
    hash = "sha256-nx1emv1Y02zN6SVXFnxhBa7WavbnC5Rw6bwo5qQc1Ww=";
  };

  swift-llvm-bindings = fetchFromGitHub {
    owner = "apple";
    repo = "swift-llvm-bindings";
    rev = "46c67a9c1018980b92a869ad58a5ac290e64b9e0";
    hash = "sha256-87taAyf52FdH0ERCbvZFqNvCHzeLdCS1rSXBh+mrfkI=";
  };

  swift-lmdb = fetchFromGitHub {
    owner = "apple";
    repo = "swift-lmdb";
    rev = "584941b1236b15bad74d8163785d389c028b1ad8";
    hash = "sha256-dZDN2pBOE0ZPtneQvEjF+AE4PDwbcaTausR2W4lg9Ss=";
  };

  swift-markdown = fetchFromGitHub {
    owner = "apple";
    repo = "swift-markdown";
    rev = "15bbd521f3efd161995ed55179e9984a7d734c61";
    hash = "sha256-VvGNZWr3G302ue4CGJMmj28v7mJnmIn7hDhc9hbAmVY=";
  };

  swift-nio = fetchFromGitHub {
    owner = "apple";
    repo = "swift-nio";
    rev = "1d425b0851ffa2695d488cce1d68df2539f42500";
    hash = "sha256-FscOA/S7on31QCR/MZFjg4ZB3FGJ+rdptZ6MRZJXexE=";
  };

  swift-nio-ssl = fetchFromGitHub {
    owner = "apple";
    repo = "swift-nio-ssl";
    rev = "2e74773972bd6254c41ceeda827f229bccbf1c0f";
    hash = "sha256-5QGkmkCOXhG3uOdf0bd3Fo1MFekB8/WcveBXGhtVZKo=";
  };

  swift-numerics = fetchFromGitHub {
    owner = "apple";
    repo = "swift-numerics";
    rev = "0a23770641f65a4de61daf5425a37ae32a3fd00d";
    hash = "sha256-wGIJ4hMxIBHy8mqmUGFWPR56wPFlI5qS4N7+nsFqLbs=";
  };

  swift-stress-tester = fetchFromGitHub {
    owner = "apple";
    repo = "swift-stress-tester";
    rev = "b74ce5772e40178c464dd2357bccd4c710aacbf0";
    hash = "sha256-m/1gnOoZusgSpC0mrNe3iVBPhgKofGlg51AVQXH+LXo=";
  };

  swift-syntax = fetchFromGitHub {
    owner = "apple";
    repo = "swift-syntax";
    rev = "9a101b70eee2a9dec04f92d2d47b22ebe57a1aae";
    hash = "sha256-yc7pPnBVdFC9lIJ3IwrMI72Rp8BRsQleuK1rtH3x7+0=";
  };

  swift-system = fetchFromGitHub {
    owner = "apple";
    repo = "swift-system";
    rev = "836bc4557b74fe6d2660218d56e3ce96aff76574";
    hash = "sha256-p18QHzO+NtoY/WQzOD+PfD+bjqrIWsbeEbsJLPqEAhA=";
  };

  swift-tools-support-core = fetchFromGitHub {
    owner = "apple";
    repo = "swift-tools-support-core";
    rev = "5665fc7641ce1a971ad06faaa476862b222ef44b";
    hash = "sha256-M6ftbtPayZk6lkU1O8J5KdQOb1Xfo+LldrtkVUQnCHY=";
  };

  swift-xcode-playground-support = fetchFromGitHub {
    owner = "apple";
    repo = "swift-xcode-playground-support";
    rev = "bbba1ba704c37d1d0131bb7d6986a80ad8cb6d6c";
    hash = "sha256-esv5h1SLs/oy7hr4CwhnHufwlBxu2Q+gfbTYU/LlkyE=";
  };

  swiftpm = fetchFromGitHub {
    owner = "apple";
    repo = "swift-package-manager";
    rev = "2b7ebe65a258faf26e7bf57c3b7a36d727017518";
    hash = "sha256-u54/P6qRpKloakBlq+fWqrVhg4RYjxBtDPp281VopwU=";
  };

  yams = fetchFromGitHub {
    owner = "jpsim";
    repo = "Yams";
    rev = "01835dc202670b5bb90d07f3eae41867e9ed29f6";
    hash = "sha256-5qxuCkmopm3uFcoYJKQA8ofW98f53H1gZaPiOh2DS4U=";
  };

}
