# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchgit, fetchFromGitHub, overrides ? (x: y: { }) }:
let
  self = packages // (overrides self packages);
  packages = with self; {
    unicode_util_compat = builder {
      name = "unicode_util_compat";
      version = "0.7.0";
      src = fetchHex {
        pkg = "unicode_util_compat";
        version = "0.7.0";
        sha256 = "sha256-Je7m1n32GWDPanlCOVZlmbCeF+Zo03ACR7xJhjgVJSE=";
      };
      beamDeps = [ ];
    };
    jiffy = builder {
      name = "jiffy";
      version = "1.1.2";
      src = fetchHex {
        pkg = "jiffy";
        version = "1.1.2";
        sha256 = "sha256-u2G8Qqcgu9M8sJpBDki7eaYQEsdMuLPnXybZiEhc84E=";
      };
      beamDeps = [ ];
    };
    base64url = builder {
      name = "base64url";
      version = "1.0.1";
      src = fetchHex {
        pkg = "base64url";
        version = "1.0.1";
        sha256 = "sha256-+bOt1HMaAqmwQQOYtHWzPnVmppU2Ujemve4btEdxn1w=";
      };
      beamDeps = [ ];
    };
    yconf = builder {
      name = "yconf";
      version = "1.0.16";
      src = fetchHex {
        pkg = "yconf";
        version = "1.0.16";
        sha256 = "sha256-6UeBMnPzhxHHsuWo5KzJpRx7voVPdEo0X2AwCzhYbIk=";
      };
      beamDeps = [ fast_yaml ];
    };
    xmpp = builder {
      name = "xmpp";
      version = "1.8.3";
      src = fetchHex {
        pkg = "xmpp";
        version = "1.8.3";
        sha256 = "sha256-7XAGX5qJqBjc/0O3TAgMnn9PFBThBRvt23KA24Ca9xE=";
      };
      beamDeps = [ ezlib fast_tls fast_xml idna p1_utils stringprep ];
    };
    stun = builder {
      name = "stun";
      version = "1.2.14";
      src = fetchHex {
        pkg = "stun";
        version = "1.2.14";
        sha256 = "sha256-4TSAext6jf/ZTmTu/uAOZce0BC89FOFvj0NWbSA3FYM=";
      };
      beamDeps = [ fast_tls p1_utils ];
    };
    stringprep = builder {
      name = "stringprep";
      version = "1.0.30";
      src = fetchHex {
        pkg = "stringprep";
        version = "1.0.30";
        sha256 = "sha256-9vybM4SgOHeDD4my84WAyvP0onRIpKMz1qjDl1wiC5o=";
      };
      beamDeps = [ p1_utils ];
    };
    sqlite3 = builder {
      name = "sqlite3";
      version = "1.1.15";
      src = fetchHex {
        pkg = "sqlite3";
        version = "1.1.15";
        sha256 = "sha256-PAuk4TMiwq1J3k4t3SgxE2at3lS+ro26nZ44iPadKFc=";
      };
      beamDeps = [ ];
    };
    pkix = builder {
      name = "pkix";
      version = "1.0.10";
      src = fetchHex {
        pkg = "pkix";
        version = "1.0.10";
        sha256 = "sha256-4CFk+DCUyxJMQbGrKJiKYV1Uua3DhXXwDxmll6OsXQ4=";
      };
      beamDeps = [ ];
    };
    p1_utils = builder {
      name = "p1_utils";
      version = "1.0.26";
      src = fetchHex {
        pkg = "p1_utils";
        version = "1.0.26";
        sha256 = "sha256-0DeejBFWuYvWT4Epwd4CL8yk8v23SGznO/DtLDN2sEw=";
      };
      beamDeps = [ ];
    };
    p1_pgsql = builder {
      name = "p1_pgsql";
      version = "1.1.27";
      src = fetchHex {
        pkg = "p1_pgsql";
        version = "1.1.27";
        sha256 = "sha256-jk0adgLLaHgOVdidxamy4arKP08e49GiXy+MPSNk/7k=";
      };
      beamDeps = [ xmpp ];
    };
    p1_oauth2 = builder {
      name = "p1_oauth2";
      version = "0.6.14";
      src = fetchHex {
        pkg = "p1_oauth2";
        version = "0.6.14";
        sha256 = "sha256-H9OsR05Dci2dWofG34029pjth697uBy7tmNhRR2Zro8=";
      };
      beamDeps = [ ];
    };
    p1_mysql = builder {
      name = "p1_mysql";
      version = "1.0.24";
      src = fetchHex {
        pkg = "p1_mysql";
        version = "1.0.24";
        sha256 = "sha256-8FiGX2Qlf1B6LGpa/zabE3XbyzCz1CWNrU8bPq/7ZV8=";
      };
      beamDeps = [ ];
    };
    p1_acme = builder {
      name = "p1_acme";
      version = "1.0.23";
      src = fetchHex {
        pkg = "p1_acme";
        version = "1.0.23";
        sha256 = "sha256-jOGW8m49IuoQt4CRIpUEZYeMEn+Adn4yUgeu1+jQ3Vk=";
      };
      beamDeps = [ base64url idna jiffy jose yconf ];
    };
    mqtree = builder {
      name = "mqtree";
      version = "1.0.17";
      src = fetchHex {
        pkg = "mqtree";
        version = "1.0.17";
        sha256 = "sha256-X+i3z4+8R4PQ/OuUZUrCu/MkKljNA5fSSd7YrgIb4qM=";
      };
      beamDeps = [ p1_utils ];
    };
    luerl = builder {
      name = "luerl";
      version = "1.2.0";
      src = fetchHex {
        pkg = "luerl";
        version = "1.2.0";
        sha256 = "sha256-nK/U9glP8PWp0nj9gdYNPgJsggvftsrNSxvZCfIbUl0=";
      };
      beamDeps = [ ];
    };
    jose = builder {
      name = "jose";
      version = "1.11.10";
      src = fetchHex {
        pkg = "jose";
        version = "1.11.10";
        sha256 = "sha256-DWzTb/i6F02ykUj8EStYQhhraKkM6fwrPsOv52WT5hQ=";
      };
      beamDeps = [ ];
    };
    idna = builder {
      name = "idna";
      version = "6.1.1";
      src = fetchHex {
        pkg = "idna";
        version = "6.1.1";
        sha256 = "sha256-kjdut4lEEu0ZrEdeSob3tBPBufu1vRbczVeTQVeUTOo=";
      };
      beamDeps = [ unicode_util_compat ];
    };
    fast_yaml = builder {
      name = "fast_yaml";
      version = "1.0.37";
      src = fetchHex {
        pkg = "fast_yaml";
        version = "1.0.37";
        sha256 = "sha256-jehochv34hckFPfTFI7eDzySK0lkVc1iXdXEQpUVp2k=";
      };
      beamDeps = [ p1_utils ];
    };
    fast_xml = builder {
      name = "fast_xml";
      version = "1.1.52";
      src = fetchHex {
        pkg = "fast_xml";
        version = "1.1.52";
        sha256 = "sha256-eVGSOQ4G0rZQFqaZC7+lcn9KJtKRSAixw8mjLu3NG/0=";
      };
      beamDeps = [ p1_utils ];
    };
    fast_tls = builder {
      name = "fast_tls";
      version = "1.1.21";
      src = fetchHex {
        pkg = "fast_tls";
        version = "1.1.21";
        sha256 = "sha256-ExVCkTk3Al5IzYCqgfADWWhtVQG3ViHnICaoe1IpUFs=";
      };
      beamDeps = [ p1_utils ];
    };
    ezlib = builder {
      name = "ezlib";
      version = "1.0.13";
      src = fetchHex {
        pkg = "ezlib";
        version = "1.0.13";
        sha256 = "sha256-nuYqs/jtVaD9EalWn8uORYaD+VV1QXJyGSsGnwkqv7s=";
      };
      beamDeps = [ p1_utils ];
    };
    esip = builder {
      name = "esip";
      version = "1.0.54";
      src = fetchHex {
        pkg = "esip";
        version = "1.0.54";
        sha256 = "sha256-gYevgZ1yWc2t2vaXJsI572BMmwsCmKXy0+aHv14iN+4=";
      };
      beamDeps = [ fast_tls p1_utils stun ];
    };
    eredis = builder {
      name = "eredis";
      version = "1.2.0";
      src = fetchHex {
        pkg = "eredis";
        version = "1.2.0";
        sha256 = "sha256-2bWr7ywsirqPMqoBggPgs9yLEVd3OyVKsdTCACMX8eE=";
      };
      beamDeps = [ ];
    };
    epam = builder {
      name = "epam";
      version = "1.0.14";
      src = fetchHex {
        pkg = "epam";
        version = "1.0.14";
        sha256 = "sha256-LzRJ5yiFpypsKoQ/VhrdD8L3DXoh9hRWkwpUdHPU2Yk=";
      };
      beamDeps = [ ];
    };
    eimp = builder {
      name = "eimp";
      version = "1.0.23";
      src = fetchHex {
        pkg = "eimp";
        version = "1.0.23";
        sha256 = "sha256-kHx4ACPLKJPk/Evb5qTwLDVZE4Yqxn8OzCZgXoFrYoo=";
      };
      beamDeps = [ p1_utils ];
    };
    cache_tab = builder {
      name = "cache_tab";
      version = "1.0.31";
      src = fetchHex {
        pkg = "cache_tab";
        version = "1.0.31";
        sha256 = "sha256-hYK2CkoJskfvhjVbqeB/zp4R7cA0WndckXH5cccrY1E=";
      };
      beamDeps = [ p1_utils ];
    };
  };
in self
