# Used in the generation of package search database.
{
  # Ensures no aliases are in the results.
  allowAliases = false;

  # Enable recursion into attribute sets that nix-env normally doesn't look into
  # so that we can get a more complete picture of the available packages for the
  # purposes of the index.
  packageOverrides = super:
  let
    recurseIntoAttrs = sets:
      super.lib.genAttrs
        (builtins.filter (set: builtins.hasAttr set super) sets)
        (set: super.recurseIntoAttrs (builtins.getAttr set super));
  in recurseIntoAttrs [
    "adoptopenjdk-bin-11-packages-darwin"
    "adoptopenjdk-bin-11-packages-linux"
    "adoptopenjdk-bin-13-packages-darwin"
    "adoptopenjdk-bin-13-packages-linux"
    "adoptopenjdk-bin-8-packages-darwin"
    "adoptopenjdk-bin-8-packages-linux"
    "agdaPackages"
    "alsamixer"
    # "androidndkPkgs"
    # "androidndkPkgs_18b"
    # "androidndkPkgs_21"
    "androidStudioPackages"
    # "androidenv"
    "apacheHttpdPackages"
    "apacheHttpdPackages_2_4"
    "appimageTools"
    "aspellDicts"
    # "aspellWithDicts"
    # "atomEnv"
    "atomPackages"
    "bat-extras"
    "beam" # TODO nested .packages
    "beamPackages" # different from beam.packages!
    # "bitlbee-plugins"
    "bitscope"
    # "buildBazelPackage"
    # "buildBowerComponents"
    # "buildDotnetPackage"
    # "buildEmscriptenPackage"
    # "buildEnv"
    # "buildFHSUserEnv"
    # "buildFHSUserEnvBubblewrap"
    # "buildFHSUserEnvChroot"
    # "buildGo114Module"
    # "buildGo114Package"
    # "buildGo115Module"
    # "buildGo115Package"
    # "buildGoModule"
    # "buildGoPackage"
    # "buildMaven"
    # "buildPerlPackage"
    # "buildPlatform"
    # "buildRubyGem"
    # "buildRustCrate"
    # "buildRustCrateHelpers"
    # "buildRustCrateTests"
    # "bundlerApp"
    # "bundlerEnv"
    # "bundlerUpdateScript"
    "cataclysmDDA"
    "chickenPackages"
    "chickenPackages_4"
    "chickenPackages_5"
    "cinnamon"
    # "closureInfo"
    # "config"
    "coqPackages"
    "coqPackages_8_10"
    "coqPackages_8_11"
    "coqPackages_8_12"
    "coqPackages_8_5"
    "coqPackages_8_6"
    "coqPackages_8_7"
    "coqPackages_8_8"
    "coqPackages_8_9"
    "cratesIO" # TODO nested .crates
    "ctagsWrapped"
    "cudaPackages"
    "cudnnPackages"
    "curaPlugins"
    "darwin"
    "deadbeefPlugins"
    "defaultCrateOverrides"
    "defaultGemConfig"
    # "deviceTree"
    "dhallPackages"
    # "dhallToNix"
    # "dictDBCollector"
    "dictdDBs"
    # "dockerTools"
    "dotnetCorePackages"
    "dotnetPackages"
    # "dotnetenv"
    # "dotnetfx35" # older dotnetenv
    # "dotnetfx40"
    # "driversi686Linux"
    "dwarf-fortress-packages"
    "eclipses"
    # "eggDerivation"
    "elasticsearch6Plugins"
    "elasticsearch7Plugins"
    "elasticsearchPlugins"
    "elmPackages"
    "emacs26Packages"
    "emacs27Packages"
    "emacsPackages"
    "emacsPackagesNg"
    "emscriptenPackages"
    "enlightenment"
    "eteroj"
    "factorio-mods"
    # "factorio-utils"
    "fcitx-engines"
    "fdbPackages"
    # "fetchCrate"
    # "fetchDockerConfig"
    # "fetchDockerLayer"
    # "fetchFromBitbucket"
    # "fetchFromGitHub"
    # "fetchFromGitLab"
    # "fetchFromGitiles"
    # "fetchFromRepoOrCz"
    # "fetchFromSavannah"
    # "fetchHex"
    # "fetchMavenArtifact"
    # "fetchNuGet"
    # "fetchRepoProject"
    # "fetchbower"
    # "fetchbzr"
    # "fetchcvs"
    # "fetchdarcs"
    # "fetchdocker"
    # "fetchegg"
    # "fetchfossil"
    # "fetchgit"
    # "fetchgitLocal"
    # "fetchgx"
    # "fetchhg"
    # "fetchmtn"
    # "fetchpatch"
    # "fetchs3"
    # "fetchsvn"
    # "fetchsvnssh"
    # "fetchurl"
    # "fetchzip"
    "firefoxPackages"
    "flutterPackages"
    # "formats"
    "fusePackages"
    # "gambit-support"
    "gawkextlib"
    # "genericUpdater"
    # "gerbil-support"
    "gerbilPackages-unstable"
    # "ghc-standalone-archive"
    "gimpPlugins"
    "gitAndTools"
    "gnome2"
    "gnome3"
    "gnomeExtensions"
    "gns3Packages"
    "gnustep"
    # "gradleGen"
    "graylogPlugins"
    "gsignondPlugins"
    "gst_all_1"
    # "haskell"
    "haskellPackages"
    "haxePackages"
    # "hostPlatform"
    "hspellDicts"
    "hunspellDicts"
    "ibus-engines"
    "icingaweb2Modules"
    "idea"
    "idrisPackages"
    "inkscape-extensions"
    "interception-tools-plugins"
    "ir"
    "javaPackages"
    "jetbrains"
    # "jupyter-kernel"
    "kakounePlugins"
    "kbdKeymaps"
    "kdeApplications"
    "kdeFrameworks"
    "kernelPatches"
    "kodiPlugins"
    "languageMachines"
    # "lib"
    "libav_all"
    # "libreoffice-args" # TODO can't be recursed into
    "libretro"
    "libsForQt5"
    "libsForQt512"
    "libsForQt514"
    "libsForQt515"
    "linuxPackages"
    "linuxPackages-libre"
    "linuxPackages-rt"
    "linuxPackages-rt_5_4"
    "linuxPackages-rt_5_6"
    "linuxPackages-rt_latest"
    "linuxPackages_4_14"
    "linuxPackages_4_19"
    "linuxPackages_4_4"
    "linuxPackages_4_9"
    "linuxPackages_5_4"
    "linuxPackages_5_8"
    "linuxPackages_5_9"
    "linuxPackages_hardened"
    "linuxPackages_hardkernel_4_14"
    "linuxPackages_hardkernel_latest"
    "linuxPackages_latest"
    "linuxPackages_latest-libre"
    "linuxPackages_latest_hardened"
    "linuxPackages_latest_xen_dom0"
    "linuxPackages_latest_xen_dom0_hardened"
    "linuxPackages_mptcp"
    "linuxPackages_rpi0"
    "linuxPackages_rpi1"
    "linuxPackages_rpi2"
    "linuxPackages_rpi3"
    "linuxPackages_rpi4"
    "linuxPackages_testing"
    "linuxPackages_testing_bcachefs"
    "linuxPackages_xen_dom0"
    "linuxPackages_xen_dom0_hardened"
    "linuxPackages_zen"
    "lispPackages"
    "llvmPackages"
    "llvmPackages_10"
    "llvmPackages_11"
    "llvmPackages_5"
    "llvmPackages_6"
    "llvmPackages_7"
    "llvmPackages_8"
    "llvmPackages_9"
    "llvmPackages_latest"
    "llvmPackages_rocm"
    "lohit-fonts"
    "lua51Packages"
    "lua52Packages"
    "lua53Packages"
    "luaInterpreters"
    "luaPackages"
    "luajitPackages"
    "lumina"
    "lxqt"
    "magnetophonDSP"
    # "makeAutostartItem"
    # "makeDesktopItem"
    # "makeRustPlatform"
    "mate"
    "matrix-synapse-plugins"
    # "mkSaneConfig"
    # "mkShell"
    "mkspiffs-presets"
    # "moodle-utils"
    "mopidyPackages"
    # "mpdWithFeatures"
    "mpvScripts"
    "multitran"
    # "myEnvFun"
    "neovimUtils"
    "netbsd"
    "netbsdCross"
    "netsurf"
    "nginxModules"
    # "nix-gitignore"
    # "nix-update-script"
    # "nixBufferBuilders"
    "nixos-artwork"
    # "nixosTests"
    "nodePackages"
    "nodePackages_latest"
    "ocaml-ng"
    "ocamlPackages"
    "ocamlPackages_4_00_1"
    "ocamlPackages_4_01_0"
    "ocamlPackages_4_02"
    "ocamlPackages_4_03"
    "ocamlPackages_latest"
    # "ociTools"
    "openlilylib-fonts"
    "openraPackages" # TODO nested .engines .mods
    "pantheon"
    "passExtensions"
    "perl530Packages"
    "perl532Packages"
    "perlInterpreters"
    "perlPackages"
    "perldevelPackages"
    "pharo-vms"
    "php73Extensions"
    "php73Packages"
    "php74Extensions"
    "php74Packages"
    "phpExtensions"
    "phpPackages"
    # "pkgsCross"
    "plasma5"
    "platformioPackages"
    # "platforms"
    "plover"
    # "poetry2nix"
    "postgresql11Packages"
    "postgresqlPackages"
    "purePackages"
    "pypy27Packages"
    "pypy2Packages"
    "pypy3Packages"
    "pypyPackages"
    # "python-setup-hook"
    "python27Packages"
    "python2Packages"
    "python310Packages"
    "python36Packages"
    "python37Packages"
    "python38Packages"
    "python39Packages"
    "python3Packages"
    "pythonDocs"
    "pythonInterpreters"
    "pythonManylinuxPackages"
    "pythonPackages"
    "qt5"
    "qt512"
    "qt514"
    "qt515"
    # "qtEnv"
    # "quake3wrapper"
    "quicklispPackages"
    "quicklispPackagesClisp"
    "quicklispPackagesSBCL"
    "rPackages"
    # "referencesByPopularity"
    # "releaseTools"
    # "replaceDependency"
    "roundcubePlugins"
    "rubyPackages"
    "rubyPackages_2_5"
    "rubyPackages_2_6"
    "rubyPackages_2_7"
    # "rust"
    "rustPackages"
    "rustPackages_1_45"
    "rustPackages_1_46"
    # "rustPlatform"
    # "rust_1_45"
    # "rust_1_46"
    "rxvt-unicode-plugins"
    "sconsPackages"
    # "setupSystemdUnits"
    # "singularity-tools"
    "sisco"
    "skawarePackages"
    # "snapTools"
    # "sourceAndTags"
    # "sourceFromHead"
    "sourceHanPackages"
    "sourceHanSansPackages"
    "sourceHanSerifPackages"
    "sourcehut"
    # "srcOnly"
    # "stdenvAdapters"
    "steamPackages"
    # "stringsWithDeps"
    "sublime3Packages"
    # "substituteAll"
    # "substituteAllFiles"
    "sway-contrib"
    "sweethome3d"
    "tamgamp"
    # "targetPlatform"
    "terraform-providers"
    # "tests"
    "tex-gyre"
    "tex-gyre-math"
    "texFunctions"
    "texlive"
    "titaniumenv"
    "tmuxPlugins"
    "ue4demos"
    "uefitoolPackages"
    "uhhyou"
    "unixODBCDrivers"
    "unixtools"
    # "ut2004Packages"
    "vamp"
    "varnish60Packages"
    "varnish62Packages"
    "varnish63Packages"
    "varnishPackages"
    "vdrPlugins"
    "vimPlugins"
    "vimUtils"
    # "vmTools"
    "vscode-extensions"
    "vscode-utils"
    "webos"
    "weechatScripts"
    "windows"
    "winePackages"
    "wineWowPackages"
    "wmsm"
    # "wrapFirefox"
    # "wrapKakoune"
    # "wrapMpv"
    # "wrapNeovimUnstable"
    # "wrapWeechat"
    # "writers"
    "xbmcPlugins"
    # "xcodeenv"
    "xenPackages"
    "xfce"
    "xfce4-14"
    "xfceUnstable"
    "xlibs"
    "xorg"
    # "yarn2nix-moretea"
    "zabbix"
    "zabbix30"
    "zabbix40"
    "zabbix50"
    "zeroadPackages"
    "zncModules"
  ];
}
