diff -rc bsdiff-orig/Makefile bsdiff-4.2/Makefile
*** bsdiff-orig/Makefile	2004-07-11 20:10:02.000000000 +0200
--- bsdiff-4.2/Makefile	2004-11-29 22:15:05.000000000 +0100
***************
*** 1,7 ****
  CFLAGS		+=	-O3
- .ifdef BZIP2
- CFLAGS		+=	-DBZIP2=\"${BZIP2}\"
- .endif
  
  PREFIX		?=	/usr/local
  INSTALL_PROGRAM	?=	${INSTALL} -c -s -m 555
--- 1,4 ----
***************
*** 13,18 ****
  
  install:
  	${INSTALL_PROGRAM} bsdiff bspatch ${PREFIX}/bin
- .ifndef WITHOUT_MAN
  	${INSTALL_MAN} bsdiff.1 bspatch.1 ${PREFIX}/man/man1
- .endif
--- 10,13 ----
