# generated-package.nix is auto-generated by regenerate-ghc-ng-packages.sh -- DO NOT EDIT MANUALLY!

{ mkDerivation, lib }:
mkDerivation {
  pname = "hp2ps";
  version = "0.1";
  isLibrary = false;
  isExecutable = true;
  description = "Heap Profile to PostScript converter";
  license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
  mainProgram = "hp2ps";
}
