source "https://rubygems.org"

gem "jekyll"

gem "jekyll-avatar"
gem "jekyll-mentions"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jemoji"

# Optional dependencies:
gem "jekyll-coffeescript"
gem "jekyll-compose"
#gem "jekyll-docs"
gem "jekyll-favicon"
gem "jekyll-feed", "~> 0.9"
gem "jekyll-gist"
gem "jekyll-paginate"
gem "jekyll-polyglot"
gem "jekyll-redirect-from"
gem "kramdown-syntax-coderay"
gem "mime-types", "~> 3.0"
gem "rdoc", "~> 6.0"
gem "tomlrb", "~> 1.2"

platform :ruby, :mswin, :mingw, :x64_mingw do
  gem "classifier-reborn", "~> 2.2"
  gem "liquid-c", "~> 4.0"
  gem "yajl-ruby", "~> 1.4"
end
