include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_apple_csp

security_apple_csp_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_apple_csp_HEADER_FILES_DIR = lib

security_apple_csp_CC_FILES = $(wildcard lib/*.cpp)
security_apple_csp_C_FILES = $(wildcard lib/*.c)

include $(GNUSTEP_MAKEFILES)/library.make
