# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "mutter-3.20.0";

  src = fetchurl {
    url = mirror://gnome/sources/mutter/3.20/mutter-3.20.0.tar.xz;
    sha256 = "5644d297b69dd3fb465ed9d998e297667c06d9d372e49ded1d788548a38516f5";
  };
}
