#!/usr/bin/env bash

buildcpath() {
  local path
  while (( $# )); do
    case $1 in
        -isystem)
            shift
            path=$path${path:+':'}$1
    esac
    shift
  done
  echo $path
}

setpaths() {
  local nix_cpath=$(buildcpath ${NIX_CFLAGS_COMPILE})
  export CPATH=${CPATH}${CPATH:+':'}${nix_cpath}

  if [[ -f "$NIX_CC/nix-support/cpath" ]]; then
    export CPATH=${CPATH}${CPATH:+':'}$(< "$NIX_CC/nix-support/cpath")
  fi

  if [[ -f "$NIX_CC/nix-support/cxxpath" ]]; then
    export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}${CPLUS_INCLUDE_PATH:+':'}$(< "$NIX_CC/nix-support/cxxpath")
  fi
}

setpaths

exec -a "$0" @clang@/bin/$(basename $0) "$@"
