#!/bin/sh
# This file is copied from https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/clang-tools/wrapper
# The clang-tools wrapper is commonly used together with the clang package on
# nix, because without the wrapper, clang tools fail to find stdlib includes on
# nix.

buildcpath() {
  local language=$1 path after
  shift
  while (( $# )); do
    case $language:$1 in
        *:-isystem|c++:-cxx-isystem)
            shift
            path=$path${path:+':'}$1
            ;;
        *:-idirafter)
            shift
            after=$after${after:+':'}$1
            ;;
    esac
    shift
  done
  echo $path${after:+':'}$after
}

export CPATH=${CPATH}${CPATH:+':'}$(buildcpath c ${NIX_CFLAGS_COMPILE} \
                                               $(<@libcFlags@)):@clang@/resource-root/include
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}${CPLUS_INCLUDE_PATH:+':'}$(buildcpath c++ ${NIX_CFLAGS_COMPILE} \
                                                                                      $(<@cxxFlags@) \
                                                                                      $(<@libcFlags@)):@clang@/resource-root/include

exec @unwrapped_clang_uml@ "$@"
