# Description: Fix lighthouse Makefile
Index: Makefile
===================================================================
--- ./Makefile	1970-01-01 02:00:01.000000000 +0200
+++ ./Makefile	1970-01-01 02:00:01.000000000 +0200
@@ -19,21 +19,10 @@
 endif
 
 # Library specific
-HAS_GDK := $(shell pkg-config --exists gdk-2.0 echo $?)
-ifdef $(HAS_GDK)
-	CFLAGS+=`pkg-config --cflags gdk-2.0`
-	LDFLAGS+=`pkg-config --libs gdk-2.0`
-else
-	CFLAGS+=-DNO_GDK
-endif
-HAS_PANGO := $(shell pkg-config --exists pango echo $?)
-ifdef $(HAS_PANGO)
-	CFLAGS+=`pkg-config --cflags pango`
-	LDFLAGS+=`pkg-config --libs pango`
-else
-	CFLAGS+=-DNO_PANGO
-endif
-
+CFLAGS+=$(shell pkg-config --cflags gdk-2.0)
+LDFLAGS+=$(shell pkg-config --libs gdk-2.0)
+CFLAGS+=$(shell pkg-config --cflags pango)
+LDFLAGS+=$(shell pkg-config --libs pango)
 
 all: lighthouse
 
