# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "dconf-editor-3.22.0";

  src = fetchurl {
    url = mirror://gnome/sources/dconf-editor/3.22/dconf-editor-3.22.0.tar.xz;
    sha256 = "4ca3c2c3836f4c944f161540d1521507dab8e7bee0cac7d543560808efb9246f";
  };
}
