# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1yqvw8729ihb182rp1mgnw106qyxjgsmliig1rn3ilq26yxxw98l";
    sha256bin64 = "1my9c2w8f24ypiqvg6mk09qwhll0rksscab4vm1y6lxlmdppc2y9";
    version = "61.0.3163.31";
  };
  dev = {
    sha256 = "0sg32g4cpa0633kn8z0rdd0nkp8dvjcpyflzz76i3ra07z7rs6fm";
    sha256bin64 = "08by8bdsnv9wdcn15dkvxwxqywl4hwl1kqgzhqjixsrvn800iwkr";
    version = "62.0.3175.4";
  };
  stable = {
    sha256 = "1rirhwvccidza4q4z1gqdwcd9v1bymh1m9r2cq8jhiabfrjpjbxl";
    sha256bin64 = "1lw349ips0sgyls3arv864yq5xykfn9jilwkalvllaq6yvdvcvlk";
    version = "60.0.3112.90";
  };
}
