include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_dotmac_tp

security_dotmac_tp_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_dotmac_tp_HEADER_FILES_DIR = lib

include $(GNUSTEP_MAKEFILES)/library.make
