include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_filedb

security_filedb_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_filedb_HEADER_FILES_DIR = lib

security_filedb_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
