# This file was generated by go2nix.
{ stdenv, lib, ncurses, goPackages, fetchgit, fetchhg, fetchbzr, fetchsvn }:

with goPackages;

buildGoPackage rec {
  name = "fzf-${version}";
  version = "0.12.2";
  rev = "${version}";

  goPackagePath = "github.com/junegunn/fzf";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/junegunn/fzf";
    sha256 = "02qqcnijv8z3736iczbx082yizpqk02g5k746k7sdgfkgyxydppk";
  };

  buildInputs = [ ncurses ];

  goDeps = ./deps.json;
  
  patchPhase = ''
    sed -i -e "s|expand('<sfile>:h:h').'/bin/fzf'|'$bin/bin/fzf'|" plugin/fzf.vim
    sed -i -e "s|expand('<sfile>:h:h').'/bin/fzf-tmux'|'$bin/bin/fzf-tmux'|" plugin/fzf.vim
  '';

  postInstall= ''
    cp $src/bin/fzf-tmux $bin/bin
    mkdir -p $out/share/vim-plugins
    ln -s $out/share/go/src/github.com/junegunn/fzf $out/share/vim-plugins/${(builtins.parseDrvName fzf.name).name}
  '';
}
