# generated-package.nix is auto-generated by regenerate-ghc-ng-packages.sh -- DO NOT EDIT MANUALLY!

{ mkDerivation, array, base, bytestring, containers, directory
, filepath, ghc, ghc-boot, lib, process, transformers, unix
}:
mkDerivation {
  pname = "ghc-bin";
  version = "9.15.20260322";
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    array base bytestring containers directory filepath ghc ghc-boot
    process transformers unix
  ];
  homepage = "http://www.haskell.org/ghc/";
  description = "The Glorious Glasgow Haskell Compiler";
  license = "unknown";
  mainProgram = "ghc";
}
