#! @bash@/bin/sh -e

## Generic service scripts for NixOS, which provide
## * functions to write state to files (/var/run/nix-services)
## * functions to read state from file (/var/run/nix-services)
## * sanity checking functions

STATEDIR=/var/run/nix-services
