# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "gnome-disk-utility-3.24.1";

  src = fetchurl {
    url = mirror://gnome/sources/gnome-disk-utility/3.24/gnome-disk-utility-3.24.1.tar.xz;
    sha256 = "878f0489947c813b44eb89f5fdc2790d757cd8565f26f22b950d55b8585653a1";
  };
}
