# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "dconf-editor-3.18.0";

  src = fetchurl {
    url = mirror://gnome/sources/dconf-editor/3.18/dconf-editor-3.18.0.tar.xz;
    sha256 = "6579b8b216b068acae7d8301b5e2d57054c85a3f147c92355ffa46a62c052534";
  };
}
