# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, deepseqGenerics, syb }:

cabal.mkDerivation (self: {
  pname = "pandoc-types";
  version = "1.12.4";
  sha256 = "10vlw8iabaay0xqlshagl45ksawlanlg6fyqwv9d448qm32ngvdn";
  buildDepends = [ aeson deepseqGenerics syb ];
  meta = {
    homepage = "http://johnmacfarlane.net/pandoc";
    description = "Types for representing a structured document";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
    maintainers = [ self.stdenv.lib.maintainers.andres ];
  };
})
