--- vpnc-0.5.1.orig/Makefile	2008-02-10 22:22:43.000000000 +0100
+++ vpnc-0.5.1/Makefile	2008-02-10 22:22:32.000000000 +0100
@@ -20,8 +20,8 @@
 # $Id: Makefile 236 2007-09-05 20:40:59Z Joerg Mayer $
 
 DESTDIR=
-PREFIX=/usr/local
-ETCDIR=/etc/vpnc
+PREFIX=$(out)
+ETCDIR=$(out)/etc/vpnc
 BINDIR=$(PREFIX)/bin
 SBINDIR=$(PREFIX)/sbin
 MANDIR=$(PREFIX)/share/man
@@ -71,7 +71,7 @@
 	$(CC) -o $@ $^ $(LDFLAGS)
 
 vpnc.8 : vpnc.8.template makeman.pl vpnc
-	./makeman.pl
+	perl makeman.pl
 
 cisco-decrypt : cisco-decrypt.o config.o supp.o sysdep.o vpnc-debug.o
 	$(CC) -o $@ $^ $(LDFLAGS)
