# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, mtl, mwcRandom, primitive, QuickCheck, vector }:

cabal.mkDerivation (self: {
  pname = "vector-algorithms";
  version = "0.6.0.2";
  sha256 = "1gn2pvgvm9g0dajx2wv305fxwhkpdj9pybrwrm3j2frl4dnj7dcq";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ mtl mwcRandom primitive vector ];
  testDepends = [ QuickCheck vector ];
  meta = {
    homepage = "http://code.haskell.org/~dolio/";
    description = "Efficient algorithms for vector arrays";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = [ self.stdenv.lib.maintainers.andres ];
  };
})
