# Generated by ./update.sh - do not update manually!
# Last updated: 2025-11-08
{ fetchurl }:
{
  aarch64-darwin = {
    version = "1.15.0";
    src = fetchurl {
      url = "https://github.com/NayaTech/NayaFlow-releases/releases/download/v1.15.0/NayaFlow-arm64.dmg";
      hash = "sha256-c1+hCr3K2F9yyc2tFAqrUwReTHZMAWxul3YVjmp3TGg=";
    };
  };
}
