source "https://rubygems.org"

gem 'backup'
gem 'thor'
gem 'open4'
gem 'fog'
gem 'unf' 
gem 'dropbox-sdk', '= 1.5.1' # patched
gem 'net-ssh'
gem 'net-scp'
gem 'net-sftp'
gem 'mail', '= 2.5.4' # patched
gem 'pagerduty'
gem 'twitter'
gem 'hipchat'
gem 'flowdock'
gem 'json'
gem 'dogapi'
gem 'aws-ses'
gem 'rspec'
gem 'fuubar'
gem 'mocha'
gem 'timecop'
