include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = securityd

securityd_HEADER_FILES = $(notdir $(wildcard lib/*.h))
securityd_HEADER_FILES_DIR = lib

securityd_CC_FILES = $(wildcard lib/*.cpp)
securityd_C_FILES = $(wildcard lib/*.c)

include $(GNUSTEP_MAKEFILES)/library.make
