include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_codesigning

security_codesigning_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_codesigning_HEADER_FILES_DIR = lib

security_codesigning_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
