include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_utilities

security_utilities_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_utilities_HEADER_FILES_DIR = lib

security_utilities_C_FILES = $(wildcard lib/*.c)
security_utilities_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
