declare -A pkg_list=(
[ansicolors]=""
[dkjson]=""
[lpty]=""
[lrexlib-gnu]=""
[lrexlib-posix]=""
[ltermbox]=""
[lua-cjson]=""
[lua-cmsgpack]=""
[lua_cliargs]=""
[lua-iconv]=""
[lua-term]=""
[lua-zlib]=""
[luacheck]=""
[luadbi]=""
[luaexpat]=""
[luaffi]="http://luarocks.org/dev"
[luaevent]=""
[luasocket]=""
[luasec]=""
[luafilesystem]=""
[luaposix]=""
[luasec]=""
[luazip]=""
[luuid]=""
[penlight]=""
[say]=""
[std.normalize]=""
[std._debug]=""
[luv]=""
[luasystem]=""

# once we can work with rockspec, we can get rid of these
[mediator_lua]="http://luarocks.org/manifests/teto"
[mpack]="http://luarocks.org/manifests/teto"
[nvim-client]="http://luarocks.org/manifests/teto"
[busted]="http://luarocks.org/manifests/teto" #rc-3won'twork
[luassert]="http://luarocks.org/manifests/teto"

# there is an error in the rockspec buildtype "bultin"
[coxpcall]="https://luarocks.org/manifests/hisham"
[lpeg]="https://luarocks.org/manifests/gvvaughan"
)

