include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_asn1

security_asn1_C_FILES = $(wildcard lib/*.c)
security_asn1_CC_FILES = $(wildcard lib/*.cpp)

security_asn1_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_asn1_HEADER_FILES_DIR = lib

include $(GNUSTEP_MAKEFILES)/library.make
