# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "file-roller-3.16.4";

  src = fetchurl {
    url = mirror://gnome/sources/file-roller/3.16/file-roller-3.16.4.tar.xz;
    sha256 = "5455980b2c9c7eb063d2d65560ae7ab2e7f01b208ea3947e151680231c7a4185";
  };
}
