# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "gnome-photos-3.24.2";

  src = fetchurl {
    url = mirror://gnome/sources/gnome-photos/3.24/gnome-photos-3.24.2.tar.xz;
    sha256 = "31ddc078ad2f6bc4bbfa2f71eb23377782750b9cb2ad2b0e6ff2a1971548cdf9";
  };
}
