include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_ocspd

security_ocspd_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_ocspd_HEADER_FILES_DIR = lib

security_ocspd_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
