include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_mds

security_mds_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_mds_HEADER_FILES_DIR = lib

security_mds_CC_FILES = $(wildcard lib/*.cpp)

include $(GNUSTEP_MAKEFILES)/library.make
