--- ./Makefile
+++ ./Makefile
@@ -45,8 +45,8 @@

 install: all
 	@echo Installing...
-	$(Q)mkdir -p ${DESTDIR}/usr/$(LIBDIR)/alsa-lib/
-	$(Q)install -m 755 $(SND_PCM_BIN) ${DESTDIR}/usr/$(LIBDIR)/alsa-lib/
-	$(Q)install -m 755 $(SND_CTL_BIN) ${DESTDIR}/usr/$(LIBDIR)/alsa-lib/
+	$(Q)mkdir -p ${DESTDIR}/$(LIBDIR)/alsa-lib/
+	$(Q)install -m 755 $(SND_PCM_BIN) ${DESTDIR}/$(LIBDIR)/alsa-lib/
+	$(Q)install -m 755 $(SND_CTL_BIN) ${DESTDIR}/$(LIBDIR)/alsa-lib/

 uninstall:
 	@echo Un-installing...
