diff --git a/clients/Makefile.am b/clients/Makefile.am
index 81d1b57..fec50af 100644
--- a/clients/Makefile.am
+++ b/clients/Makefile.am
@@ -80,6 +80,8 @@ libtoytoolkit_a_SOURCES =			\
 	text-cursor-position-client-protocol.h	\
 	workspaces-protocol.c			\
 	workspaces-client-protocol.h
+libtoytoolkit_a_CPPFLAGS = \
+	$(AM_CPPFLAGS) $(PIXMAN_CFLAGS) $(CAIRO_CFLAGS)
 
 toolkit_libs =						\
 	libtoytoolkit.a					\
@@ -96,6 +98,7 @@ weston_terminal_SOURCES = terminal.c
 weston_terminal_LDADD = $(toolkit_libs) -lutil
 
 image_SOURCES = image.c
+image_CPPFLAGS = $(PIXMAN_CFLAGS) $(CAIRO_CFLAGS)
 image_LDADD = $(toolkit_libs)
 
 cliptest_SOURCES = cliptest.c
@@ -103,6 +106,7 @@ cliptest_CPPFLAGS = $(AM_CPPFLAGS) $(PIXMAN_CFLAGS)
 cliptest_LDADD = $(toolkit_libs) $(PIXMAN_LIBS)
 
 dnd_SOURCES = dnd.c
+dnd_CPPFLAGS = $(PIXMAN_CFLAGS) $(CAIRO_CFLAGS)
 dnd_LDADD = $(toolkit_libs)
 
 smoke_SOURCES = smoke.c
@@ -141,12 +145,15 @@ weston_desktop_shell_SOURCES =			\
 	desktop-shell.c				\
 	desktop-shell-client-protocol.h		\
 	desktop-shell-protocol.c
+weston_desktop_shell_CPPFLAGS = \
+	$(AM_CPPFLAGS) $(PIXMAN_CFLAGS) $(CAIRO_CFLAGS)
 weston_desktop_shell_LDADD = $(toolkit_libs)
 
 weston_tablet_shell_SOURCES =			\
 	tablet-shell.c				\
 	tablet-shell-client-protocol.h		\
 	tablet-shell-protocol.c
+weston_tablet_shell_CPPFLAGS = $(PIXMAN_CFLAGS) $(CAIRO_CFLAGS)
 weston_tablet_shell_LDADD = $(toolkit_libs)
 
 BUILT_SOURCES =					\
