name: NixOS test driver

on:
  pull_request:
    paths:
      - 'nixos/lib/test-driver/**'

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          extra_nix_config: |
            sandbox = true
            auto-allocate-uids = true
            extra-system-features = uid-range
            experimental-features = nix-command auto-allocate-uids cgroups
            extra-sandbox-paths = /dev/net

      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        continue-on-error: true
        with:
          name: ${{ vars.CACHIX_NAME || 'nixpkgs-gha' }}
          extraPullNames: nixpkgs-gha

      - name: Run nixos-test-driver tests
        run: nix-build -A nixosTests.nixos-test-driver
